objects/Campaign_Member_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Member Criterias</relationshipLabel>
        <relationshipName>Campaign_Member_Criterias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Criteria_Groups</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exclude__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_Id__c</fullName>
        <label>Criteria Element</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AND</fullName>
                    <default>true</default>
                    <label>AND</label>
                </value>
                <value>
                    <fullName>OR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>WM_Sync_Status__c</fullName>
        <label>WM Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Synced</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WM_Sync_Type__c</fullName>
        <label>WM_Sync_Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Insert</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Campaign Member Criteria</label>
    <nameField>
        <displayFormat>CMC{0000000000}</displayFormat>
        <label>Campaign Member Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Member Criterias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_AudienceUploadJunction__c.object
<CustomObject>
    <fields>
        <fullName>CRM_AudienceCount__c</fullName>
        <label>Audience Count</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Audience Upload Junctions</relationshipLabel>
        <relationshipName>CRM_AudienceUploadJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRM_ToDelete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>To Delete</label>
        <type>Checkbox</type>
    </fields>
    <label>Audience Upload Junction</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Audience Upload Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audience Upload Junctions</pluralLabel>
    <recordTypes>
        <fullName>Audience_Upload</fullName>
        <active>true</active>
        <description>Will be used to link audience upload records with Campaign</description>
        <label>Audience Upload</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_CampaignGeographyReferenceData__c.object
<CustomObject>
    <description>Stores Reference data for State, county, CBSA and City</description>
    <fields>
        <fullName>CRM_CBSA__c</fullName>
        <description>Stores CBSA Name</description>
        <externalId>true</externalId>
        <inlineHelpText>Stores CBSA Name</inlineHelpText>
        <label>CBSA</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_County__c</fullName>
        <description>Stores County Name of the County Record</description>
        <inlineHelpText>Enter the County Name of the County Record</inlineHelpText>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_CountysStateID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>state record ID for the respective County record</description>
        <inlineHelpText>State Name of the respective County record</inlineHelpText>
        <label>County&apos;s State ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CRM_CampaignGeographyReferenceData__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>State</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CRM_CampaignGeographyReferenceData__c</referenceTo>
        <relationshipName>CRM_CountyStateMapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRM_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Reference data field to activate and deactivate picklistvalue</description>
        <inlineHelpText>Activate value for picklist</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_StateCode__c</fullName>
        <description>State Record: Stores Value of the State Code</description>
        <externalId>true</externalId>
        <inlineHelpText>State Record: Stores Value of the State Code</inlineHelpText>
        <label>State Code</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_State__c</fullName>
        <description>Stores State Name of the State Record</description>
        <externalId>true</externalId>
        <inlineHelpText>Enter the State Name of the State Record</inlineHelpText>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Ref Data - Geography</label>
    <nameField>
        <displayFormat>CGRD-{0000000}</displayFormat>
        <label>Campaign Geography Reference Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ref Data - Geography</pluralLabel>
    <recordTypes>
        <fullName>CBSA</fullName>
        <active>true</active>
        <description>Record Type for CBSA</description>
        <label>CBSA</label>
    </recordTypes>
    <recordTypes>
        <fullName>County</fullName>
        <active>true</active>
        <description>Record Type for County</description>
        <label>County</label>
    </recordTypes>
    <recordTypes>
        <fullName>State</fullName>
        <active>true</active>
        <description>Record Type for State</description>
        <label>State</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_CampaignLocationReferenceData__c.object
<CustomObject>
    <description>Stores Reference Data for Region, Market, Hospital and Service Area</description>
    <fields>
        <fullName>CRM_HospitalCode__c</fullName>
        <description>Stores the Hospital Code</description>
        <inlineHelpText>Stores the Hospital Code</inlineHelpText>
        <label>Hospital Code</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_Hospital__c</fullName>
        <description>Hospital Name</description>
        <inlineHelpText>Hospital Name</inlineHelpText>
        <label>Hospital</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Reference data field to activate and deactivate picklistvalue</description>
        <inlineHelpText>Activate value for piclkist.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_MarketCode__c</fullName>
        <description>Market Record: Stores Value of the Market Code</description>
        <inlineHelpText>Market Record: Stores Value of the Market Code</inlineHelpText>
        <label>Market Code</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_Market__c</fullName>
        <description>Stores Market Name of the Market Record</description>
        <inlineHelpText>Stores Market Name of the Market Record</inlineHelpText>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_RegionCode__c</fullName>
        <description>Code of the respective Region Record</description>
        <inlineHelpText>Code of the respective Region Record</inlineHelpText>
        <label>Region Code</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_Region__c</fullName>
        <description>Stores Region Name</description>
        <inlineHelpText>Stores Region Name</inlineHelpText>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_ServiceAreaCode__c</fullName>
        <label>Service Area Code</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_ServiceArea__c</fullName>
        <description>Stores Service Area Value</description>
        <inlineHelpText>Enter the Service Area</inlineHelpText>
        <label>Service Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Ref Data - Location</label>
    <nameField>
        <displayFormat>CLRD-{0000000}</displayFormat>
        <label>Locations Reference Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ref Data - Locations</pluralLabel>
    <recordTypes>
        <fullName>Hospital</fullName>
        <active>true</active>
        <description>Record Type for Hospital</description>
        <label>Hospital</label>
    </recordTypes>
    <recordTypes>
        <fullName>Market</fullName>
        <active>true</active>
        <description>Record Type for Market</description>
        <label>Market</label>
    </recordTypes>
    <recordTypes>
        <fullName>Region</fullName>
        <active>true</active>
        <description>Record Type for Region</description>
        <label>Region</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_Search_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Search Criterias</relationshipLabel>
        <relationshipName>Search_Criterias_del</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CRM_Search_Criteria_Level_1__c</fullName>
        <label>Search Criteria Level 1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>By Region</fullName>
                </value>
                <value>
                    <fullName>By Market</fullName>
                </value>
                <value>
                    <fullName>By Hospital</fullName>
                </value>
                <value>
                    <fullName>By State</fullName>
                </value>
                <value>
                    <fullName>By County</fullName>
                </value>
                <value>
                    <fullName>By CBSA</fullName>
                </value>
                <value>
                    <fullName>By Distance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CRM_Search_Criteria_Level_2__c</fullName>
        <label>Search Criteria Level 2</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRM_Search_Criteria_Level_3__c</fullName>
        <label>Search Criteria Level 3</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Search Criteria</label>
    <nameField>
        <displayFormat>SC-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Search Criterias</pluralLabel>
    <recordTypes>
        <fullName>Region</fullName>
        <active>true</active>
        <label>Region</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Criteria_Groups.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ailments</fullName>
    </customValue>
    <customValue>
        <fullName>Demographics</fullName>
    </customValue>
    <customValue>
        <fullName>Encounter Aggregates</fullName>
    </customValue>
    <customValue>
        <fullName>Encounter Codes</fullName>
    </customValue>
    <customValue>
        <fullName>Encounters</fullName>
    </customValue>
    <customValue>
        <fullName>Geography</fullName>
    </customValue>
    <customValue>
        <fullName>Health Indices</fullName>
    </customValue>
    <customValue>
        <fullName>Health Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>HRAs</fullName>
    </customValue>
    <customValue>
        <fullName>Interests</fullName>
    </customValue>
    <customValue>
        <fullName>Models</fullName>
    </customValue>
    <customValue>
        <fullName>Physicians</fullName>
    </customValue>
    <customValue>
        <fullName>Survey Responses</fullName>
    </customValue>
    <customValue>
        <fullName>Living Well</fullName>
    </customValue>
    <customValue>
        <fullName>Service Line</fullName>
    </customValue>
    <masterLabel>Criteria Groups</masterLabel>
</GlobalValueSet>

classes/CampaignCriteriaController.cls
public class CampaignCriteriaController
{
    public Campaign objcampaign {get;set;} 
    public Map<String, List<Campaign_Member_Criteria__c>> includeCriteriaMap {get;set;}
    public Map<String, List<Campaign_Member_Criteria__c>> excludeCriteriaMap {get;set;}
    public boolean hasInclusions {get;set;}
    public boolean hasExclusions {get;set;}
    public string wmSyncStatus {get;set;}
    public string homeaddress{get;set;}
    public string homeaddressSL2{get;set;}
    public string homeaddressSL3{get;set;}
    
    public CampaignCriteriaController(ApexPages.StandardController stdController)
    {
        wmSyncStatus = 'Synced';
        this.objcampaign = (Campaign)stdController.getRecord();
        //Changes for PP1 Start
        /*this.objcampaign=[select RecordTypeId,CRM_UploadAudienceCount__c,Current_count__c,Wunderman_Sync__c,
                         Id,List_Order_Id__c,Member_Types__c,Name,of_CampaignMembers__c,of_Members__c,
                         IsActive,Status,Add_Member_Status__c,
                         (SELECT ID, CRM_AudienceCount__c, recordtype.name from CRM_AudienceUploadJunctions__r WHERE RecordTypeId =:ReferenceData_PicklistController.recordTypeId('CRM_AudienceUploadJunction__c','Audience_Upload') AND CRM_ToDelete__c=:false limit 1)
                         from campaign where id=:this.objcampaign.id limit 1];*/
         this.objcampaign=[select RecordTypeId,Current_count__c,Wunderman_Sync__c,
                         Id,List_Order_Id__c,Member_Types__c,Name,of_CampaignMembers__c,of_Members__c,
                         IsActive,Status,Add_Member_Status__c from campaign where id=:this.objcampaign.id limit 1];                
        //Changes for PP1 Start   
        
        List<Campaign_Member_Criteria__c> includeCriterias = [SELECT Id, Field_Id__c, Value__c, Operator__c, Category__c, WM_Sync_Status__c, WM_Sync_Type__c FROM Campaign_Member_Criteria__c WHERE Campaign__c=:objcampaign.Id AND Exclude__c=:false];
        hasInclusions = includeCriterias.size()>0?true:false;
        List<Campaign_Member_Criteria__c> excludeCriterias = [SELECT Id, Field_Id__c, Value__c, Operator__c, Category__c, WM_Sync_Status__c, WM_Sync_Type__c FROM Campaign_Member_Criteria__c WHERE Campaign__c=:objcampaign.Id AND Exclude__c=:true];
        hasExclusions = excludeCriterias.size()>0?true:false;
        includeCriteriaMap = getCriteriaMap(includeCriterias);
        excludeCriteriaMap = getCriteriaMap(excludeCriterias);
        
        
        getHomeAddressCriteria();
    }
        
    private Map<String, List<Campaign_Member_Criteria__c>> getCriteriaMap(List<Campaign_Member_Criteria__c> lstCriterias)
    {
        Map<String, List<Campaign_Member_Criteria__c>> criteriaMap = new Map<String, List<Campaign_Member_Criteria__c>>();
        for(Campaign_Member_Criteria__c criteria: lstCriterias)
        {
             if(criteria.WM_Sync_Type__c !='Delete')
             {
                 if(!criteriaMap.containsKey(criteria.Category__c))
                 {
                     List<Campaign_Member_Criteria__c> criterias = new List<Campaign_Member_Criteria__c>(); 
                     criterias.add(criteria);
                     criteriaMap.put(criteria.Category__c, criterias);
                 }
                 else
                     criteriaMap.get(criteria.Category__c).add(criteria);
             }
             if(wmSyncStatus != 'Failed' && criteria.WM_Sync_Status__c != 'Synced')
                    wmSyncStatus = criteria.WM_Sync_Status__c;
        }
        return criteriaMap;
    }
    
    void getHomeAddressCriteria(){
      CRM_Search_Criteria__c hsl;
      for(CRM_Search_Criteria__c crms : [select id,CRM_Campaign__c,CRM_Search_Criteria_Level_1__c,CRM_Search_Criteria_Level_2__c,CRM_Search_Criteria_Level_3__c from CRM_Search_Criteria__c where CRM_Campaign__c=:objcampaign.Id]){
        hsl = crms;
      }
      
      if(hsl!=null){
        map<string,id> recordTypeMap = new map<string,id>();
    
          for(RecordType rt : [select developerName,id from RecordType where sObjectType='CRM_CampaignGeographyReferenceData__c' OR sObjectType='CRM_CampaignLocationReferenceData__c']){
              recordTypeMap.put(rt.developerName,rt.id);
          }
          
        homeaddress = hsl.CRM_Search_Criteria_Level_1__c;
        
        if(homeaddress=='By Region' || homeaddress=='By Market' || homeaddress=='By Hospital'){
          id recordTypeIds = homeaddress=='By Region'?recordTypeMap.get('Region'):homeaddress=='By Market'?recordTypeMap.get('Market'):recordTypeMap.get('Hospital');
          list<string> saCode = hsl.CRM_Search_Criteria_Level_2__c.split(';');
          for(CRM_CampaignLocationReferenceData__c clrs : [select id,CRM_ServiceArea__c from CRM_CampaignLocationReferenceData__c where CRM_ServiceAreaCode__c IN: saCode AND CRM_IsActive__c=true]){
            if(string.isBlank(homeaddressSL2))
              homeaddressSL2 = clrs.CRM_ServiceArea__c;
            else
              homeaddressSL2 += '; '+clrs.CRM_ServiceArea__c;
          }
          
          list<string> level3Codes = hsl.CRM_Search_Criteria_Level_3__c.split(';');
          for(CRM_CampaignLocationReferenceData__c clrs : [select id,CRM_Hospital__c,CRM_Market__c,CRM_Region__c from CRM_CampaignLocationReferenceData__c where (CRM_HospitalCode__c IN: level3Codes OR CRM_MarketCode__c IN: level3Codes OR CRM_RegionCode__c IN: level3Codes) AND CRM_IsActive__c=true AND recordTypeId=:recordTypeIds]){
            string str;
            if(homeaddress=='By Region')
              str =clrs.CRM_Region__c; 
            else if(homeaddress=='By Market')
              str =clrs.CRM_Market__c;
            else if(homeaddress=='By Hospital')
              str =clrs.CRM_Hospital__c;
            
            if(string.isBlank(homeaddressSL3))
              homeaddressSL3 = str;
            else
              homeaddressSL3 += '; '+str;
          }
          
        }
        if(homeaddress=='By Distance'){
           homeaddressSL2 = hsl.CRM_Search_Criteria_Level_2__c+' Miles';
           
           list<string> level3Codes = hsl.CRM_Search_Criteria_Level_3__c.split(';');
          for(CRM_CampaignLocationReferenceData__c clrs : [select id,CRM_Hospital__c from CRM_CampaignLocationReferenceData__c where CRM_HospitalCode__c IN: level3Codes AND CRM_IsActive__c=true]){
            string str;
            str =clrs.CRM_Hospital__c;
            
            if(string.isBlank(homeaddressSL3))
              homeaddressSL3 = str;
            else
              homeaddressSL3 += '; '+str;
          }
           
        }
        if(homeaddress=='By State' || homeaddress=='By County' || homeaddress=='By CBSA'){
          id recordTypeIds = homeaddress=='By State'?recordTypeMap.get('State'):homeaddress=='By County'?recordTypeMap.get('State'):recordTypeMap.get('CBSA');          
          list<string> saCode = hsl.CRM_Search_Criteria_Level_2__c.split(';');
          set<id> stateIds = new set<id>();
          for(CRM_CampaignGeographyReferenceData__c clrs : [select id,CRM_CBSA__c,CRM_State__c from CRM_CampaignGeographyReferenceData__c where (CRM_StateCode__c IN: saCode OR CRM_CBSA__c IN: saCode) AND CRM_IsActive__c=true AND recordTYpeId=:recordTypeIds]){
            string str;
            if(homeaddress=='By State' || homeaddress=='By County')
              str =clrs.CRM_State__c; 
            else if(homeaddress=='By CBSA')
              str =clrs.CRM_CBSA__c;
            
            if(string.isBlank(homeaddressSL2))
              homeaddressSL2 = str;
            else
              homeaddressSL2 += '; '+str;
              
              stateIds.add(clrs.id);
          }
          
          
          if(hsl.CRM_Search_Criteria_Level_3__c!=null){
              
            list<string> level3Codes = hsl.CRM_Search_Criteria_Level_3__c.split(';');
            for(CRM_CampaignGeographyReferenceData__c clrs : [select id,CRM_County__c from CRM_CampaignGeographyReferenceData__c where CRM_CountysStateID__c IN:stateIds AND CRM_County__c IN: level3Codes AND CRM_IsActive__c=true]){
              if(string.isBlank(homeaddressSL3))
                homeaddressSL3 = clrs.CRM_County__c;
              else
                homeaddressSL3 += '; '+clrs.CRM_County__c;
            }
            
          }
          
          
        }
        
      }
      
    }
}