objects/Campaign_Location__c.object
<CustomObject>
    <fields>
        <fullName>Hospital__c</fullName>
        <formula>Location__r.Hospital__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hospital</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Campaign Location</relationshipLabel>
        <relationshipName>Campaign_Location</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <formula>Location__r.Market__c</formula>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>Location__r.Region__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <label>Campaign Location Information</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Campaign Location No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Geography</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Hospital__c</fullName>
        <label>Hospital</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <displayFormat>LOC-{000000}</displayFormat>
        <label>Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AddLocation_ByServiceArea_Test.cls
@istest
public class AddLocation_ByServiceArea_Test
{
    public static testmethod void Addlocationtestmethod()
     {
        boolean selectAll=false;
        boolean flag = true;
        campaign cmp = marketingDataUtils.CreateCampaign();
        
        Location__c loc= marketingDataUtils.createlocation();
        Campaign_Location__c loc1 =    marketingDataUtils.createLocationInformation(cmp.id, loc.id);

        map<id,Location__c> locmap = new map<id,Location__c>([SELECT Hospital__c,Market__c,Region__c  FROM Location__c WHERE ID=:Loc.id]);
        AddLocation_ByServiceArea_Controller.WrapSearchResult wrap = new AddLocation_ByServiceArea_Controller.WrapSearchResult(loc,flag);
        pagereference testpage = new pagereference ('/apex/AddLocation_ByServiceArea');
        Test.setcurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('id',cmp.id); 
        ApexPages.StandardController sc = new ApexPages.standardController(cmp);
        AddLocation_ByServiceArea_Controller location = new AddLocation_ByServiceArea_Controller(sc) ;       
        location.selectedZipCode ='22222222';
        location.selectedRegion = 'Texas';
        location.selectedMarket = 'Dellas';
        location.selectedHospital = 'ABRAZO ARIZONA HEART HOSPITAL';
        list<SelectOption> sa=new list<SelectOption>();
        sa.add(new SelectOption('test','PSA'));
        sa.add(new SelectOption('SSA','SSA'));
        sa.add(new SelectOption('TSASSA','TSA'));
        location.selectedServiceArea=sa;
        location.handleExistingRecords(locmap);
        location.preparePiclistFields();
        location.searchLocation();
        location.selectAll= true;
        location.masterSelectAll= False;
        location.getsearchResult();
        location.first();
        location.last();
        location.previous();
        location.next();
        location.selectAll= true;
        location.handleSeletedLocation();
        location.saveDemographicServiceArea();
        location.quickSave();
        system.debug('location&&&&'+location);
        location.cancel();
        //location.saveServiceArea();
   }
     
 public static testmethod void Addlocationtestmethod1()
 {
        boolean selectAll=False;
        boolean flag = True;
        //boolean showSearchResult=false;
        set<Integer> visitedPage;
        campaign cmp = marketingDataUtils.CreateCampaign();  
        Location__c loc= marketingDataUtils.createlocation();
        AddLocation_ByServiceArea_Controller.WrapSearchResult wrap = new AddLocation_ByServiceArea_Controller.WrapSearchResult(loc,flag);
        
        pagereference testpage = new pagereference ('/apex/AddLocation_ByServiceArea');
        Test.setcurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('id',cmp.id);
        ApexPages.StandardController sc = new ApexPages.standardController(cmp);
        AddLocation_ByServiceArea_Controller location = new AddLocation_ByServiceArea_Controller(sc) ;
        location.selectedZipCode ='22222222';
        location.selectedRegion = 'Texas';
        location.selectedMarket = 'Dellas';
        location.selectedHospital = 'Atlanta Medical Center';
        list<SelectOption> sa=new list<SelectOption>();
        sa.add(new SelectOption('PSA','PSA'));
        sa.add(new SelectOption('SSA','SSA'));
        sa.add(new SelectOption('TSASSA','TSA'));
        location.selectedServiceArea=sa;  
        
        location.searchLocation();
        location.selectAll= True;
        location.getsearchResult();
        
    }
    public static testmethod void Addlocationtestmethod2()
 {
         
        boolean selectAll=false;
        boolean flag = true;
        campaign cmp = marketingDataUtils.CreateCampaign();
        
        Location__c loc= marketingDataUtils.createlocation();
        Campaign_Location__c loc1 = marketingDataUtils.createLocationInformation(cmp.id, loc.id);

        AddLocation_ByServiceArea_Controller.WrapSearchResult wrap = new AddLocation_ByServiceArea_Controller.WrapSearchResult(loc,flag);
        pagereference testpage = new pagereference ('/apex/AddLocation_ByServiceArea');
        Test.setcurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('id',cmp.id);
        
        ApexPages.StandardController sc = new ApexPages.standardController(cmp);
        
        AddLocation_ByServiceArea_Controller location = new AddLocation_ByServiceArea_Controller(sc) ;
        
        location.selectedZipCode ='22222222';
        location.selectedRegion = 'Texas';
        location.selectedMarket = 'Dellas';
        location.selectedHospital = 'ABRAZO ARIZONA HEART HOSPITAL';
        list<SelectOption> sa=new list<SelectOption>();
        sa.add(new SelectOption('PSA','PSA'));
        sa.add(new SelectOption('SSA','SSA'));
        sa.add(new SelectOption('TSASSA','TSA'));
        location.selectedServiceArea=sa;  
        location.preparePiclistFields();
        location.searchLocation();
        location.getsearchResult(); 
        location.first();
        location.last();
        location.previous();
        location.next();
        location.selectAll= False;
        location.masterSelectAll=True;
        location.handleSeletedLocation();
        location.saveDemographicServiceArea();
        system.debug('location&&&&'+location);
        location.cancel();
   
   }
   
   
    public static testmethod void Test_searchLocation1()
    {
        boolean selectAll=false;
        boolean flag = true;
        campaign cmp = marketingDataUtils.CreateCampaign();
        
        Location__c loc= marketingDataUtils.createlocation();
        Campaign_Location__c loc1 =    marketingDataUtils.createLocationInformation(cmp.id, loc.id);
      
        map<id,Location__c> locmap = new map<id,Location__c>([SELECT Hospital__c,Market__c,Region__c  FROM Location__c WHERE ID=:Loc.id]);
        AddLocation_ByServiceArea_Controller.WrapSearchResult wrap = new AddLocation_ByServiceArea_Controller.WrapSearchResult(loc,flag);
        
        pagereference testpage = new pagereference ('/apex/AddLocation_ByServiceArea');
        Test.setcurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('id',cmp.id); 
        ApexPages.StandardController sc = new ApexPages.standardController(cmp);
        AddLocation_ByServiceArea_Controller location = new AddLocation_ByServiceArea_Controller(sc) ;       
        location.selectedZipCode ='';
        location.selectedRegion = '';
        location.selectedMarket = '';
        location.selectedHospital = '';
        list<SelectOption> sa=new list<SelectOption>();
        
        location.selectedServiceArea=sa;
        
        location.searchLocation();
        location.selectAll= true;
        

    }
    
     public static testmethod void Test_saveServiceArea1()
     {
          boolean selectAll=false;
        boolean flag = true;
        campaign cmp = marketingDataUtils.CreateCampaign();
        
        Location__c loc= marketingDataUtils.createlocation();
        Campaign_Location__c loc1 =    marketingDataUtils.createLocationInformation(cmp.id, loc.id);

        map<id,Location__c> locmap = new map<id,Location__c>([SELECT Hospital__c,Market__c,Region__c  FROM Location__c WHERE ID=:Loc.id]);
        AddLocation_ByServiceArea_Controller.WrapSearchResult wrap = new AddLocation_ByServiceArea_Controller.WrapSearchResult(loc,flag);
        wrap.isSelected=false;
        pagereference testpage = new pagereference ('/apex/AddLocation_ByServiceArea');
        Test.setcurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('id',cmp.id); 
        ApexPages.StandardController sc = new ApexPages.standardController(cmp);
        AddLocation_ByServiceArea_Controller location = new AddLocation_ByServiceArea_Controller(sc) ;       
        location.selectedZipCode ='22222222';
        location.selectedRegion = 'Texas';
        location.selectedMarket = 'Dellas';
        location.selectedHospital = 'ABRAZO ARIZONA HEART HOSPITAL';
        list<SelectOption> sa=new list<SelectOption>();
        sa.add(new SelectOption('test','PSA'));
        sa.add(new SelectOption('SSA','SSA'));
        sa.add(new SelectOption('TSASSA','TSA'));
        location.selectedServiceArea=sa;  
        location.handleExistingRecords(locmap);
        location.preparePiclistFields();
        location.searchLocation();
        location.selectAll= False;
        location.masterSelectAll= True;
        location.getsearchResult();
        location.first();
        location.last();
        location.previous();
        location.next();
        location.selectAll= true;
        location.handleSeletedLocation();
        location.saveDemographicServiceArea();
        location.quickSave();
        system.debug('location&&&&'+location);
        location.cancel();   
        //location.saveServiceArea();
               
   }
   
    
 }