objects/Campaign_Demographics__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Demographics</relationshipLabel>
        <relationshipName>Campaign_Demographics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Campaign Demographics</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Campaign Demographics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Demographics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Campaign_Member_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Member Criterias</relationshipLabel>
        <relationshipName>Campaign_Member_Criterias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Criteria_Groups</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Criteria_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Criteria Group</label>
        <referenceTo>Campaign_Member_Criteria_Group__c</referenceTo>
        <relationshipLabel>Campaign Member Criterias</relationshipLabel>
        <relationshipName>Campaign_Member_Criterias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exclude__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_Id__c</fullName>
        <label>Criteria Element</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AND</fullName>
                    <default>true</default>
                    <label>AND</label>
                </value>
                <value>
                    <fullName>OR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>WM_CriteriaGroup_Id__c</fullName>
        <label>WM CriteriaGroup Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WM_Criteria_Id__c</fullName>
        <externalId>true</externalId>
        <label>WM Criteria Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WM_Sync_Status__c</fullName>
        <label>WM Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Synced</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WM_Sync_Type__c</fullName>
        <label>WM_Sync_Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Insert</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Campaign Member Criteria</label>
    <nameField>
        <displayFormat>CMC{0000000000}</displayFormat>
        <label>Campaign Member Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Member Criterias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Campaign_Member_Criteria_Group__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Member Criteria Groups</relationshipLabel>
        <relationshipName>Campaign_Member_Criteria_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exclude__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <label>Group Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inner_Operator__c</fullName>
        <label>Inner Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AND</fullName>
                </value>
                <value>
                    <fullName>OR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Outer_Operator__c</fullName>
        <label>Outer Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AND</fullName>
                </value>
                <value>
                    <fullName>OR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WM_CriteriaGroup_Id__c</fullName>
        <externalId>true</externalId>
        <label>WM CriteriaGroup Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WM_Parent_group_Id__c</fullName>
        <label>WM Parent group Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Campaign Member Criteria Group</label>
    <nameField>
        <displayFormat>CMCG{000000000}</displayFormat>
        <label>Campaign Member Criteria Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Member Criteria Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Campaign_Member_Search_Critera__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Inner_Operator__c</fullName>
        <label>Inner Operator</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outer_Operator__c</fullName>
        <label>Outer Operator</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requires_SubGroup__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requires SubGroup</label>
        <type>Checkbox</type>
    </fields>
    <label>Campaign Member Search Critera</label>
</CustomObject>

objects/CRM_AudienceUploadJunction__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Audience Upload Junctions</relationshipLabel>
        <relationshipName>CRM_AudienceUploadJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Audience Upload Junction</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Audience Upload Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audience Upload Junctions</pluralLabel>
    <recordTypes>
        <fullName>Audience_Report</fullName>
        <active>true</active>
        <description>Will be used to link audience report to campaign</description>
        <label>Audience Report</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_Search_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Search Criterias</relationshipLabel>
        <relationshipName>Search_Criterias_del</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Search Criteria</label>
    <nameField>
        <displayFormat>SC-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Search Criterias</pluralLabel>
    <recordTypes>
        <fullName>Region</fullName>
        <active>true</active>
        <label>Region</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Data_Element_Identifier__c.object
<CustomObject>
    <fields>
        <fullName>Data_Element_Identifier__c</fullName>
        <label>Data Element Identifier</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Element_Name__c</fullName>
        <label>Data Element Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_Type_Code__c</fullName>
        <label>Display Type Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>SFDC Field Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Value_Mapping__c</fullName>
        <label>Value Mapping</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Data Element Identifier</label>
    <nameField>
        <label>Data Element Identifier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Element Identifiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Geographic_Info_Information__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Geography By Boundary</relationshipLabel>
        <relationshipName>Geographic_Info_Informations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <formula>Geographic_Info__r.ZipCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ZipCode</label>
        <type>Text</type>
    </fields>
    <label>Geographic Info Information</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Geographic Info Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Geographic Info Informations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ICD_Diagnosis_In__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>ICD Diagnosis</relationshipLabel>
        <relationshipName>ICD_Diagnosis_Informations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exclude__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude</label>
        <type>Checkbox</type>
    </fields>
    <label>ICD Diagnosis Information</label>
    <nameField>
        <displayFormat>ICD INFO-{000000}</displayFormat>
        <label>ICD Diagnosis Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICD Diagnosis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tenet_Data_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting will be used for Name Match sync process between Salesforce and Wunderman</description>
    <fields>
        <fullName>Static_Value__c</fullName>
        <label>Static Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Tenet Data Configuration</label>
</CustomObject>

objects/WundermanLogin__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EndpointURL__c</fullName>
        <label>EndpointURL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>GetSession__c</fullName>
        <label>GetSession</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Id__c</fullName>
        <label>Session Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>WundermanLogin</label>
</CustomObject>

globalValueSets/Criteria_Groups.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ailments</fullName>
    </customValue>
    <customValue>
        <fullName>Demographics</fullName>
    </customValue>
    <customValue>
        <fullName>Encounter Aggregates</fullName>
    </customValue>
    <customValue>
        <fullName>Encounter Codes</fullName>
    </customValue>
    <customValue>
        <fullName>Encounters</fullName>
    </customValue>
    <customValue>
        <fullName>Geography</fullName>
    </customValue>
    <customValue>
        <fullName>Health Indices</fullName>
    </customValue>
    <customValue>
        <fullName>Health Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>HRAs</fullName>
    </customValue>
    <customValue>
        <fullName>Interests</fullName>
    </customValue>
    <customValue>
        <fullName>Models</fullName>
    </customValue>
    <customValue>
        <fullName>Physicians</fullName>
    </customValue>
    <customValue>
        <fullName>Survey Responses</fullName>
    </customValue>
    <customValue>
        <fullName>Living Well</fullName>
    </customValue>
    <customValue>
        <fullName>Service Line</fullName>
    </customValue>
    <masterLabel>Criteria Groups</masterLabel>
</GlobalValueSet>

classes/CampaignMemberCriteriaManager_Test.cls
@istest
Private class CampaignMemberCriteriaManager_Test
{
public static testmethod void CampaignMembermethod()
{
list<Campaign_Member_Criteria__c> cmpmembercritera = new list<Campaign_Member_Criteria__c>();
list<WundermanLogin__c> cslist = new list<WundermanLogin__c>();

    Campaign cmp = new Campaign();
        cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmp.Service_Line__c='Burn';
        cmp.CRM_SubServiceLineText__c='Dermatology';
        cmp.Tactic__c='Mail';
        cmp.count_of_index__c ='765';
        cmp.Channel__c='Direct Mail';
        cmp.List_Order_Id__c = 1876757;
          insert cmp; 
 
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
        grp.Campaign__c=cmp.id;
        grp.Exclude__c = True;
        grp.Group_Name__c='test';
        grp.WM_CriteriaGroup_Id__c='12';
        grp.WM_Parent_group_Id__c='677';
        grp.Inner_Operator__c = 'OR';
          insert grp;
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
        mem.Campaign__c=cmp.id;
        mem.Exclude__c=true;
        mem.Category__c = 'Ailments';
        mem.Criteria_Group__c = grp.id;
        mem.Field_Name__c='ZipCode__c';
           insert mem;
        cmpmembercritera.add(mem);
    Data_Element_Identifier__c elementidentifier = new Data_Element_Identifier__c();
        elementidentifier.Data_Element_Identifier__c = 'ZIPCD';
        elementidentifier.Data_Element_Name__c='ZIP Code';
        elementidentifier.Display_Type_Code__c='GEO.MANUAL';
        elementidentifier.Value_Mapping__c='{"Out Patient":"O","In Patient":"I"}';
        elementidentifier.Field_Name__c ='ZipCode__c';
            insert elementidentifier;
    WundermanLogin__c login = new WundermanLogin__c();
        login.EndpointURL__c= 'https://thcintellisight.uat.kbmg.com/IntellisightListAPI/com/wunderman/api/listOrder';
        login.Session_Id__c ='5685179';
        login.Password__c ='tenet1test';
        login.GetSession__c='GetSession.jsp';
        login.Name ='tenettest1';
            insert login;    
            cslist.add(login);
    Campaign_Member_Search_Critera__c searchmem = new Campaign_Member_Search_Critera__c();
        searchmem.Name='Geographicss';
        searchmem.Inner_Operator__c = 'OR';
        searchmem.Outer_Operator__c = 'AND';  
        searchmem.Requires_SubGroup__c=True;
            insert searchmem;
  CRM_AudienceUploadJunction__c  audiencejunction = marketingDataUtils.createAudienceJunction(cmp.id);
         
    			Set<id> juncid = new Set<id>();
        juncid.add(audiencejunction.Id);			
    
                map<string,string> stringmap = new map<string,string>();
                stringmap.put('value','memgrp');
                string listOrderId = '7333';
                String lstordergrpid = '';
                String lstorderexgrpid = '';
                id clonedCampid = cmp.id;
                string fieldName ='ZipCode__c';
                string value = 'Zipcode';
                Id campaignId = cmp.id;
                string stringcampaignId = cmp.id;
                boolean exclude = true;
                string objectname ='Geographic_Info_Information__c';
                integer pageNumber=1;
                List<string> lstWMContactIds =new String[3];
                lstWMContactIds[0]='test';
                lstWMContactIds[1]='test1';
                lstWMContactIds[2]='test2';
                string request='txt';
                string xmlReponse = '<ROOT><RESULT><RETURNCODE>0</RETURNCODE><MESSAGE>Added Criteria element and values</MESSAGE><LIST_ORDER_CRITERIA_ELMNT_ID>4188725</LIST_ORDER_CRITERIA_ELMNT_ID></RESULT></ROOT>';
                 string source='sourc';
 system.debug('&&&id'+campaignId);
Test.startTest();
     string response='<submitMessageResponseObject><responseCode>0</responseCode><transactionId>1568502965</transactionId><attributes><entry><key>NEW_PERSON_IND</key><value>1</value></entry></attributes><jobId>0</jobId><objects><entry><key>person</key><value xsi:type="ns3:person" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns3="com.kbmg.remix.api"><address1>239 GRANT ST</address1><attributes/><city>PARK FOREST</city><country>USA</country><dob>11/03/1971</dob><emailAddress>B_2_WILLIAMS@MYEMAILPROVIDER.COM</emailAddress><firstName>BILLY</firstName><id>WDM1223</id><lastName>WILLIAMS</lastName><middleName>D</middleName><objects/><state>IL</state><suffix>III</suffix><telephone>281.777.9311</telephone></value></entry></objects></submitMessageResponseObject>';
     ID batchID = database.executeBatch(new Audience_dedupeBatch(cmp,juncid),2000);
    Test.setMock(HttpCalloutMock.class, new MockHttpResponse(response));
    CampaignMemberCriteriaManager.insertCriteria(fieldName,value,campaignId,exclude,objectname);
    CampaignMemberCriteriaManager.updateCriteria(fieldName,value,campaignId,exclude);
    CampaignMemberCriteriaManager.deleteCriteria(fieldName,campaignId,exclude);
    CampaignMemberCriteriaManager.addCampaignMemberCriteriasForClonedCampaign(cmpmembercritera,listOrderId,lstordergrpid,lstorderexgrpid,cmp,clonedCampid );
    CampaignMemberCriteriaManager.resetCampaignMemberCriteriasSync(campaignId, batchID);
    CampaignMemberCriteriaManager.setAddOnExclusionCriterias(campaignId);

    system.debug('****stringcampaignId'+stringcampaignId);
    //CampaignMemberCriteriaManager.syncCampaignMemberCriterias(stringcampaignId);
Test.stopTest();
}

public static testmethod void CampaignMembermethod1()
{
list<Campaign_Member_Criteria__c> cmpmembercritera = new list<Campaign_Member_Criteria__c>();

    Campaign cmp = new Campaign();
        cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmp.Service_Line__c='Burn';
        cmp.CRM_SubServiceLineText__c='Dermatology';
        cmp.Tactic__c='Mail';
        cmp.count_of_index__c ='765';
        cmp.Channel__c='Direct Mail';
        cmp.List_Order_Id__c = 76757;
            insert cmp;
          
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
        grp.Campaign__c=cmp.id;
        grp.Exclude__c = True;
        grp.Inner_Operator__c = 'OR';
            insert grp;
          
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
        mem.Campaign__c=cmp.id;
        mem.Exclude__c=true;
        mem.Category__c = 'Ailments';
        mem.Criteria_Group__c = grp.id;
        mem.Field_Name__c='Diagnosis Codes';
        mem.WM_Criteria_Id__c ='444664';
            insert mem;
            cmpmembercritera.add(mem);
          
                id clonedCampid = cmp.id;
                string fieldName ='Diagnosis Codes';
                string objectname ='ICD_Diagnosis_In__c';
                string value = 'Zipcode';
                Id campaignId = cmp.id;
                string stringcampaignId = cmp.id;
                boolean exclude = true;
                
Test.startTest();
    string response='<submitMessageResponseObject><responseCode>0</responseCode><transactionId>1568502965</transactionId><attributes><entry><key>NEW_PERSON_IND</key><value>1</value></entry></attributes><jobId>0</jobId><objects><entry><key>person</key><value xsi:type="ns3:person" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns3="com.kbmg.remix.api"><address1>239 GRANT ST</address1><attributes/><city>PARK FOREST</city><country>USA</country><dob>11/03/1971</dob><emailAddress>B_2_WILLIAMS@MYEMAILPROVIDER.COM</emailAddress><firstName>BILLY</firstName><id>WDM1223</id><lastName>WILLIAMS</lastName><middleName>D</middleName><objects/><state>IL</state><suffix>III</suffix><telephone>281.777.9311</telephone></value></entry></objects></submitMessageResponseObject>';
  Test.setMock(HttpCalloutMock.class, new MockHttpResponse(response));
Test.stopTest();
}
public static testmethod void syncCampaignMemberCriteriasmethod()
{
list<Campaign_Member_Criteria__c> cmpmembercritera = new list<Campaign_Member_Criteria__c>();
    Campaign cmp = new Campaign();
        cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmp.Service_Line__c='Burn';
        cmp.CRM_SubServiceLineText__c='Dermatology';
        cmp.Tactic__c='Mail';
        cmp.Current_count__c =3636;
        cmp.List_Order_Id__c =89334422;
        cmp.List_Order_Select_Grp_Id__c=334823224;
        cmp.count_of_index__c ='765';
        cmp.List_Order_Exclude_Grp_Id__c=387873;
        cmp.Channel__c='Direct Mail';
        insert cmp;
         
    Campaign cmpnew = new Campaign();
        cmpnew.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmpnew.Service_Line__c='Burn';
        cmpnew.CRM_SubServiceLineText__c='Dermatology';
        cmpnew.List_Order_Id__c =893422;
        cmpnew.List_Order_Select_Grp_Id__c=33224;
        cmpnew.count_of_index__c ='765';
        cmpnew.ParentId=cmp.id;
        cmpnew.List_Order_Exclude_Grp_Id__c=387873;
        cmpnew.Channel__c='Direct Mail';
        insert cmpnew;
            
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
        grp.Campaign__c=cmp.id;
        grp.Exclude__c = True;
        grp.Group_Number__c=1;
        grp.WM_CriteriaGroup_Id__c='8130';
        grp.Inner_Operator__c = 'OR';
        insert grp;
        
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
        mem.Campaign__c=cmp.id;
        mem.WM_Sync_Type__c='Insert';
        mem.Field_Id__c='Zip Code';
        mem.WM_Sync_Status__c='Pending';
        mem.Category__c = 'Geography';
        mem.Criteria_Group__c = grp.id;
        mem.Field_Name__c='ZipCode__c';
        mem.Value__c='12345';
        mem.Operator__c='AND';
        insert mem;
        
    Tenet_Data_Configuration__c tenet = new Tenet_Data_Configuration__c();
      tenet.Static_Value__c='9900';
      tenet.Name='Page Size';
      insert tenet;
      
    WundermanLogin__c login = new WundermanLogin__c();
        login.EndpointURL__c= 'https://thcintellisight.uat.kbmg.com/IntellisightListAPI/com/wunderman/api/listOrder';
        login.Session_Id__c ='5685179';
        login.Password__c ='tenet1test';
        login.GetSession__c='GetSession.jsp';
        login.Name ='tenettest1';
        insert login; 
    Data_Element_Identifier__c elementidentifier = new Data_Element_Identifier__c();
        elementidentifier.Data_Element_Identifier__c = '559';
        elementidentifier.Data_Element_Name__c='Zip Code';
        elementidentifier.Field_Name__c ='ZipCode__c';
            insert elementidentifier;
            cmpmembercritera.add(mem);
                
                string stringcampaignId=cmp.id;
                
   CRM_Search_Criteria__c searchcriteria = new CRM_Search_Criteria__c();
     searchcriteria.CRM_Campaign__c=Cmp.id;
     searchcriteria.CRM_Search_Criteria_Level_1__c ='By Distance';
     searchcriteria.CRM_Search_Criteria_Level_2__c ='PSA';
     searchcriteria.CRM_Search_Criteria_Level_3__c ='CR3';
     searchcriteria.CRM_AdditionalZipCodes__c ='';
     searchcriteria.CRM_ExcludedZipCodes__c ='12345';
     insert searchcriteria;
    Test.startTest();
       string response='<submitMessageResponseObject><responseCode>0</responseCode><transactionId>1568502965</transactionId><attributes><entry><key>NEW_PERSON_IND</key><value>1</value></entry></attributes><jobId>0</jobId><objects><entry><key>person</key><value xsi:type="ns3:person" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns3="com.kbmg.remix.api"><address1>239 GRANT ST</address1><attributes/><city>PARK FOREST</city><country>USA</country><dob>11/03/1971</dob><emailAddress>B_2_WILLIAMS@MYEMAILPROVIDER.COM</emailAddress><firstName>BILLY</firstName><id>WDM1223</id><lastName>WILLIAMS</lastName><middleName>D</middleName><objects/><state>IL</state><suffix>III</suffix><telephone>281.777.9311</telephone></value></entry></objects></submitMessageResponseObject>';
       Test.setMock(HttpCalloutMock.class, new MockHttpResponse(response));
       try{
           CampaignMemberCriteriaManager.syncCampaignMemberCriterias(stringcampaignId ,true);
       }Catch(Exception ex){
       }
    Test.stopTest();
    
}   
 public static testmethod void syncCampaignMemberCriteriasmethod1()
{
list<Campaign_Member_Criteria__c> cmpmembercritera = new list<Campaign_Member_Criteria__c>();
    Campaign cmp = new Campaign();
        cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmp.Service_Line__c='Burn';
        cmp.CRM_SubServiceLineText__c='Dermatology';
        cmp.Tactic__c='Mail';
        cmp.Current_count__c =3636;
        cmp.List_Order_Id__c =89334422;
        cmp.List_Order_Select_Grp_Id__c=334823224;
        cmp.count_of_index__c ='765';
        cmp.List_Order_Exclude_Grp_Id__c=387873;
        cmp.Channel__c='Direct Mail';
            insert cmp; 
    Campaign cmpnew = new Campaign();
        cmpnew.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmpnew.Service_Line__c='Burn';
        cmpnew.CRM_SubServiceLineText__c='Dermatology';
        cmpnew.List_Order_Id__c =893422;
        cmpnew.List_Order_Select_Grp_Id__c=33224;
        cmpnew.count_of_index__c ='765';
        cmpnew.ParentId=cmp.id;
        cmpnew.List_Order_Exclude_Grp_Id__c=387873;
        cmpnew.Channel__c='Direct Mail';
            insert cmpnew;
            
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
        grp.Campaign__c=cmp.id;
        grp.Exclude__c = True;
        grp.Group_Number__c=1;
        grp.WM_CriteriaGroup_Id__c='8130';
        grp.Inner_Operator__c = 'OR';
            insert grp;
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
        mem.Campaign__c=cmp.id;
        mem.WM_Sync_Type__c='Insert';
        mem.Exclude__c=False;
        mem.Field_Id__c='Member Type';
        mem.WM_Sync_Status__c='Pending';
        mem.Category__c = 'Ailments';
        mem.Criteria_Group__c = grp.id;
        mem.Field_Name__c='ZipCode__c';
        mem.WM_Criteria_Id__c='4091543';
        mem.Value__c='American Indian';
        mem.Operator__c='AND';
            insert mem;
     WundermanLogin__c login = new WundermanLogin__c();
        login.EndpointURL__c= 'https://thcintellisight.uat.kbmg.com/IntellisightListAPI/com/wunderman/api/listOrder';
        login.Session_Id__c ='5685179';
        login.Password__c ='tenet1test';
        login.GetSession__c='GetSession.jsp';
        login.Name ='tenettest1';
            insert login; 
    Id Recordtypereglocation = Schema.SObjectType.CRM_CampaignLocationReferenceData__c.getRecordTypeInfosByName().get('Region').getRecordTypeId(); 
    CRM_CampaignLocationReferenceData__c locationrefregiondata = new CRM_CampaignLocationReferenceData__c();
     locationrefregiondata.CRM_Region__c='Baylor/Tenet JV Region';
     locationrefregiondata.CRM_RegionCode__c='CR3';
     locationrefregiondata.RecordTypeId=Recordtypereglocation;
     locationrefregiondata.CRM_IsActive__c=True;
            insert locationrefregiondata;
    Id Recordtypemarket = Schema.SObjectType.CRM_CampaignLocationReferenceData__c.getRecordTypeInfosByName().get('Market').getRecordTypeId(); 
    CRM_CampaignLocationReferenceData__c refdata = new CRM_CampaignLocationReferenceData__c();
     refdata.CRM_Market__c='Baylor/Tenet JV Region';
     refdata.CRM_MarketCode__c='CR3';
     refdata.CRM_MarketsRegionID__c=locationrefregiondata.id;
     refdata.RecordTypeId=Recordtypemarket;
     refdata.CRM_IsActive__c=True;
            insert refdata;
     CRM_Search_Criteria__c searchcriteria = new CRM_Search_Criteria__c();
     searchcriteria.CRM_Campaign__c=Cmp.id;
     searchcriteria.CRM_Search_Criteria_Level_1__c ='By Market';
     searchcriteria.CRM_Search_Criteria_Level_2__c ='PSA';
     searchcriteria.CRM_Search_Criteria_Level_3__c ='CR3';
     searchcriteria.CRM_AdditionalZipCodes__c ='';
     searchcriteria.CRM_ExcludedZipCodes__c ='12345';
     
   insert searchcriteria;
    Data_Element_Identifier__c elementidentifier = new Data_Element_Identifier__c();
        elementidentifier.Data_Element_Identifier__c = '559';
        elementidentifier.Data_Element_Name__c='ZIP Code';
        elementidentifier.Field_Name__c ='ZipCode__c';
            insert elementidentifier;
            cmpmembercritera.add(mem);
                
                string stringcampaignId=cmp.id;
                
  
    Test.startTest();
       string response='<submitMessageResponseObject><responseCode>0</responseCode><transactionId>1568502965</transactionId><attributes><entry><key>NEW_PERSON_IND</key><value>1</value></entry></attributes><jobId>0</jobId><objects><entry><key>person</key><value xsi:type="ns3:person" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns3="com.kbmg.remix.api"><address1>239 GRANT ST</address1><attributes/><city>PARK FOREST</city><country>USA</country><dob>11/03/1971</dob><emailAddress>B_2_WILLIAMS@MYEMAILPROVIDER.COM</emailAddress><firstName>BILLY</firstName><id>WDM1223</id><lastName>WILLIAMS</lastName><middleName>D</middleName><objects/><state>IL</state><suffix>III</suffix><telephone>281.777.9311</telephone></value></entry></objects></submitMessageResponseObject>';
  Test.setMock(HttpCalloutMock.class, new MockHttpResponse(response));
       CampaignMemberCriteriaManager.syncCampaignMemberCriterias(stringcampaignId,false);
    Test.stopTest();
    
}
public static testmethod void syncCampaignMemberCriteriasmethod2()
{
list<Campaign_Member_Criteria__c> cmpmembercritera = new list<Campaign_Member_Criteria__c>();
    Campaign cmp = new Campaign();
        cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmp.Service_Line__c='Burn';
        cmp.CRM_SubServiceLineText__c='Dermatology';
        cmp.Tactic__c='Mail';
        cmp.Current_count__c =3636;
        cmp.List_Order_Id__c =89334422;
        cmp.CRM_Refreshed_Count_Date__c=null;
        cmp.List_Order_Select_Grp_Id__c=334823224;
        cmp.count_of_index__c ='765';
        cmp.List_Order_Exclude_Grp_Id__c=387873;
        cmp.Channel__c='Direct Mail';
            insert cmp; 
    Campaign cmpnew = new Campaign();
        cmpnew.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmpnew.Service_Line__c='Burn';
        cmpnew.CRM_SubServiceLineText__c='Dermatology';
        cmpnew.List_Order_Id__c =893422;
        cmpnew.List_Order_Select_Grp_Id__c=33224;
        cmpnew.count_of_index__c ='765';
        cmpnew.ParentId=cmp.id;
        cmpnew.List_Order_Exclude_Grp_Id__c=387873;
        cmpnew.Channel__c='Direct Mail';
            insert cmpnew;
    Campaign_Demographics__c demographic = new Campaign_Demographics__c();
        demographic.Campaign__c= cmp.Id;
        demographic.AgeTo_UI__c =12;
        demographic.AgeFrom_UI__c =22;
        demographic.CRM_Birth_Month__c='Current Month';
            insert demographic;        
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
        grp.Campaign__c=cmp.id;
        grp.Exclude__c = True;
        grp.Group_Number__c=1;
        grp.WM_CriteriaGroup_Id__c='8130';
        grp.Inner_Operator__c = 'OR';
            insert grp;
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
        mem.Campaign__c=cmp.id;
        mem.WM_Sync_Type__c='Delete';
        mem.Exclude__c=False;
        mem.Field_Id__c='Member Type';
        mem.WM_Sync_Status__c='Pending';
        mem.Category__c = 'Ailments';
        mem.Criteria_Group__c = grp.id;
        mem.Field_Name__c='ZipCode__c';
        mem.WM_Criteria_Id__c='4091543';
        mem.Value__c='American Indian';
        mem.Operator__c='AND';
            insert mem;
     WundermanLogin__c login = new WundermanLogin__c();
        login.EndpointURL__c= 'https://thcintellisight.uat.kbmg.com/IntellisightListAPI/com/wunderman/api/listOrder';
        login.Session_Id__c ='5685179';
        login.Password__c ='tenet1test';
        login.GetSession__c='GetSession.jsp';
        login.Name ='tenettest1';
            insert login; 
    Data_Element_Identifier__c elementidentifier = new Data_Element_Identifier__c();
        elementidentifier.Data_Element_Identifier__c = '561';
        elementidentifier.Data_Element_Name__c='Race';
        elementidentifier.Display_Type_Code__c='LIST.BOX.MULTI';
        elementidentifier.Value_Mapping__c='{"Asian":"A","African American":"B","Chinese":"C","Hispanic":"H","American Indian":"I","Jewish":"J","Japanese":"N","Portuguese":"P","Oriental":"R","Caucasian":"W","Uncoded":"U"}';
        elementidentifier.Field_Name__c ='ZipCode__c';
            insert elementidentifier;
            cmpmembercritera.add(mem);
                
                string stringcampaignId=cmp.id;
     CRM_Search_Criteria__c searchcriteria = new CRM_Search_Criteria__c();
     searchcriteria.CRM_Campaign__c=Cmp.id;
     searchcriteria.CRM_Search_Criteria_Level_1__c ='By State';
     searchcriteria.CRM_Search_Criteria_Level_2__c ='PSA';
     searchcriteria.CRM_Search_Criteria_Level_3__c ='CR3';
     searchcriteria.CRM_AdditionalZipCodes__c ='';
     searchcriteria.CRM_ExcludedZipCodes__c ='12345';
     insert searchcriteria;           
  
    Test.startTest();
       string response='<submitMessageResponseObject><responseCode>0</responseCode><transactionId>1568502965</transactionId><attributes><entry><key>NEW_PERSON_IND</key><value>1</value></entry></attributes><jobId>0</jobId><objects><entry><key>person</key><value xsi:type="ns3:person" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns3="com.kbmg.remix.api"><address1>239 GRANT ST</address1><attributes/><city>PARK FOREST</city><country>USA</country><dob>11/03/1971</dob><emailAddress>B_2_WILLIAMS@MYEMAILPROVIDER.COM</emailAddress><firstName>BILLY</firstName><id>WDM1223</id><lastName>WILLIAMS</lastName><middleName>D</middleName><objects/><state>IL</state><suffix>III</suffix><telephone>281.777.9311</telephone></value></entry></objects></submitMessageResponseObject>';
  Test.setMock(HttpCalloutMock.class, new MockHttpResponse(response));
       CampaignMemberCriteriaManager.syncCampaignMemberCriterias(stringcampaignId,false);
    Test.stopTest();
    
}   
 public static testmethod void syncCampaignMemberCriteriasmethod3()
{
list<Campaign_Member_Criteria__c> cmpmembercritera = new list<Campaign_Member_Criteria__c>();
    Campaign cmp = new Campaign();
        cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmp.Service_Line__c='Burn';
        cmp.CRM_SubServiceLineText__c='Dermatology';
        cmp.Tactic__c='Mail';
        cmp.Current_count__c =3636;
        cmp.List_Order_Id__c =89334422;
        cmp.List_Order_Select_Grp_Id__c=334823224;
        cmp.count_of_index__c ='765';
        cmp.List_Order_Exclude_Grp_Id__c=387873;
        cmp.Channel__c='Direct Mail';
            insert cmp; 
    Campaign cmpnew = new Campaign();
        cmpnew.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmpnew.Service_Line__c='Burn';
        cmpnew.CRM_SubServiceLineText__c='Dermatology';
        cmpnew.List_Order_Id__c =893422;
        cmpnew.List_Order_Select_Grp_Id__c=33224;
        cmpnew.count_of_index__c ='765';
        cmpnew.ParentId=cmp.id;
        cmpnew.List_Order_Exclude_Grp_Id__c=387873;
        cmpnew.Channel__c='Direct Mail';
            insert cmpnew;
            
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
        grp.Campaign__c=cmp.id;
        grp.Exclude__c = True;
        grp.Group_Number__c=1;
        grp.WM_CriteriaGroup_Id__c='8130';
        grp.Inner_Operator__c = 'OR';
            insert grp;
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
        mem.Campaign__c=cmp.id;
        mem.WM_Sync_Type__c='Delete';
        mem.Exclude__c=True;
        mem.Field_Id__c='Member Type';
        mem.WM_Sync_Status__c='Pending';
        mem.Category__c = 'Ailments';
        mem.Criteria_Group__c = grp.id;
        mem.Field_Name__c='Race__c';
        mem.WM_Criteria_Id__c='4091543';
        mem.Value__c='American Indian';
        mem.Operator__c='AND';
            insert mem;
     WundermanLogin__c login = new WundermanLogin__c();
        login.EndpointURL__c= 'https://thcintellisight.uat.kbmg.com/IntellisightListAPI/com/wunderman/api/listOrder';
        login.Session_Id__c ='5685179';
        login.Password__c ='tenet1test';
        login.GetSession__c='GetSession.jsp';
        login.Name ='tenettest1';
            insert login; 
    Data_Element_Identifier__c elementidentifier = new Data_Element_Identifier__c();
        elementidentifier.Data_Element_Identifier__c = '561';
        elementidentifier.Data_Element_Name__c='Race';
        elementidentifier.Display_Type_Code__c='LIST.BOX.MULTI';
        elementidentifier.Value_Mapping__c='{"Asian":"A","African American":"B","Chinese":"C","Hispanic":"H","American Indian":"I","Jewish":"J","Japanese":"N","Portuguese":"P","Oriental":"R","Caucasian":"W","Uncoded":"U"}';
        elementidentifier.Field_Name__c ='Race__c';
            insert elementidentifier;
            cmpmembercritera.add(mem);
                
                string stringcampaignId=cmp.id;
                
  
    Test.startTest();
       string response='<submitMessageResponseObject><responseCode>0</responseCode><transactionId>1568502965</transactionId><attributes><entry><key>NEW_PERSON_IND</key><value>1</value></entry></attributes><jobId>0</jobId><objects><entry><key>person</key><value xsi:type="ns3:person" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns3="com.kbmg.remix.api"><address1>239 GRANT ST</address1><attributes/><city>PARK FOREST</city><country>USA</country><dob>11/03/1971</dob><emailAddress>B_2_WILLIAMS@MYEMAILPROVIDER.COM</emailAddress><firstName>BILLY</firstName><id>WDM1223</id><lastName>WILLIAMS</lastName><middleName>D</middleName><objects/><state>IL</state><suffix>III</suffix><telephone>281.777.9311</telephone></value></entry></objects></submitMessageResponseObject>';
  Test.setMock(HttpCalloutMock.class, new MockHttpResponse(response));
       CampaignMemberCriteriaManager.syncCampaignMemberCriterias(stringcampaignId,false);
    Test.stopTest();
    
}
public static testmethod void CampaignMembermethodnew()
{
list<WundermanLogin__c> cslist = new list<WundermanLogin__c>();

    Campaign cmp = new Campaign();
        cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmp.Service_Line__c='Burn';
        cmp.CRM_SubServiceLineText__c='Dermatology';
        cmp.Tactic__c='Mail';
        cmp.count_of_index__c ='765';
        cmp.Channel__c='Direct Mail';
        cmp.List_Order_Id__c = 1876757;
          insert cmp; 
 
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
        grp.Campaign__c=cmp.id;
        grp.Exclude__c = True;
        grp.Group_Name__c='test';
        grp.WM_CriteriaGroup_Id__c='12';
        grp.WM_Parent_group_Id__c='677';
        grp.Inner_Operator__c = 'OR';
          insert grp;
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
        mem.Campaign__c=cmp.id;
        mem.Exclude__c=true;
        mem.WM_Sync_Type__c='insert';
        mem.Category__c = 'Encounters';
        mem.Criteria_Group__c = grp.id;
        mem.Field_Name__c='Facility_ID__c';
           insert mem;

Test.startTest();
     string response='<submitMessageResponseObject><responseCode>0</responseCode><transactionId>1568502965</transactionId><attributes><entry><key>NEW_PERSON_IND</key><value>1</value></entry></attributes><jobId>0</jobId><objects><entry><key>person</key><value xsi:type="ns3:person" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns3="com.kbmg.remix.api"><address1>239 GRANT ST</address1><attributes/><city>PARK FOREST</city><country>USA</country><dob>11/03/1971</dob><emailAddress>B_2_WILLIAMS@MYEMAILPROVIDER.COM</emailAddress><firstName>BILLY</firstName><id>WDM1223</id><lastName>WILLIAMS</lastName><middleName>D</middleName><objects/><state>IL</state><suffix>III</suffix><telephone>281.777.9311</telephone></value></entry></objects></submitMessageResponseObject>';
  Test.setMock(HttpCalloutMock.class, new MockHttpResponse(response));
    CampaignMemberCriteriaManager.setAddOnExclusionCriterias(cmp.id); 
Test.stopTest();
}
 public static testmethod void CampaignMembermethodnew1()
{
list<WundermanLogin__c> cslist = new list<WundermanLogin__c>();

    Campaign cmp = new Campaign();
        cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmp.Service_Line__c='Burn';
        cmp.CRM_SubServiceLineText__c='Dermatology';
        cmp.Tactic__c='Mail';
        cmp.count_of_index__c ='765';
        cmp.Channel__c='Direct Mail';
        cmp.List_Order_Id__c = 1876757;
          insert cmp; 
 
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
        grp.Campaign__c=cmp.id;
        grp.Exclude__c = False;
        grp.Group_Name__c='test';
        grp.WM_CriteriaGroup_Id__c='12';
        grp.WM_Parent_group_Id__c='677';
        grp.Inner_Operator__c = 'OR';
          insert grp;
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
        mem.Campaign__c=cmp.id;
        mem.Exclude__c=False;
        mem.WM_Sync_Type__c='insert';
        mem.Category__c = 'Encounters';
        mem.Criteria_Group__c = grp.id;
        mem.Field_Name__c='ZipCode__c';
           insert mem;

Test.startTest();
     string response='<submitMessageResponseObject><responseCode>0</responseCode><transactionId>1568502965</transactionId><attributes><entry><key>NEW_PERSON_IND</key><value>1</value></entry></attributes><jobId>0</jobId><objects><entry><key>person</key><value xsi:type="ns3:person" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns3="com.kbmg.remix.api"><address1>239 GRANT ST</address1><attributes/><city>PARK FOREST</city><country>USA</country><dob>11/03/1971</dob><emailAddress>B_2_WILLIAMS@MYEMAILPROVIDER.COM</emailAddress><firstName>BILLY</firstName><id>WDM1223</id><lastName>WILLIAMS</lastName><middleName>D</middleName><objects/><state>IL</state><suffix>III</suffix><telephone>281.777.9311</telephone></value></entry></objects></submitMessageResponseObject>';
  Test.setMock(HttpCalloutMock.class, new MockHttpResponse(response));
    CampaignMemberCriteriaManager.setAddOnExclusionCriterias(cmp.id); 
Test.stopTest();
}

public static testmethod void CampaignMembermethodnew2()
{
list<WundermanLogin__c> cslist = new list<WundermanLogin__c>();

    Campaign cmp = new Campaign();
        cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmp.Service_Line__c='Burn';
        cmp.CRM_SubServiceLineText__c='Dermatology';
        cmp.Tactic__c='Mail';
        cmp.count_of_index__c ='765';
        cmp.Channel__c='Direct Mail';
        cmp.List_Order_Id__c = 1876757;
          insert cmp; 
 
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
        grp.Campaign__c=cmp.id;
        grp.Exclude__c = False;
        grp.Group_Name__c='test';
        grp.WM_CriteriaGroup_Id__c='12';
        grp.WM_Parent_group_Id__c='677';
        grp.Inner_Operator__c = 'OR';
          insert grp;
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
        mem.Campaign__c=cmp.id;
        mem.Exclude__c=False;
        mem.WM_Sync_Type__c='insert';
        mem.Category__c = 'Encounters';
        mem.Criteria_Group__c = grp.id;
        mem.Field_Name__c='Diagnosis_Code__c';
           insert mem;

Test.startTest();
     string response='<submitMessageResponseObject><responseCode>0</responseCode><transactionId>1568502965</transactionId><attributes><entry><key>NEW_PERSON_IND</key><value>1</value></entry></attributes><jobId>0</jobId><objects><entry><key>person</key><value xsi:type="ns3:person" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns3="com.kbmg.remix.api"><address1>239 GRANT ST</address1><attributes/><city>PARK FOREST</city><country>USA</country><dob>11/03/1971</dob><emailAddress>B_2_WILLIAMS@MYEMAILPROVIDER.COM</emailAddress><firstName>BILLY</firstName><id>WDM1223</id><lastName>WILLIAMS</lastName><middleName>D</middleName><objects/><state>IL</state><suffix>III</suffix><telephone>281.777.9311</telephone></value></entry></objects></submitMessageResponseObject>';
  Test.setMock(HttpCalloutMock.class, new MockHttpResponse(response));
    CampaignMemberCriteriaManager.setAddOnExclusionCriterias(cmp.id); 
Test.stopTest();
}

public static testmethod void CampaignMembermethodnew3()
{
list<WundermanLogin__c> cslist = new list<WundermanLogin__c>();

    Campaign cmp = new Campaign();
        cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmp.Service_Line__c='Burn';
        cmp.CRM_SubServiceLineText__c='Dermatology';
        cmp.Tactic__c='Mail';
        cmp.count_of_index__c ='765';
        cmp.Channel__c='Direct Mail';
        cmp.List_Order_Id__c = 1876757;
          insert cmp; 
 
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
        grp.Campaign__c=cmp.id;
        grp.Exclude__c = False;
        grp.Group_Name__c='test';
        grp.WM_CriteriaGroup_Id__c='12';
        grp.WM_Parent_group_Id__c='677';
        grp.Inner_Operator__c = 'OR';
          insert grp;
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
        mem.Campaign__c=cmp.id;
        mem.Exclude__c=True;
        mem.WM_Sync_Type__c='insert';
        mem.Category__c = 'Encounters';
        mem.Criteria_Group__c = grp.id;
        mem.Field_Name__c='Procedure_Code__c';
           insert mem;

Test.startTest();
     string response='<submitMessageResponseObject><responseCode>0</responseCode><transactionId>1568502965</transactionId><attributes><entry><key>NEW_PERSON_IND</key><value>1</value></entry></attributes><jobId>0</jobId><objects><entry><key>person</key><value xsi:type="ns3:person" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns3="com.kbmg.remix.api"><address1>239 GRANT ST</address1><attributes/><city>PARK FOREST</city><country>USA</country><dob>11/03/1971</dob><emailAddress>B_2_WILLIAMS@MYEMAILPROVIDER.COM</emailAddress><firstName>BILLY</firstName><id>WDM1223</id><lastName>WILLIAMS</lastName><middleName>D</middleName><objects/><state>IL</state><suffix>III</suffix><telephone>281.777.9311</telephone></value></entry></objects></submitMessageResponseObject>';
  Test.setMock(HttpCalloutMock.class, new MockHttpResponse(response));
    CampaignMemberCriteriaManager.setAddOnExclusionCriterias(cmp.id); 
Test.stopTest();
}

public static testmethod void CampaignMembermethod7()
{
list<Campaign_Member_Criteria__c> cmpmembercritera = new list<Campaign_Member_Criteria__c>();
list<WundermanLogin__c> cslist = new list<WundermanLogin__c>();

    Campaign cmp = new Campaign();
        cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmp.Service_Line__c='Burn';
        cmp.CRM_SubServiceLineText__c='Dermatology';
        cmp.Tactic__c='Mail';
        cmp.count_of_index__c ='765';
        cmp.Channel__c='Direct Mail';
        cmp.List_Order_Id__c = 1876757;
          insert cmp; 
 
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
        grp.Campaign__c=cmp.id;
        grp.Exclude__c = True;
        grp.Group_Name__c='test';
        grp.WM_CriteriaGroup_Id__c='12';
        grp.WM_Parent_group_Id__c='677';
        grp.Inner_Operator__c = 'OR';
          insert grp;
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
        mem.Campaign__c=cmp.id;
        mem.Exclude__c=true;
        mem.Category__c = 'Ailments';
        mem.Criteria_Group__c = grp.id;
        mem.Field_Name__c='ZipCode__c';
        mem.WM_Criteria_Id__c='';
           insert mem;
        cmpmembercritera.add(mem);
    Data_Element_Identifier__c elementidentifier = new Data_Element_Identifier__c();
        elementidentifier.Data_Element_Identifier__c = 'ZIPCD';
        elementidentifier.Data_Element_Name__c='ZIP Code';
        elementidentifier.Display_Type_Code__c='GEO.MANUAL';
        elementidentifier.Value_Mapping__c='{"Out Patient":"O","In Patient":"I"}';
        elementidentifier.Field_Name__c ='ZipCode__c';
            insert elementidentifier;
    WundermanLogin__c login = new WundermanLogin__c();
        login.EndpointURL__c= 'https://thcintellisight.uat.kbmg.com/IntellisightListAPI/com/wunderman/api/listOrder';
        login.Session_Id__c ='5685179';
        login.Password__c ='tenet1test';
        login.GetSession__c='GetSession.jsp';
        login.Name ='tenettest1';
            insert login;    
            cslist.add(login);
    Campaign_Member_Search_Critera__c searchmem = new Campaign_Member_Search_Critera__c();
        searchmem.Name='Geographicss';
        searchmem.Inner_Operator__c = 'OR';
        searchmem.Outer_Operator__c = 'AND';  
        searchmem.Requires_SubGroup__c=false;
            insert searchmem;
 
    CRM_AudienceUploadJunction__c  audiencejunction = marketingDataUtils.createAudienceJunction(cmp.id);
         
    			Set<id> juncid = new Set<id>();
        juncid.add(audiencejunction.Id);
    
                map<string,string> stringmap = new map<string,string>();
                stringmap.put('value','memgrp');
                string listOrderId = '7333';
                String lstordergrpid = '';
                String lstorderexgrpid = '';
                id clonedCampid = cmp.id;
                string fieldName ='ZipCode__c';
                string value = 'Next Month;Current Month';
                Id campaignId = cmp.id;
                string stringcampaignId = cmp.id;
                boolean exclude = False;
                string objectname ='Geographic_Info_Information__c';
                integer pageNumber=1;
                List<string> lstWMContactIds =new String[3];
                lstWMContactIds[0]='test';
                lstWMContactIds[1]='test1';
                lstWMContactIds[2]='test2';
                string request='txt';
                string xmlReponse = '<ROOT><RESULT><RETURNCODE>0</RETURNCODE><MESSAGE>Added Criteria element and values</MESSAGE><LIST_ORDER_CRITERIA_ELMNT_ID>4188725</LIST_ORDER_CRITERIA_ELMNT_ID></RESULT></ROOT>';
                 string source='sourc';
 system.debug('&&&id'+campaignId);
Test.startTest();
     string response='<submitMessageResponseObject><responseCode>0</responseCode><transactionId>1568502965</transactionId><attributes><entry><key>NEW_PERSON_IND</key><value>1</value></entry></attributes><jobId>0</jobId><objects><entry><key>person</key><value xsi:type="ns3:person" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns3="com.kbmg.remix.api"><address1>239 GRANT ST</address1><attributes/><city>PARK FOREST</city><country>USA</country><dob>11/03/1971</dob><emailAddress>B_2_WILLIAMS@MYEMAILPROVIDER.COM</emailAddress><firstName>BILLY</firstName><id>WDM1223</id><lastName>WILLIAMS</lastName><middleName>D</middleName><objects/><state>IL</state><suffix>III</suffix><telephone>281.777.9311</telephone></value></entry></objects></submitMessageResponseObject>';
    ID batchID = database.executeBatch(new Audience_dedupeBatch(cmp,juncid),2000);
    Test.setMock(HttpCalloutMock.class, new MockHttpResponse(response));
    CampaignMemberCriteriaManager.insertCriteria(fieldName,value,campaignId,exclude,objectname);
    CampaignMemberCriteriaManager.updateCriteria(fieldName,value,campaignId,exclude);
    CampaignMemberCriteriaManager.deleteCriteria(fieldName,campaignId,exclude);
    CampaignMemberCriteriaManager.addCampaignMemberCriteriasForClonedCampaign(cmpmembercritera,listOrderId,lstordergrpid,lstorderexgrpid,cmp,clonedCampid );
    CampaignMemberCriteriaManager.resetCampaignMemberCriteriasSync(campaignId,batchID);
    CampaignMemberCriteriaManager.setAddOnExclusionCriterias(campaignId);

    system.debug('****stringcampaignId'+stringcampaignId);
Test.stopTest();
}
public static testmethod void CampaignMembermethod5()
{
list<Campaign_Member_Criteria__c> cmpmembercritera = new list<Campaign_Member_Criteria__c>();
list<WundermanLogin__c> cslist = new list<WundermanLogin__c>();

    Campaign cmp = new Campaign();
        cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmp.Service_Line__c='Burn';
        cmp.CRM_SubServiceLineText__c='Dermatology';
        cmp.Tactic__c='Mail';
        cmp.count_of_index__c ='765';
        cmp.Channel__c='Direct Mail';
        cmp.List_Order_Id__c = 1876757;
          insert cmp; 
 
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
        grp.Campaign__c=cmp.id;
        grp.Exclude__c = True;
        grp.Group_Name__c='test';
        grp.WM_CriteriaGroup_Id__c='12';
        grp.WM_Parent_group_Id__c='677';
        grp.Inner_Operator__c = 'OR';
          insert grp;
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
        mem.Campaign__c=cmp.id;
        mem.Exclude__c=true;
        mem.Category__c = 'Ailments';
        mem.Criteria_Group__c = grp.id;
        mem.Field_Name__c='ZipCode__c';
        String lstorderexgrpid = '';
        mem.WM_Criteria_Id__c='';
           insert mem;
        cmpmembercritera.add(mem);
    Data_Element_Identifier__c elementidentifier = new Data_Element_Identifier__c();
        elementidentifier.Data_Element_Identifier__c = 'ZIPCD';
        elementidentifier.Data_Element_Name__c='ZIP Code';
        elementidentifier.Display_Type_Code__c='GEO.MANUAL';
        elementidentifier.Value_Mapping__c='{"Out Patient":"O","In Patient":"I"}';
        elementidentifier.Field_Name__c ='ZipCode__c';
            insert elementidentifier;
    WundermanLogin__c login = new WundermanLogin__c();
        login.EndpointURL__c= 'https://thcintellisight.uat.kbmg.com/IntellisightListAPI/com/wunderman/api/listOrder';
        login.Session_Id__c ='5685179';
        login.Password__c ='tenet1test';
        login.GetSession__c='GetSession.jsp';
        login.Name ='tenettest1';
            insert login;    
            cslist.add(login);
    Campaign_Member_Search_Critera__c searchmem = new Campaign_Member_Search_Critera__c();
        searchmem.Name='Geographicss';
        searchmem.Inner_Operator__c = 'OR';
        searchmem.Outer_Operator__c = 'AND';  
        searchmem.Requires_SubGroup__c=false;
            insert searchmem;
 
         CRM_AudienceUploadJunction__c  audiencejunction = marketingDataUtils.createAudienceJunction(cmp.id);
         
    			Set<id> juncid = new Set<id>();
        juncid.add(audiencejunction.Id);
    
    
                map<string,string> stringmap = new map<string,string>();
                stringmap.put('value','memgrp');
                string listOrderId = '7333';
                String lstordergrpid = '';
                
                id clonedCampid = cmp.id;
                string fieldName ='ZipCode__c';
                string value = 'Current Month';
                Id campaignId = cmp.id;
                string stringcampaignId = cmp.id;
                boolean exclude = true;
                string objectname ='Geographic_Info_Information__c';
                integer pageNumber=1;
                List<string> lstWMContactIds =new String[3];
                lstWMContactIds[0]='test';
                lstWMContactIds[1]='test1';
                lstWMContactIds[2]='test2';
                string request='txt';
                string xmlReponse = '<ROOT><RESULT><RETURNCODE>0</RETURNCODE><MESSAGE>Added Criteria element and values</MESSAGE><LIST_ORDER_CRITERIA_ELMNT_ID>4188725</LIST_ORDER_CRITERIA_ELMNT_ID></RESULT></ROOT>';
                 string source='sourc';
 system.debug('&&&id'+campaignId);
Test.startTest();
     string response='<submitMessageResponseObject><responseCode>0</responseCode><transactionId>1568502965</transactionId><attributes><entry><key>NEW_PERSON_IND</key><value>1</value></entry></attributes><jobId>0</jobId><objects><entry><key>person</key><value xsi:type="ns3:person" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns3="com.kbmg.remix.api"><address1>239 GRANT ST</address1><attributes/><city>PARK FOREST</city><country>USA</country><dob>11/03/1971</dob><emailAddress>B_2_WILLIAMS@MYEMAILPROVIDER.COM</emailAddress><firstName>BILLY</firstName><id>WDM1223</id><lastName>WILLIAMS</lastName><middleName>D</middleName><objects/><state>IL</state><suffix>III</suffix><telephone>281.777.9311</telephone></value></entry></objects></submitMessageResponseObject>';
    ID batchID = database.executeBatch(new Audience_dedupeBatch(cmp,juncid),2000);
    Test.setMock(HttpCalloutMock.class, new MockHttpResponse(response));
    CampaignMemberCriteriaManager.insertCriteria(fieldName,value,campaignId,exclude,objectname);
    CampaignMemberCriteriaManager.updateCriteria(fieldName,value,campaignId,exclude);
    CampaignMemberCriteriaManager.deleteCriteria(fieldName,campaignId,exclude);
    CampaignMemberCriteriaManager.addCampaignMemberCriteriasForClonedCampaign(cmpmembercritera,listOrderId,lstordergrpid,lstorderexgrpid,cmp,clonedCampid );
    CampaignMemberCriteriaManager.resetCampaignMemberCriteriasSync(campaignId,batchID);
    CampaignMemberCriteriaManager.setAddOnExclusionCriterias(campaignId);

    system.debug('****stringcampaignId'+stringcampaignId);
    
    //CampaignMemberCriteriaManager.syncCampaignMemberCriterias(stringcampaignId,false);
Test.stopTest();
}

public static testmethod void CampaignMembermethodnew4()
{
list<WundermanLogin__c> cslist = new list<WundermanLogin__c>();

    Campaign cmp = new Campaign();
        cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmp.Service_Line__c='Burn';
        cmp.CRM_SubServiceLineText__c='Dermatology';
        cmp.Tactic__c='Mail';
        cmp.count_of_index__c ='765';
        cmp.Channel__c='Direct Mail';
        cmp.List_Order_Id__c = 1876757;
          insert cmp; 
 
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
        grp.Campaign__c=cmp.id;
        grp.Exclude__c = False;
        grp.Group_Name__c='test';
        grp.WM_CriteriaGroup_Id__c='12';
        grp.WM_Parent_group_Id__c='677';
        grp.Inner_Operator__c = 'OR';
          insert grp;
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
        mem.Campaign__c=cmp.id;
        mem.Exclude__c=false;
        mem.WM_Sync_Type__c='Update';
        mem.Category__c = 'Encounters';
        mem.Criteria_Group__c = grp.id;
        mem.Field_Name__c='Procedure_Code__c';
           insert mem;

Test.startTest();
     string response='<submitMessageResponseObject><responseCode>0</responseCode><transactionId>1568502965</transactionId><attributes><entry><key>NEW_PERSON_IND</key><value>1</value></entry></attributes><jobId>0</jobId><objects><entry><key>person</key><value xsi:type="ns3:person" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns3="com.kbmg.remix.api"><address1>239 GRANT ST</address1><attributes/><city>PARK FOREST</city><country>USA</country><dob>11/03/1971</dob><emailAddress>B_2_WILLIAMS@MYEMAILPROVIDER.COM</emailAddress><firstName>BILLY</firstName><id>WDM1223</id><lastName>WILLIAMS</lastName><middleName>D</middleName><objects/><state>IL</state><suffix>III</suffix><telephone>281.777.9311</telephone></value></entry></objects></submitMessageResponseObject>';
     Test.setMock(HttpCalloutMock.class, new MockHttpResponse(response));
     CampaignMemberCriteriaManager.setAddOnExclusionCriterias(cmp.id); 
     
Test.stopTest();
}   

public static testmethod void CoveringBirthMonthLogic () 
{

    Campaign cmp = new Campaign();
    cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
    cmp.Service_Line__c='Burn';
    cmp.CRM_SubServiceLineText__c='Dermatology';
    cmp.Tactic__c='Mail';
    cmp.Current_count__c =3636;
    cmp.List_Order_Id__c =89334422;
    cmp.CRM_Refreshed_Count_Date__c=null;
    cmp.List_Order_Select_Grp_Id__c=334823224;
    cmp.count_of_index__c ='765';
    cmp.List_Order_Exclude_Grp_Id__c=387873;
    cmp.Channel__c='Direct Mail';
    insert cmp; 
    System.assertEquals(cmp.Service_Line__c, 'Burn');
    
    Campaign_Demographics__c demographic = new Campaign_Demographics__c();
    demographic.Campaign__c= cmp.Id;
    demographic.AgeTo_UI__c =12;
    demographic.AgeFrom_UI__c =22;
    demographic.CRM_Birth_Month__c='Current Month';
    insert demographic;
    System.assertEquals(demographic.AgeTo_UI__c, 12);
            
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
    grp.Campaign__c=cmp.id;
    grp.Exclude__c = True;
    grp.Group_Number__c=1;
    grp.WM_CriteriaGroup_Id__c='8130';
    grp.Inner_Operator__c = 'OR';
    insert grp;
    System.assertEquals( grp.Group_Number__c,1);
    
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
    mem.Campaign__c=cmp.id;
    mem.Exclude__c=true;
    mem.Category__c = 'Demographics';
    mem.Criteria_Group__c = grp.id;
    mem.Field_Name__c='CRM_Birth_Month__c';
    String lstorderexgrpid = '';
    mem.WM_Criteria_Id__c='';
    insert mem;
    System.assertEquals(mem.Category__c, 'Demographics');
       
    WundermanLogin__c login = new WundermanLogin__c();
    login.EndpointURL__c= 'https://thcintellisight.uat.kbmg.com/IntellisightListAPI/com/wunderman/api/listOrder';
    login.Session_Id__c ='5685179';
    login.Password__c ='tenet1test';
    login.GetSession__c='GetSession.jsp';
    login.Name ='tenettest1';
    insert login; 
    System.assertEquals(login.Password__c,'tenet1test');
    
    Data_Element_Identifier__c elementidentifier = new Data_Element_Identifier__c();
    elementidentifier.Data_Element_Identifier__c = '561';
    elementidentifier.Field_Name__c ='CRM_Birth_Month__c';
    elementidentifier.Criteria_Group_Name__c = 'Demographics';
    insert elementidentifier;
    string stringcampaignId=cmp.id;
    System.assertEquals(elementidentifier.Field_Name__c,'CRM_Birth_Month__c');
    
    Campaign_Member_Search_Critera__c cs = new Campaign_Member_Search_Critera__c ();
    cs.Requires_SubGroup__c = true;
    cs.Name = 'Demographics';
    cs.Inner_Operator__c = 'OR';
    cs.Outer_Operator__c = 'AND';        
    insert cs;     
    System.assertEquals(cs.Name, 'Demographics');
  
    Test.startTest();
    CampaignMemberCriteriaManager.insertCriteria(mem.Field_Name__c,demographic.CRM_Birth_Month__c,stringcampaignId,false,'Campaign_Demographics__c');
    Test.stopTest();


}
public static testmethod void CoveringBirthMonthLogicScenario2 () 
{

    Campaign cmp = new Campaign();
    cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
    cmp.Service_Line__c='Burn';
    cmp.CRM_SubServiceLineText__c='Dermatology';
    cmp.Tactic__c='Mail';
    cmp.Current_count__c =3636;
    cmp.List_Order_Id__c =89334422;
    cmp.CRM_Refreshed_Count_Date__c=null;
    cmp.List_Order_Select_Grp_Id__c=334823224;
    cmp.count_of_index__c ='765';
    cmp.List_Order_Exclude_Grp_Id__c=387873;
    cmp.Channel__c='Direct Mail';
    insert cmp; 
    System.assertEquals(cmp.Service_Line__c, 'Burn');
    
    Campaign_Demographics__c demographic = new Campaign_Demographics__c();
    demographic.Campaign__c= cmp.Id;
    demographic.AgeTo_UI__c =12;
    demographic.AgeFrom_UI__c =22;
    demographic.CRM_Birth_Month__c='Next Month';
    insert demographic;
    System.assertEquals(demographic.AgeTo_UI__c, 12);
            
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
    grp.Campaign__c=cmp.id;
    grp.Exclude__c = True;
    grp.Group_Number__c=1;
    grp.WM_CriteriaGroup_Id__c='8130';
    grp.Inner_Operator__c = 'OR';
    insert grp;
    System.assertEquals( grp.Group_Number__c,1);
    
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
    mem.Campaign__c=cmp.id;
    mem.Exclude__c=true;
    mem.Category__c = 'Demographics';
    mem.Criteria_Group__c = grp.id;
    mem.Field_Name__c='CRM_Birth_Month__c';
    String lstorderexgrpid = '';
    mem.WM_Criteria_Id__c='';
    insert mem;
    System.assertEquals(mem.Category__c, 'Demographics');
       
    WundermanLogin__c login = new WundermanLogin__c();
    login.EndpointURL__c= 'https://thcintellisight.uat.kbmg.com/IntellisightListAPI/com/wunderman/api/listOrder';
    login.Session_Id__c ='5685179';
    login.Password__c ='tenet1test';
    login.GetSession__c='GetSession.jsp';
    login.Name ='tenettest1';
    insert login; 
    System.assertEquals(login.Password__c,'tenet1test');
    
    Data_Element_Identifier__c elementidentifier = new Data_Element_Identifier__c();
    elementidentifier.Data_Element_Identifier__c = '561';
    elementidentifier.Field_Name__c ='CRM_Birth_Month__c';
    elementidentifier.Criteria_Group_Name__c = 'Demographics';
    insert elementidentifier;
    string stringcampaignId=cmp.id;
    System.assertEquals(elementidentifier.Field_Name__c,'CRM_Birth_Month__c');
    
    Campaign_Member_Search_Critera__c cs = new Campaign_Member_Search_Critera__c ();
    cs.Requires_SubGroup__c = true;
    cs.Name = 'Demographics';
    cs.Inner_Operator__c = 'OR';
    cs.Outer_Operator__c = 'AND';        
    insert cs;     
    System.assertEquals(cs.Name, 'Demographics');     
  
    Test.startTest();
    CampaignMemberCriteriaManager.insertCriteria(mem.Field_Name__c,demographic.CRM_Birth_Month__c,stringcampaignId,false,'Campaign_Demographics__c');
    Test.stopTest();


}
public static testmethod void CoveringBirthMonthLogicScenario3 () 
{

    Campaign cmp = new Campaign();
    cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
    cmp.Service_Line__c='Burn';
    cmp.CRM_SubServiceLineText__c='Dermatology';
    cmp.Tactic__c='Mail';
    cmp.Current_count__c =3636;
    cmp.List_Order_Id__c =89334422;
    cmp.CRM_Refreshed_Count_Date__c=null;
    cmp.List_Order_Select_Grp_Id__c=334823224;
    cmp.count_of_index__c ='765';
    cmp.List_Order_Exclude_Grp_Id__c=387873;
    cmp.Channel__c='Direct Mail';
    insert cmp; 
    System.assertEquals(cmp.Service_Line__c, 'Burn');
    
    Campaign_Demographics__c demographic = new Campaign_Demographics__c();
    demographic.Campaign__c= cmp.Id;
    demographic.AgeTo_UI__c =12;
    demographic.AgeFrom_UI__c =22;
    demographic.CRM_Birth_Month__c='Current Month;Next Month';
    insert demographic;
    System.assertEquals(demographic.AgeTo_UI__c, 12);
            
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
    grp.Campaign__c=cmp.id;
    grp.Exclude__c = True;
    grp.Group_Number__c=1;
    grp.WM_CriteriaGroup_Id__c='8130';
    grp.Inner_Operator__c = 'OR';
    insert grp;
    System.assertEquals( grp.Group_Number__c,1);
    
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
    mem.Campaign__c=cmp.id;
    mem.Exclude__c=true;
    mem.Category__c = 'Demographics';
    mem.Criteria_Group__c = grp.id;
    mem.Field_Name__c='CRM_Birth_Month__c';
    String lstorderexgrpid = '';
    mem.WM_Criteria_Id__c='';
    insert mem;
    System.assertEquals(mem.Category__c, 'Demographics');
       
    WundermanLogin__c login = new WundermanLogin__c();
    login.EndpointURL__c= 'https://thcintellisight.uat.kbmg.com/IntellisightListAPI/com/wunderman/api/listOrder';
    login.Session_Id__c ='5685179';
    login.Password__c ='tenet1test';
    login.GetSession__c='GetSession.jsp';
    login.Name ='tenettest1';
    insert login; 
    System.assertEquals(login.Password__c,'tenet1test');
    
    Data_Element_Identifier__c elementidentifier = new Data_Element_Identifier__c();
    elementidentifier.Data_Element_Identifier__c = '561';
    elementidentifier.Field_Name__c ='CRM_Birth_Month__c';
    elementidentifier.Criteria_Group_Name__c = 'Demographics';
    insert elementidentifier;
    string stringcampaignId=cmp.id;
    System.assertEquals(elementidentifier.Field_Name__c,'CRM_Birth_Month__c');
    
    Campaign_Member_Search_Critera__c cs = new Campaign_Member_Search_Critera__c ();
    cs.Requires_SubGroup__c = true;
    cs.Name = 'Demographics';
    cs.Inner_Operator__c = 'OR';
    cs.Outer_Operator__c = 'AND';        
    insert cs;     
    System.assertEquals(cs.Name, 'Demographics');   
  
    Test.startTest();
    CampaignMemberCriteriaManager.insertCriteria(mem.Field_Name__c,demographic.CRM_Birth_Month__c,stringcampaignId,false,'Campaign_Demographics__c');
    Test.stopTest();


}
public static testmethod void CoveringBirthMonthOnRefresh () 
{

    Campaign cmp = new Campaign();
    cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
    cmp.Service_Line__c='Burn';
    cmp.CRM_SubServiceLineText__c='Dermatology';
    cmp.Tactic__c='Mail';
    cmp.Current_count__c =3636;
    cmp.List_Order_Id__c =89334422;
    cmp.CRM_Refreshed_Count_Date__c=null;
    cmp.List_Order_Select_Grp_Id__c=334823224;
    cmp.count_of_index__c ='765';
    cmp.List_Order_Exclude_Grp_Id__c=387873;
    cmp.Channel__c='Direct Mail';
    insert cmp; 
    System.assertEquals(cmp.Service_Line__c, 'Burn');
    
    Campaign_Demographics__c demographic = new Campaign_Demographics__c();
    demographic.Campaign__c= cmp.Id;
    demographic.AgeTo_UI__c =12;
    demographic.AgeFrom_UI__c =22;
    demographic.CRM_Birth_Month__c='Current Month';
    insert demographic;
    System.assertEquals(demographic.AgeTo_UI__c, 12);
            
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
    grp.Campaign__c=cmp.id;
    grp.Exclude__c = True;
    grp.Group_Number__c=1;
    grp.WM_CriteriaGroup_Id__c='8130';
    grp.Inner_Operator__c = 'OR';
    insert grp;
    System.assertEquals( grp.Group_Number__c,1);
    
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
    mem.Campaign__c=cmp.id;
    mem.Exclude__c=true;
    mem.Category__c = 'Demographics';
    mem.Criteria_Group__c = grp.id;
    mem.Field_Name__c='CRM_Birth_Month__c';
    String lstorderexgrpid = '';
    mem.WM_Criteria_Id__c='';
    insert mem;
    System.assertEquals(mem.Category__c, 'Demographics');
       
    WundermanLogin__c login = new WundermanLogin__c();
    login.EndpointURL__c= 'https://thcintellisight.uat.kbmg.com/IntellisightListAPI/com/wunderman/api/listOrder';
    login.Session_Id__c ='5685179';
    login.Password__c ='tenet1test';
    login.GetSession__c='GetSession.jsp';
    login.Name ='tenettest1';
    insert login; 
    System.assertEquals(login.Password__c,'tenet1test');
    
    Data_Element_Identifier__c elementidentifier = new Data_Element_Identifier__c();
    elementidentifier.Data_Element_Identifier__c = '561';
    elementidentifier.Field_Name__c ='CRM_Birth_Month__c';
    elementidentifier.Criteria_Group_Name__c = 'Demographics';
    insert elementidentifier;
    string stringcampaignId=cmp.id;
    System.assertEquals(elementidentifier.Field_Name__c,'CRM_Birth_Month__c');
  
    Test.startTest();
     string response='<submitMessageResponseObject><responseCode>0</responseCode><transactionId>1568502965</transactionId><attributes><entry><key>NEW_PERSON_IND</key><value>1</value></entry></attributes><jobId>0</jobId><objects><entry><key>person</key><value xsi:type="ns3:person" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns3="com.kbmg.remix.api"><address1>239 GRANT ST</address1><attributes/><city>PARK FOREST</city><country>USA</country><dob>11/03/1971</dob><emailAddress>B_2_WILLIAMS@MYEMAILPROVIDER.COM</emailAddress><firstName>BILLY</firstName><id>WDM1223</id><lastName>WILLIAMS</lastName><middleName>D</middleName><objects/><state>IL</state><suffix>III</suffix><telephone>281.777.9311</telephone></value></entry></objects></submitMessageResponseObject>';
     Test.setMock(HttpCalloutMock.class, new MockHttpResponse(response));
     try{
     CampaignMemberCriteriaManager.syncCampaignMemberCriterias(stringcampaignId,true);
     }Catch(Exception ex){
     }
    Test.stopTest();


}
public static testmethod void CoveringBirthMonthOnRefreshScen2 () 
{

    Campaign cmp = new Campaign();
    cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
    cmp.Service_Line__c='Burn';
    cmp.CRM_SubServiceLineText__c='Dermatology';
    cmp.Tactic__c='Mail';
    cmp.Current_count__c =3636;
    cmp.List_Order_Id__c =89334422;
    cmp.CRM_Refreshed_Count_Date__c=null;
    cmp.List_Order_Select_Grp_Id__c=334823224;
    cmp.count_of_index__c ='765';
    cmp.List_Order_Exclude_Grp_Id__c=387873;
    cmp.Channel__c='Direct Mail';
    insert cmp; 
    System.assertEquals(cmp.Service_Line__c, 'Burn');
    
    Campaign_Demographics__c demographic = new Campaign_Demographics__c();
    demographic.Campaign__c= cmp.Id;
    demographic.AgeTo_UI__c =12;
    demographic.AgeFrom_UI__c =22;
    demographic.CRM_Birth_Month__c='Next Month';
    insert demographic;
    System.assertEquals(demographic.AgeTo_UI__c, 12);
            
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
    grp.Campaign__c=cmp.id;
    grp.Exclude__c = True;
    grp.Group_Number__c=1;
    grp.WM_CriteriaGroup_Id__c='8130';
    grp.Inner_Operator__c = 'OR';
    insert grp;
    System.assertEquals( grp.Group_Number__c,1);
    
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
    mem.Campaign__c=cmp.id;
    mem.Exclude__c=true;
    mem.Category__c = 'Demographics';
    mem.Criteria_Group__c = grp.id;
    mem.Field_Name__c='CRM_Birth_Month__c';
    String lstorderexgrpid = '';
    mem.WM_Criteria_Id__c='';
    insert mem;
    System.assertEquals(mem.Category__c, 'Demographics');
       
    WundermanLogin__c login = new WundermanLogin__c();
    login.EndpointURL__c= 'https://thcintellisight.uat.kbmg.com/IntellisightListAPI/com/wunderman/api/listOrder';
    login.Session_Id__c ='5685179';
    login.Password__c ='tenet1test';
    login.GetSession__c='GetSession.jsp';
    login.Name ='tenettest1';
    insert login; 
    System.assertEquals(login.Password__c,'tenet1test');
    
    Data_Element_Identifier__c elementidentifier = new Data_Element_Identifier__c();
    elementidentifier.Data_Element_Identifier__c = '561';
    elementidentifier.Field_Name__c ='CRM_Birth_Month__c';
    elementidentifier.Criteria_Group_Name__c = 'Demographics';
    insert elementidentifier;
    string stringcampaignId=cmp.id;
    System.assertEquals(elementidentifier.Field_Name__c,'CRM_Birth_Month__c');
                
  
    Test.startTest();
    string response='<submitMessageResponseObject><responseCode>0</responseCode><transactionId>1568502965</transactionId><attributes><entry><key>NEW_PERSON_IND</key><value>1</value></entry></attributes><jobId>0</jobId><objects><entry><key>person</key><value xsi:type="ns3:person" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns3="com.kbmg.remix.api"><address1>239 GRANT ST</address1><attributes/><city>PARK FOREST</city><country>USA</country><dob>11/03/1971</dob><emailAddress>B_2_WILLIAMS@MYEMAILPROVIDER.COM</emailAddress><firstName>BILLY</firstName><id>WDM1223</id><lastName>WILLIAMS</lastName><middleName>D</middleName><objects/><state>IL</state><suffix>III</suffix><telephone>281.777.9311</telephone></value></entry></objects></submitMessageResponseObject>';
    Test.setMock(HttpCalloutMock.class, new MockHttpResponse(response));
    try{
        CampaignMemberCriteriaManager.syncCampaignMemberCriterias(stringcampaignId,true);
        CampaignMemberCriteriaManager.getValueIfTrue(false, 'test');
    }Catch(Exception ex){
    }
    Test.stopTest();


}
public static testmethod void CoveringBirthMonthOnRefreshScen3 () 
{

    Campaign cmp = new Campaign();
    cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
    cmp.Service_Line__c='Burn';
    cmp.CRM_SubServiceLineText__c='Dermatology';
    cmp.Tactic__c='Mail';
    cmp.Current_count__c =3636;
    cmp.List_Order_Id__c =89334422;
    cmp.CRM_Refreshed_Count_Date__c=null;
    cmp.List_Order_Select_Grp_Id__c=334823224;
    cmp.count_of_index__c ='765';
    cmp.List_Order_Exclude_Grp_Id__c=387873;
    cmp.Channel__c='Direct Mail';
    insert cmp; 
    System.assertEquals(cmp.Service_Line__c, 'Burn');
    
    Campaign_Demographics__c demographic = new Campaign_Demographics__c();
    demographic.Campaign__c= cmp.Id;
    demographic.AgeTo_UI__c =12;
    demographic.AgeFrom_UI__c =22;
    demographic.CRM_Birth_Month__c='Current Month;Next Month';
    insert demographic;
    System.assertEquals(demographic.AgeTo_UI__c, 12);
            
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
    grp.Campaign__c=cmp.id;
    grp.Exclude__c = True;
    grp.Group_Number__c=1;
    grp.WM_CriteriaGroup_Id__c='8130';
    grp.Inner_Operator__c = 'OR';
    insert grp;
    System.assertEquals( grp.Group_Number__c,1);
   
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
    mem.Campaign__c=cmp.id;
    mem.Exclude__c=true;
    mem.Category__c = 'Demographics';
    mem.Criteria_Group__c = grp.id;
    mem.Field_Name__c='CRM_Birth_Month__c';
    String lstorderexgrpid = '';
    mem.WM_Criteria_Id__c='';
    mem.WM_Sync_Type__c= 'Insert';
    insert mem;
    System.assertEquals(mem.Category__c, 'Demographics');
        
    WundermanLogin__c login = new WundermanLogin__c();
    login.EndpointURL__c= 'https://thcintellisight.uat.kbmg.com/IntellisightListAPI/com/wunderman/api/listOrder';
    login.Session_Id__c ='5685179';
    login.Password__c ='tenet1test';
    login.GetSession__c='GetSession.jsp';
    login.Name ='tenettest1';
    insert login; 
    System.assertEquals(login.Password__c,'tenet1test');
    
    Data_Element_Identifier__c elementidentifier = new Data_Element_Identifier__c();
    elementidentifier.Data_Element_Identifier__c = '561';
    elementidentifier.Field_Name__c ='CRM_Birth_Month__c';
    elementidentifier.Criteria_Group_Name__c = 'Demographics';
    insert elementidentifier;
    string stringcampaignId=cmp.id;
    System.assertEquals(elementidentifier.Field_Name__c,'CRM_Birth_Month__c');
                
  
    Test.startTest();
    string response='<submitMessageResponseObject><responseCode>0</responseCode><transactionId>1568502965</transactionId><attributes><entry><key>NEW_PERSON_IND</key><value>1</value></entry></attributes><jobId>0</jobId><objects><entry><key>person</key><value xsi:type="ns3:person" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns3="com.kbmg.remix.api"><address1>239 GRANT ST</address1><attributes/><city>PARK FOREST</city><country>USA</country><dob>11/03/1971</dob><emailAddress>B_2_WILLIAMS@MYEMAILPROVIDER.COM</emailAddress><firstName>BILLY</firstName><id>WDM1223</id><lastName>WILLIAMS</lastName><middleName>D</middleName><objects/><state>IL</state><suffix>III</suffix><telephone>281.777.9311</telephone></value></entry></objects></submitMessageResponseObject>';
    Test.setMock(HttpCalloutMock.class, new MockHttpResponse(response));
    CampaignMemberCriteriaManager.syncCampaignMemberCriterias(stringcampaignId,false);
    CampaignMemberCriteriaManager.getValueIfTrue(true, 'true');
    Test.stopTest();


}

public static testmethod void improveCoverage(){
	list<Campaign_Member_Criteria__c> cmpmembercritera = new list<Campaign_Member_Criteria__c>();
	list<WundermanLogin__c> cslist = new list<WundermanLogin__c>();
	Campaign cmp1 = new Campaign();
        cmp1.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmp1.Service_Line__c='Burn';
        cmp1.CRM_SubServiceLineText__c='Dermatology';
        cmp1.Tactic__c='Mail';
        cmp1.count_of_index__c ='765';
        cmp1.Channel__c='Direct Mail';
        cmp1.Member_Types__c = 'Campaign Segments';
        insert cmp1;
        
	Campaign cmp = new Campaign();
        cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmp.Service_Line__c='Burn';
        cmp.CRM_SubServiceLineText__c='Dermatology';
        cmp.Tactic__c='Mail';
        cmp.count_of_index__c ='765';
        cmp.Channel__c='Direct Mail';
        cmp.List_Order_Id__c = 1876757;
        cmp.CRM_ParentSegmentedCampaign__c=cmp1.id;
        insert cmp; 
 
    Id auRTId = ReferenceData_PicklistController.recordTypeId('CRM_AudienceUploadJunction__c','Audience_Report');
    CRM_AudienceUploadJunction__c au = new CRM_AudienceUploadJunction__c(CRM_Campaign__c=cmp.id,RecordTypeId=auRTId);
    insert au;
    
    CRM_Search_Criteria__c searchcriteria = new CRM_Search_Criteria__c();
     searchcriteria.CRM_Campaign__c=Cmp.id;
     searchcriteria.CRM_Search_Criteria_Level_1__c ='By Distance';
     searchcriteria.CRM_Search_Criteria_Level_2__c ='PSA';
     searchcriteria.CRM_Search_Criteria_Level_3__c ='CR3';
     searchcriteria.CRM_AdditionalZipCodes__c ='';
     searchcriteria.CRM_ExcludedZipCodes__c ='12345';
     insert searchcriteria;   
    
    Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
        grp.Campaign__c=cmp.id;
        grp.Exclude__c = True;
        grp.Group_Name__c='test';
        grp.WM_CriteriaGroup_Id__c='12';
        grp.WM_Parent_group_Id__c='677';
        grp.Inner_Operator__c = 'OR';
        insert grp;
    
    Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
        mem.Campaign__c=cmp.id;
        mem.Exclude__c=false;
        mem.Category__c = 'Geography';
        mem.Criteria_Group__c = grp.id;
        mem.Field_Name__c='ZipCode__c';
        insert mem;
        cmpmembercritera.add(mem);
        
    Data_Element_Identifier__c elementidentifier = new Data_Element_Identifier__c();
        elementidentifier.Data_Element_Identifier__c = 'ZIPCD';
        elementidentifier.Data_Element_Name__c='ZIP Code';
        elementidentifier.Display_Type_Code__c='GEO.MANUAL';
        //elementidentifier.Value_Mapping__c='{"Out Patient":"O","In Patient":"I"}';
        elementidentifier.Field_Name__c ='ZipCode__c';
        insert elementidentifier;
    
    WundermanLogin__c login = new WundermanLogin__c();
        login.EndpointURL__c= 'https://thcintellisight.uat.kbmg.com/IntellisightListAPI/com/wunderman/api/listOrder';
        login.Session_Id__c ='5685179';
        login.Password__c ='tenet1test';
        login.GetSession__c='GetSession.jsp';
        login.Name ='tenettest1';
        insert login;    
        cslist.add(login);
    
    Campaign_Member_Search_Critera__c searchmem = new Campaign_Member_Search_Critera__c();
        searchmem.Name='Geography';
        searchmem.Inner_Operator__c = 'OR';
        searchmem.Outer_Operator__c = 'AND';  
        searchmem.Requires_SubGroup__c=false;
        insert searchmem;
        
    	CRM_AudienceUploadJunction__c  audiencejunction = marketingDataUtils.createAudienceJunction(cmp.id);
         
    			Set<id> juncid = new Set<id>();
        juncid.add(audiencejunction.Id);
    
        map<string,string> stringmap = new map<string,string>();
        stringmap.put('value','memgrp');
        string listOrderId = '7333';
        String lstordergrpid = '';
        String lstorderexgrpid = '';
        id clonedCampid = cmp.id;
        string fieldName ='ZipCode__c';
        string value = 'Zipcode';
        Id campaignId = cmp.id;
        string stringcampaignId = cmp.id;
        boolean exclude = true;
        string objectname ='Geographic_Info_Information__c';
        integer pageNumber=1;
        List<string> lstWMContactIds =new String[3];
        lstWMContactIds[0]='test';
        lstWMContactIds[1]='test1';
        lstWMContactIds[2]='test2';
        string request='txt';
        string xmlReponse = '<ROOT><RESULT><RETURNCODE>0</RETURNCODE><MESSAGE>Added Criteria element and values</MESSAGE><LIST_ORDER_CRITERIA_ELMNT_ID>4188725</LIST_ORDER_CRITERIA_ELMNT_ID></RESULT></ROOT>';
        string source='sourc';
 		system.debug('&&&id'+campaignId);

	Test.startTest();
  		string response='<submitMessageResponseObject><responseCode>0</responseCode><transactionId>1568502965</transactionId><attributes><entry><key>NEW_PERSON_IND</key><value>1</value></entry></attributes><jobId>0</jobId><objects><entry><key>person</key><value xsi:type="ns3:person" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns3="com.kbmg.remix.api"><address1>239 GRANT ST</address1><attributes/><city>PARK FOREST</city><country>USA</country><dob>11/03/1971</dob><emailAddress>B_2_WILLIAMS@MYEMAILPROVIDER.COM</emailAddress><firstName>BILLY</firstName><id>WDM1223</id><lastName>WILLIAMS</lastName><middleName>D</middleName><objects/><state>IL</state><suffix>III</suffix><telephone>281.777.9311</telephone></value></entry></objects></submitMessageResponseObject>';
  		ID batchID = database.executeBatch(new Audience_dedupeBatch(cmp,juncid),2000);
    Test.setMock(HttpCalloutMock.class, new MockHttpResponse(response));
    	CampaignMemberCriteriaManager.insertCriteria(fieldName,value,campaignId,exclude,objectname);
	    CampaignMemberCriteriaManager.updateCriteria(fieldName,value,campaignId,exclude);
	    CampaignMemberCriteriaManager.deleteCriteria(fieldName,campaignId,exclude);
	    CampaignMemberCriteriaManager.addCampaignMemberCriteriasForClonedCampaign(cmpmembercritera,listOrderId,lstordergrpid,lstorderexgrpid,cmp,clonedCampid );
	    CampaignMemberCriteriaManager.resetCampaignMemberCriteriasSync(campaignId,batchID);
	    CampaignMemberCriteriaManager.setAddOnExclusionCriterias(campaignId);

Test.stopTest();
}

}