objects/Campaign_Member_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Member Criterias</relationshipLabel>
        <relationshipName>Campaign_Member_Criterias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AND</fullName>
                    <default>true</default>
                    <label>AND</label>
                </value>
                <value>
                    <fullName>OR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>WM_Criteria_Id__c</fullName>
        <externalId>true</externalId>
        <label>WM Criteria Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Campaign Member Criteria</label>
    <nameField>
        <displayFormat>CMC{0000000000}</displayFormat>
        <label>Campaign Member Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Member Criterias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AddCriteriasManager.cls
// This class is handling the functional code to insert the crtieria element ids into SFDC. 
Public class AddCriteriasManager 
{    
    // This method is used to insert the criteria element id into Campaign_Member_Criteria__c object along with other info such as SFDCAPIName, Campaignid etc..
    public static void addCriterias (String SFDCAPIName, String operator,String csvValue, String criteriaID, String criteriaGroupID,ID Campaignid) 
    {
        Campaign_Member_Criteria__c cmc = new Campaign_Member_Criteria__c ();
        cmc.Field_Name__c = SFDCAPIName;
        cmc.Operator__c = operator;
        cmc.Value__c = csvValue;
        cmc.WM_Criteria_Id__c = criteriaID;
        cmc.Campaign__c = Campaignid;
        insert cmc;
    }
}