objects/Campaign_Member_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Campaign Member Criteria</label>
    <nameField>
        <displayFormat>CMC{0000000000}</displayFormat>
        <label>Campaign Member Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Member Criterias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_CampaignWizardReferenceData__c.object
<CustomObject>
    <fields>
        <fullName>CRM_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Reference data field to activate and deactivate picklistvalue .</description>
        <inlineHelpText>Activate value for piclkist .</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_ParentServiceLine__c</fullName>
        <description>Field to store name of Parent Service Line.</description>
        <formula>CRM_ParentServiceLineID__r.CRM_ServiceLine__c</formula>
        <inlineHelpText>Field to store name of Parent Service Line.</inlineHelpText>
        <label>Parent Service Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_ServiceSubServiceLine__c</fullName>
        <description>Reference data field to store service lien and sub service line concatenated value .</description>
        <formula>CRM_ParentServiceLineID__r.CRM_ServiceLine__c + &apos; - &apos;+ CRM_SubServiceLine__c</formula>
        <inlineHelpText>Stores service line and sub service line concatenated value .</inlineHelpText>
        <label>Service-Sub Service Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_SubServiceLine__c</fullName>
        <description>Reference data field to store Sub Service line picklist values.</description>
        <inlineHelpText>Stores Sub Service line picklist values .</inlineHelpText>
        <label>Sub Service Line</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>Ref Data - Campaign Wizard</label>
    <nameField>
        <displayFormat>CWRD-{0000000}</displayFormat>
        <label>Campaign Reference Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ref Data - Campaign Wizard</pluralLabel>
    <recordTypes>
        <fullName>Sub_Service_Line</fullName>
        <active>true</active>
        <description>This record type records will be used to maintain Sub Service Line picklist on campaign wizard screen which is dependent on service line values.</description>
        <label>Sub Service Line</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ServSubServiceLineCrtieriaManager.cls
public class ServSubServiceLineCrtieriaManager {
   public static void ServiceSubServiceValuesAsperWDM (Campaign_Member_Criteria__c criteria) {
       if(criteria.Value__c!=null) {
            id RecordTypeidSub = [SELECT id FROM RecordType WHERE SobjectType='CRM_CampaignWizardReferenceData__c' AND DeveloperName='Sub_Service_Line'][0].id;
            List<String> subserviceLines = new List<String> ();
            List<String> lstreturnedSubServiceLine = new List<String> ();
            System.debug('*****criteria.Value__c'+criteria.Value__c);   
            for (String str : criteria.Value__c.split(';')) {
                str=str.trim();
                subserviceLines.add(str);
            }
            System.debug('*****subserviceLines '+subserviceLines);                  
            for(CRM_CampaignWizardReferenceData__c cwr:  [Select id ,CRM_SubServiceLine__c  FROM CRM_CampaignWizardReferenceData__c WHERE Recordtypeid =:RecordTypeidSub and CRM_IsActive__c = true AND CRM_ServiceSubServiceLine__c in:subserviceLines]) 
                lstreturnedSubServiceLine.add(cwr.CRM_SubServiceLine__c);
                
            if(lstreturnedSubServiceLine.size()>0) criteria.Value__c = String.join(lstreturnedSubServiceLine,';');
            System.debug('*****criteria.value*********'+criteria.Value__c);
       }
        
    }
    public static Map<String, String> ServiceLineSubServiceLineMapping() {
        id RecordTypeidSub = [SELECT id FROM RecordType WHERE SobjectType='CRM_CampaignWizardReferenceData__c' AND DeveloperName='Sub_Service_Line'][0].id;
        Map<String,String> mapserServiceLine = new Map<String,String> ();
        for(CRM_CampaignWizardReferenceData__c cwr:  [Select id ,CRM_SubServiceLine__c,CRM_ParentServiceLine__c  FROM CRM_CampaignWizardReferenceData__c WHERE Recordtypeid =:RecordTypeidSub and CRM_IsActive__c = true ]) 
             mapserServiceLine.put(cwr.CRM_SubServiceLine__c,cwr.CRM_ParentServiceLine__c);
                 
        return mapserServiceLine;
        
    }
    public static Map<String, Set<String>> ServiceLineSubServiceSetsMapping() {
        id RecordTypeidSub = [SELECT id FROM RecordType WHERE SobjectType='CRM_CampaignWizardReferenceData__c' AND DeveloperName='Sub_Service_Line'][0].id;
        Map<String, Set<String>> mapserSetServiceLine = new Map<String, Set<String>> ();
        for(CRM_CampaignWizardReferenceData__c cwr:  [Select id ,CRM_SubServiceLine__c,CRM_ParentServiceLine__c  FROM CRM_CampaignWizardReferenceData__c WHERE Recordtypeid =:RecordTypeidSub and CRM_IsActive__c = true ]) 
             if(mapserSetServiceLine .containsKey(cwr.CRM_ParentServiceLine__c))
                 mapserSetServiceLine .get(cwr.CRM_ParentServiceLine__c).add(cwr.CRM_SubServiceLine__c);
             else {
                 Set<String> setSubServLines = new Set<String> ();
                 setSubServLines.add(cwr.CRM_SubServiceLine__c);
                 mapserSetServiceLine.put(cwr.CRM_ParentServiceLine__c,setSubServLines);
             }
                 
        return mapserSetServiceLine;
        
    }

}