objects/Campaign_Location__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Geography By Service Area</relationshipLabel>
        <relationshipName>Campaign_Location</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <formula>Location__r.Zip_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zip Code</label>
        <type>Text</type>
    </fields>
    <label>Campaign Location Information</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Campaign Location No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Geography</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Geographic_Info_Information__c.object
<CustomObject>
    <fields>
        <fullName>Audience_Search_Type__c</fullName>
        <label>Audience Search Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Geography By Boundary</fullName>
                </value>
                <value>
                    <fullName>Geography By Distance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Geography By Boundary</relationshipLabel>
        <relationshipName>Geographic_Info_Informations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <formula>Geographic_Info__r.ZipCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ZipCode</label>
        <type>Text</type>
    </fields>
    <label>Geographic Info Information</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Geographic Info Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Geographic Info Informations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CampaignCriteria_GeographiesController.cls
public class CampaignCriteria_GeographiesController
{
    public Campaign objcampaign {get;set;} 
    public boolean hasServiceAreas {get;set;}
    public boolean hasBoundaries {get;set;}
    public boolean hasDistances {get;set;}
    
    public boolean hasGeoSetup 
    {
        get {return hasServiceAreas || hasBoundaries || hasDistances;}
    }
       
    public CampaignCriteria_GeographiesController(ApexPages.StandardController stdController)
    {
        hasServiceAreas = false;
        hasBoundaries = false;
        hasDistances = false;
        
        this.objcampaign = (Campaign)stdController.getRecord();
        
        integer serviceAreasCount = [Select count() from Campaign_Location__c where Campaign__c=:objcampaign.Id ]; 
        if(serviceAreasCount>0)
           hasServiceAreas = true;
        else
        {
            integer boundariesCount = [Select count() from Geographic_Info_Information__c where Campaign__c=:objcampaign.Id AND Audience_Search_Type__c='Geography By Boundary'];
            if(boundariesCount>0)
                hasBoundaries = true;
            else
            {
                integer distancesCount = [Select count() from Geographic_Info_Information__c where Campaign__c=:objcampaign.Id AND Audience_Search_Type__c='Geography By Distance'];
                if(distancesCount>0)
                    hasDistances = true;
            }        
        }        
    }
    
    public PageReference BackToCampaign()
    {
        return new PageReference('/apex/CampaignWizard?id='+ objcampaign.id + '&stepNo=3');
    }
    
    public PageReference AddServiceAreas()
    {
        return new PageReference('/apex/CampaignCriteria_ServiceAreas?id='+ objcampaign.id);
    } 
    
    public PageReference AddBoundaries()
    {
        return new PageReference('/apex/CampaignCriteria_Boundaries?id='+ objcampaign.id);
    } 
    
    public PageReference AddDistances()
    {
        return new PageReference('/apex/CampaignCriteria_Distances?id='+ objcampaign.id);
    } 
    //start of home address change
     public PageReference AddHomeAddress()
    {
        return new PageReference('/apex/HomeAddress?id='+ objcampaign.id);
    }  
    // end of home address change
    
    //delete All Geography By Service Area records for this campaign
    public pageReference deleteAllGeoServiceArea()
    {
        list<Campaign_Location__c> campLoc = [SELECT Zip_Code__c FROM Campaign_Location__c where campaign__c=:objcampaign.id]; 
        CampaignMemberCriteriaManager.deleteCriteria('ZipCode__c', objcampaign.id, false);
      
        if(campLoc.size()>0)
            delete campLoc;
            
        Pagereference  pg = new Pagereference('/apex/CampaignCriteria_Geographies?Id='+objcampaign.id);
        pg.setRedirect(true);
        return pg;
    }
  
    //delete All Geography By Boundary and Distance records for this campaign
    public pageReference deleteAllGeoBoundaryDistance()
    {
        list<Geographic_Info_Information__c> campLoc = [select id from Geographic_Info_Information__c where Campaign__c=:objcampaign.id limit 10000];
        CampaignMemberCriteriaManager.deleteCriteria('ZipCode__c', objcampaign.id, false);
      
        if(campLoc.size()>0)
            delete campLoc;
        
        Pagereference  pg = new Pagereference('/apex/CampaignCriteria_Geographies?Id='+objcampaign.id);
        pg.setRedirect(true);
        return pg;
    }
    
}