objects/Campaign_Member_Criteria__c.object
<CustomObject>
    <label>Campaign Member Criteria</label>
    <nameField>
        <displayFormat>CMC{0000000000}</displayFormat>
        <label>Campaign Member Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Member Criterias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_CampaignGeographyReferenceData__c.object
<CustomObject>
    <description>Stores Reference data for State, county, CBSA and City</description>
    <fields>
        <fullName>CRM_CBSA__c</fullName>
        <description>Stores CBSA Name</description>
        <externalId>true</externalId>
        <inlineHelpText>Stores CBSA Name</inlineHelpText>
        <label>CBSA</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_County__c</fullName>
        <description>Stores County Name of the County Record</description>
        <inlineHelpText>Enter the County Name of the County Record</inlineHelpText>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_CountysStateID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>state record ID for the respective County record</description>
        <inlineHelpText>State Name of the respective County record</inlineHelpText>
        <label>County&apos;s State ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CRM_CampaignGeographyReferenceData__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>State</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CRM_CampaignGeographyReferenceData__c</referenceTo>
        <relationshipName>CRM_CountyStateMapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRM_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Reference data field to activate and deactivate picklistvalue</description>
        <inlineHelpText>Activate value for picklist</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_StateCode__c</fullName>
        <description>State Record: Stores Value of the State Code</description>
        <externalId>true</externalId>
        <inlineHelpText>State Record: Stores Value of the State Code</inlineHelpText>
        <label>State Code</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Ref Data - Geography</label>
    <nameField>
        <displayFormat>CGRD-{0000000}</displayFormat>
        <label>Campaign Geography Reference Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ref Data - Geography</pluralLabel>
    <recordTypes>
        <fullName>State</fullName>
        <active>true</active>
        <description>Record Type for State</description>
        <label>State</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_CampaignLocationReferenceData__c.object
<CustomObject>
    <description>Stores Reference Data for Region, Market, Hospital and Service Area</description>
    <fields>
        <fullName>CRM_HospitalCode__c</fullName>
        <description>Stores the Hospital Code</description>
        <inlineHelpText>Stores the Hospital Code</inlineHelpText>
        <label>Hospital Code</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_Hospital__c</fullName>
        <description>Hospital Name</description>
        <inlineHelpText>Hospital Name</inlineHelpText>
        <label>Hospital</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Reference data field to activate and deactivate picklistvalue</description>
        <inlineHelpText>Activate value for piclkist.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_Market__c</fullName>
        <description>Stores Market Name of the Market Record</description>
        <inlineHelpText>Stores Market Name of the Market Record</inlineHelpText>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_Region__c</fullName>
        <description>Stores Region Name</description>
        <inlineHelpText>Stores Region Name</inlineHelpText>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Ref Data - Location</label>
    <nameField>
        <displayFormat>CLRD-{0000000}</displayFormat>
        <label>Locations Reference Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ref Data - Locations</pluralLabel>
    <recordTypes>
        <fullName>Hospital</fullName>
        <active>true</active>
        <description>Record Type for Hospital</description>
        <label>Hospital</label>
    </recordTypes>
    <recordTypes>
        <fullName>Market</fullName>
        <active>true</active>
        <description>Record Type for Market</description>
        <label>Market</label>
    </recordTypes>
    <recordTypes>
        <fullName>Region</fullName>
        <active>true</active>
        <description>Record Type for Region</description>
        <label>Region</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_Search_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Search Criterias</relationshipLabel>
        <relationshipName>Search_Criterias_del</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CRM_Search_Criteria_Level_1__c</fullName>
        <label>Search Criteria Level 1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>By Region</fullName>
                </value>
                <value>
                    <fullName>By Market</fullName>
                </value>
                <value>
                    <fullName>By Hospital</fullName>
                </value>
                <value>
                    <fullName>By State</fullName>
                </value>
                <value>
                    <fullName>By County</fullName>
                </value>
                <value>
                    <fullName>By CBSA</fullName>
                </value>
                <value>
                    <fullName>By Distance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CRM_Search_Criteria_Level_2__c</fullName>
        <label>Search Criteria Level 2</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRM_Search_Criteria_Level_3__c</fullName>
        <label>Search Criteria Level 3</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Search Criteria</label>
    <nameField>
        <displayFormat>SC-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Search Criterias</pluralLabel>
    <recordTypes>
        <fullName>Region</fullName>
        <active>true</active>
        <label>Region</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CampaignCriteriaController_Test.cls
@istest
 public class CampaignCriteriaController_Test{
  public static testmethod void CampaignCriteriaMethod(){
    campaign cmp = marketingDataUtils.CreateCampaign();
    Campaign_Member_Criteria__c cmpmember = marketingDataUtils.createCampaignMemberCriteria(cmp.id);
    pagereference testpage = new pagereference ('/apex/CampaignCriteria');
    CRM_Search_Criteria__c csc = new CRM_Search_Criteria__c();
    csc.CRM_Search_Criteria_Level_1__c = 'By Region';
    csc.CRM_Search_Criteria_Level_2__c = 'By Market';
    csc.CRM_Search_Criteria_Level_3__c = 'By Hospital';
    csc.CRM_Campaign__c = cmp.id;
    insert csc;
    List<RecordType> lstRecType = [select developerName,id from RecordType where sObjectType='CRM_CampaignLocationReferenceData__c' AND developerName = 'Region'];
    if(lstRecType.size()>0) {
        CRM_CampaignLocationReferenceData__c clr = new CRM_CampaignLocationReferenceData__c();
        clr.CRM_Hospital__c = 'ABC';
        clr.CRM_Market__c = 'Dallas';
        clr.CRM_Region__c = 'Dallas Market';
        clr.CRM_IsActive__c = true;
        clr.RecordTypeid = lstRecType[0].id;
        clr.CRM_HospitalCode__c = 'By Hospital'; 
        insert clr;
    }
    
    Test.setcurrentPage(testPage);   
    ApexPages.StandardController sc = new ApexPages.standardController(cmp);
    CampaignCriteriaController criteria = new CampaignCriteriaController(sc);
   }
   public static testmethod void CampaignCriteriaMethod2(){
    campaign cmp = marketingDataUtils.CreateCampaign();
    Campaign_Member_Criteria__c cmpmember = marketingDataUtils.createCampaignMemberCriteria(cmp.id);
    pagereference testpage = new pagereference ('/apex/CampaignCriteria');
    CRM_Search_Criteria__c csc = new CRM_Search_Criteria__c();
    csc.CRM_Search_Criteria_Level_1__c = 'By Distance';
    csc.CRM_Search_Criteria_Level_2__c = 'By Market';
    csc.CRM_Search_Criteria_Level_3__c = 'By Hospital';
    csc.CRM_Campaign__c = cmp.id;
    insert csc;
    List<RecordType> lstRecType = [select developerName,id from RecordType where sObjectType='CRM_CampaignLocationReferenceData__c' AND developerName = 'Region'];
    if(lstRecType.size()>0) {
        CRM_CampaignLocationReferenceData__c clr = new CRM_CampaignLocationReferenceData__c();
        clr.CRM_Hospital__c = 'ABC';
        clr.CRM_Market__c = 'Dallas';
        clr.CRM_Region__c = 'Dallas Market';
        clr.CRM_IsActive__c = true;
        clr.RecordTypeid = lstRecType[0].id;
        clr.CRM_HospitalCode__c = 'By Hospital'; 
        insert clr;
    }
    
    Test.setcurrentPage(testPage);   
    ApexPages.StandardController sc = new ApexPages.standardController(cmp);
    CampaignCriteriaController criteria = new CampaignCriteriaController(sc);
   }
    public static testmethod void CampaignCriteriaMethod3(){
    campaign cmp = marketingDataUtils.CreateCampaign();
    Campaign_Member_Criteria__c cmpmember = marketingDataUtils.createCampaignMemberCriteria(cmp.id);
    pagereference testpage = new pagereference ('/apex/CampaignCriteria');
    CRM_Search_Criteria__c csc = new CRM_Search_Criteria__c();
    csc.CRM_Search_Criteria_Level_1__c = 'By State';
    csc.CRM_Search_Criteria_Level_2__c = 'By Market';
    csc.CRM_Search_Criteria_Level_3__c = 'By Hospital';
    csc.CRM_Campaign__c = cmp.id;
    insert csc;
    List<RecordType> lstRecType = [select developerName,id from RecordType where sObjectType='CRM_CampaignLocationReferenceData__c' AND developerName = 'Region'];
    if(lstRecType.size()>0) {
        CRM_CampaignLocationReferenceData__c clr = new CRM_CampaignLocationReferenceData__c();
        clr.CRM_Hospital__c = 'ABC';
        clr.CRM_Market__c = 'Dallas';
        clr.CRM_Region__c = 'Dallas Market';
        clr.CRM_IsActive__c = true;
        clr.RecordTypeid = lstRecType[0].id;
        clr.CRM_HospitalCode__c = 'By Hospital'; 
        insert clr;
    }
    
    Test.setcurrentPage(testPage);   
    ApexPages.StandardController sc = new ApexPages.standardController(cmp);
    CampaignCriteriaController criteria = new CampaignCriteriaController(sc);
   }
    public static testmethod void CampaignCriteriaMethod4(){
    campaign cmp = marketingDataUtils.CreateCampaign();
    Campaign_Member_Criteria__c cmpmember = marketingDataUtils.createCampaignMemberCriteria(cmp.id);
    pagereference testpage = new pagereference ('/apex/CampaignCriteria');
    CRM_Search_Criteria__c csc = new CRM_Search_Criteria__c();
    csc.CRM_Search_Criteria_Level_1__c = 'By State';
    csc.CRM_Search_Criteria_Level_2__c = 'By Market;By State';
    csc.CRM_Search_Criteria_Level_3__c = 'By Hospital;By Market';
    csc.CRM_Campaign__c = cmp.id;
    insert csc;
    List<RecordType> lstRecType = [select developerName,id from RecordType where sObjectType='CRM_CampaignGeographyReferenceData__c' AND developerName = 'State'];
    if(lstRecType.size()>0) {
        CRM_CampaignGeographyReferenceData__c clr = new CRM_CampaignGeographyReferenceData__c();
        clr.CRM_StateCode__c = 'By Market';
        clr.CRM_IsActive__c = true;
        clr.CRM_CBSA__c = 'By State';
        clr.CRM_County__c = 'By Hospital';
        clr.RecordTypeid = lstRecType[0].id;
        insert clr;
        
        CRM_CampaignGeographyReferenceData__c clr2 = new CRM_CampaignGeographyReferenceData__c();
        clr2.CRM_County__c = 'By Hospital';
        clr2.CRM_CountysStateID__c = clr.id;
        clr2.RecordTypeid = lstRecType[0].id;
        clr.CRM_IsActive__c = true;
        insert clr2;
    }
    
    Test.setcurrentPage(testPage);   
    ApexPages.StandardController sc = new ApexPages.standardController(cmp);
    CampaignCriteriaController criteria = new CampaignCriteriaController(sc);
   }
  }