objects/Campaign_Location__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Geography By Service Area</relationshipLabel>
        <relationshipName>Campaign_Location</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Campaign Location</relationshipLabel>
        <relationshipName>Campaign_Location</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Campaign Location Information</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Campaign Location No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Geography</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Geographic__c.object
<CustomObject>
    <label>Geographic Info</label>
    <nameField>
        <displayFormat>Geo-{00000}</displayFormat>
        <label>Geographic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Geographic Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Geographic_Info_Information__c.object
<CustomObject>
    <fields>
        <fullName>Audience_Search_Type__c</fullName>
        <label>Audience Search Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Geography By Boundary</fullName>
                </value>
                <value>
                    <fullName>Geography By Distance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Geography By Boundary</relationshipLabel>
        <relationshipName>Geographic_Info_Informations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Geographic_Info__c</fullName>
        <label>Geographic Info</label>
        <referenceTo>Geographic__c</referenceTo>
        <relationshipLabel>Geographic Info Informations</relationshipLabel>
        <relationshipName>Geographic_Info_Informations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Geographic Info Information</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Geographic Info Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Geographic Info Informations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <label>Location</label>
    <nameField>
        <displayFormat>LOC-{000000}</displayFormat>
        <label>Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CampaignCriteriaGeographies_Test.cls
@istest
public class CampaignCriteriaGeographies_Test
{
 public static testmethod void CampaignCriteriaMethod()
 {
  campaign cmp = marketingDataUtils.CreateCampaign();
  Location__c Loc = marketingDataUtils.createlocation();
  Campaign_Location__c  cmpLoc = marketingDataUtils.createLocationInformation(cmp.id,loc.id);
      pagereference testpage = new pagereference ('/apex/CampaignCriteria_Geographies');
      Test.setcurrentPage(testPage);    
       ApexPages.StandardController sc = new ApexPages.standardController(cmp);
       CampaignCriteria_GeographiesController CampaignCriteria = new CampaignCriteria_GeographiesController(sc);
          CampaignCriteria.AddBoundaries();
          CampaignCriteria.AddDistances();
          CampaignCriteria.AddServiceAreas();
          CampaignCriteria.BackToCampaign();
          CampaignCriteria.deleteAllGeoBoundaryDistance();
          CampaignCriteria.deleteAllGeoServiceArea();
          CampaignCriteria.hasServiceAreas=True;
 }
 public static testmethod void CampaignCriteriaMethod1()
 {
  campaign cmp = marketingDataUtils.CreateCampaign();
  Geographic__c geography = marketingDataUtils.createGeographic();
  Geographic_Info_Information__c geoinfo = new Geographic_Info_Information__c();
     geoinfo.Campaign__c=cmp.id;
     geoinfo.Geographic_Info__c=geography.id;
     geoinfo.Audience_Search_Type__c='Geography By Boundary';
      insert geoinfo;        
    pagereference testpage = new pagereference ('/apex/CampaignCriteria_Geographies');
    Test.setcurrentPage(testPage);    
    ApexPages.StandardController sc = new ApexPages.standardController(cmp);        
    CampaignCriteria_GeographiesController CampaignCriteria = new CampaignCriteria_GeographiesController(sc);
          CampaignCriteria.AddBoundaries();
          CampaignCriteria.AddDistances();
          CampaignCriteria.AddServiceAreas();
          CampaignCriteria.BackToCampaign();
          CampaignCriteria.deleteAllGeoBoundaryDistance();
          CampaignCriteria.deleteAllGeoServiceArea();
          CampaignCriteria.hasServiceAreas=True;
 }
 public static testmethod void CampaignCriteriaMethod2()
 {
  campaign cmp = marketingDataUtils.CreateCampaign();
  Geographic__c geography = marketingDataUtils.createGeographic();
  Geographic_Info_Information__c geoinfo = new Geographic_Info_Information__c();
     geoinfo.Campaign__c=cmp.id;
     geoinfo.Geographic_Info__c=geography.id;
     geoinfo.Audience_Search_Type__c='Geography By Distance';
      insert geoinfo;         
    pagereference testpage = new pagereference ('/apex/CampaignCriteria_Geographies');
    Test.setcurrentPage(testPage);    
    ApexPages.StandardController sc = new ApexPages.standardController(cmp);        
          CampaignCriteria_GeographiesController CampaignCriteria = new CampaignCriteria_GeographiesController(sc);
          CampaignCriteria.AddBoundaries();
          CampaignCriteria.AddDistances();
          CampaignCriteria.AddServiceAreas();
          CampaignCriteria.BackToCampaign();
          CampaignCriteria.deleteAllGeoBoundaryDistance();
          CampaignCriteria.deleteAllGeoServiceArea();
          CampaignCriteria.hasServiceAreas=True;
 }
}