objects/Campaign_Member_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Member Criterias</relationshipLabel>
        <relationshipName>Campaign_Member_Criterias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Criteria_Groups</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Criteria_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Criteria Group</label>
        <referenceTo>Campaign_Member_Criteria_Group__c</referenceTo>
        <relationshipLabel>Campaign Member Criterias</relationshipLabel>
        <relationshipName>Campaign_Member_Criterias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exclude__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>WM_CriteriaGroup_Id__c</fullName>
        <label>WM CriteriaGroup Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Campaign Member Criteria</label>
    <nameField>
        <displayFormat>CMC{0000000000}</displayFormat>
        <label>Campaign Member Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Member Criterias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Campaign_Member_Criteria_Group__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Member Criteria Groups</relationshipLabel>
        <relationshipName>Campaign_Member_Criteria_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exclude__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inner_Operator__c</fullName>
        <label>Inner Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AND</fullName>
                </value>
                <value>
                    <fullName>OR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WM_CriteriaGroup_Id__c</fullName>
        <externalId>true</externalId>
        <label>WM CriteriaGroup Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WM_Parent_group_Id__c</fullName>
        <label>WM Parent group Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Campaign Member Criteria Group</label>
    <nameField>
        <displayFormat>CMCG{000000000}</displayFormat>
        <label>Campaign Member Criteria Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Member Criteria Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CRM_CampaignWizardReferenceData__c.object
<CustomObject>
    <fields>
        <fullName>CRM_SubServiceLine__c</fullName>
        <description>Reference data field to store Sub Service line picklist values.</description>
        <inlineHelpText>Stores Sub Service line picklist values .</inlineHelpText>
        <label>Sub Service Line</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>Ref Data - Campaign Wizard</label>
    <nameField>
        <displayFormat>CWRD-{0000000}</displayFormat>
        <label>Campaign Reference Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ref Data - Campaign Wizard</pluralLabel>
    <recordTypes>
        <fullName>Sub_Service_Line</fullName>
        <active>true</active>
        <description>This record type records will be used to maintain Sub Service Line picklist on campaign wizard screen which is dependent on service line values.</description>
        <label>Sub Service Line</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Criteria_Groups.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ailments</fullName>
    </customValue>
    <customValue>
        <fullName>Demographics</fullName>
    </customValue>
    <customValue>
        <fullName>Encounter Aggregates</fullName>
    </customValue>
    <customValue>
        <fullName>Encounter Codes</fullName>
    </customValue>
    <customValue>
        <fullName>Encounters</fullName>
    </customValue>
    <customValue>
        <fullName>Geography</fullName>
    </customValue>
    <customValue>
        <fullName>Health Indices</fullName>
    </customValue>
    <customValue>
        <fullName>Health Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>HRAs</fullName>
    </customValue>
    <customValue>
        <fullName>Interests</fullName>
    </customValue>
    <customValue>
        <fullName>Models</fullName>
    </customValue>
    <customValue>
        <fullName>Physicians</fullName>
    </customValue>
    <customValue>
        <fullName>Survey Responses</fullName>
    </customValue>
    <customValue>
        <fullName>Living Well</fullName>
    </customValue>
    <customValue>
        <fullName>Service Line</fullName>
    </customValue>
    <masterLabel>Criteria Groups</masterLabel>
</GlobalValueSet>

classes/ServSubServiceLineCrtieriaManager_Test.cls
@isTest
private class ServSubServiceLineCrtieriaManager_Test {
    public static testmethod void method1() {
        Campaign cmp = new Campaign();
        cmp.Name='20170127-103-Detroit-Cardiovascular-Direct Mail-V1';
        cmp.Service_Line__c='Burn';
        cmp.CRM_SubServiceLineText__c='Dermatology';
        cmp.Tactic__c='Mail';
        cmp.count_of_index__c ='765';
        cmp.Channel__c='Direct Mail';
        cmp.List_Order_Id__c = 1876757;
        insert cmp; 
        
        Campaign_Member_Criteria_Group__c  grp = new Campaign_Member_Criteria_Group__c();
        grp.Campaign__c=cmp.id;
        grp.Exclude__c = True;
        grp.Group_Name__c='test';
        grp.WM_CriteriaGroup_Id__c='12';
        grp.WM_Parent_group_Id__c='677';
        grp.Inner_Operator__c = 'OR';
        insert grp;
          
        Campaign_Member_Criteria__c mem= new Campaign_Member_Criteria__c();
        mem.Campaign__c=cmp.id;
        mem.Exclude__c=true;
        mem.Category__c = 'Ailments';
        mem.Criteria_Group__c = grp.id;
        mem.Field_Name__c='ZipCode__c';
        mem.value__c = '32124';
        insert mem;
        List<RecordType> recTypes = [SELECT id FROM RecordType WHERE SobjectType='CRM_CampaignWizardReferenceData__c' AND DeveloperName='Sub_Service_Line'];
        if(recTypes.size()>0) {
        id recTypeid = recTypes[0].id;
            CRM_CampaignWizardReferenceData__c cwr = new CRM_CampaignWizardReferenceData__c ();
            cwr.CRM_SubServiceLine__c = 'Branding-Sub';
            cwr.RecordTypeid = recTypeid;
            insert cwr;
        }
        test.startTest();
        ServSubServiceLineCrtieriaManager.ServiceSubServiceValuesAsperWDM(mem);
        ServSubServiceLineCrtieriaManager.ServiceLineSubServiceLineMapping();
        ServSubServiceLineCrtieriaManager.ServiceLineSubServiceSetsMapping();        
        test.stopTest();
    
    
    }
}