objects/CampaignSequencer__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Counter_Value__c</fullName>
        <label>Counter Value</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CampaignSequencer</label>
</CustomObject>

objects/CRM_AudienceCriteriaRefData__c.object
<CustomObject>
    <description>Object to store Reference Data Explicitly for Audience Criteria</description>
    <fields>
        <fullName>CRM_ClinicalServiceLineID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sub Service Line related Service Line</description>
        <inlineHelpText>Service Line Lookup</inlineHelpText>
        <label>Clinical Service Line ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CRM_AudienceCriteriaRefData__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Clinical Service Line</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CRM_AudienceCriteriaRefData__c</referenceTo>
        <relationshipName>CRM_ClinicalServiceLineID</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRM_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Reference data field to activate and deactivate picklist value</description>
        <inlineHelpText>Reference data field to activate and deactivate picklist value</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Ref Data - Audience Criteria</label>
    <nameField>
        <displayFormat>CARD-{0000000}</displayFormat>
        <label>Audience Reference Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ref Data - Audience Criteria</pluralLabel>
    <recordTypes>
        <fullName>ClinicalServiceLine</fullName>
        <active>true</active>
        <description>Record Type for Clinical Service Line</description>
        <label>Clinical Service Line</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClinicalSubServiceLine</fullName>
        <active>true</active>
        <description>Record Type for Clinical Sub Service Line</description>
        <label>Clinical Sub Service Line</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_CampaignLocationReferenceData__c.object
<CustomObject>
    <description>Stores Reference Data for Region, Market, Hospital and Service Area</description>
    <fields>
        <fullName>CRM_HospitalCode__c</fullName>
        <description>Stores the Hospital Code</description>
        <inlineHelpText>Stores the Hospital Code</inlineHelpText>
        <label>Hospital Code</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Reference data field to activate and deactivate picklistvalue</description>
        <inlineHelpText>Activate value for piclkist.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_MarketCode__c</fullName>
        <description>Market Record: Stores Value of the Market Code</description>
        <inlineHelpText>Market Record: Stores Value of the Market Code</inlineHelpText>
        <label>Market Code</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_Market__c</fullName>
        <description>Stores Market Name of the Market Record</description>
        <inlineHelpText>Stores Market Name of the Market Record</inlineHelpText>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_RegionCode__c</fullName>
        <description>Code of the respective Region Record</description>
        <inlineHelpText>Code of the respective Region Record</inlineHelpText>
        <label>Region Code</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_Region__c</fullName>
        <description>Stores Region Name</description>
        <inlineHelpText>Stores Region Name</inlineHelpText>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Ref Data - Location</label>
    <nameField>
        <displayFormat>CLRD-{0000000}</displayFormat>
        <label>Locations Reference Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ref Data - Locations</pluralLabel>
    <recordTypes>
        <fullName>Hospital</fullName>
        <active>true</active>
        <description>Record Type for Hospital</description>
        <label>Hospital</label>
    </recordTypes>
    <recordTypes>
        <fullName>Market</fullName>
        <active>true</active>
        <description>Record Type for Market</description>
        <label>Market</label>
    </recordTypes>
    <recordTypes>
        <fullName>Region</fullName>
        <active>true</active>
        <description>Record Type for Region</description>
        <label>Region</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_CampaignRefJunction__c.object
<CustomObject>
    <description>Stores the selected values for Channel, Vendor name, Call to action for campaign</description>
    <fields>
        <fullName>CRM_CampaignMapping__c</fullName>
        <description>Mapping between Campaign and Reference Data Records</description>
        <label>CRM_CampaignMapping</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Ref Junction</relationshipLabel>
        <relationshipName>CRM_CampaignRefJunction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CRM_CampaignWizardReferenceData__c</fullName>
        <label>Campaign Wizard Reference Data</label>
        <referenceTo>CRM_CampaignWizardReferenceData__c</referenceTo>
        <relationshipLabel>Campaign Ref Junction</relationshipLabel>
        <relationshipName>Campaign_ref_Junction</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Campaign Ref Junction</label>
    <nameField>
        <label>Campaign ref Junction  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Ref Junction</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CRM_CampaignWizardReferenceData__c.object
<CustomObject>
    <fields>
        <fullName>CRM_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Reference data field to activate and deactivate picklistvalue .</description>
        <inlineHelpText>Activate value for piclkist .</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_IsTargeted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to mark channel as targeted or non targeted .</description>
        <inlineHelpText>Checkbox to mark channel as targeted or non targeted .</inlineHelpText>
        <label>Is Targeted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_ServiceLine__c</fullName>
        <description>Reference data field to store Service line picklist values for campaign wizard screen.</description>
        <externalId>true</externalId>
        <inlineHelpText>Stores service line picklist values for campaign wizard screen.</inlineHelpText>
        <label>Service Line</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Ref Data - Campaign Wizard</label>
    <nameField>
        <displayFormat>CWRD-{0000000}</displayFormat>
        <label>Campaign Reference Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ref Data - Campaign Wizard</pluralLabel>
    <recordTypes>
        <fullName>Call_To_Action</fullName>
        <active>true</active>
        <description>This record type records will be used to maintain Call To Action picklist on campaign wizard screen and it will only be available when channel value is Inbound</description>
        <label>Call To Action</label>
    </recordTypes>
    <recordTypes>
        <fullName>ChannelValues</fullName>
        <active>true</active>
        <description>This record type records will be used to maintain Channel picklist and other dependent values on campaign wizard screen.</description>
        <label>Channel Values</label>
    </recordTypes>
    <recordTypes>
        <fullName>Service_Line</fullName>
        <active>true</active>
        <description>This record type records will be used to maintain Service Line picklist on campaign wizard screen.</description>
        <label>Service Line</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sub_Service_Line</fullName>
        <active>true</active>
        <description>This record type records will be used to maintain Sub Service Line picklist on campaign wizard screen which is dependent on service line values.</description>
        <label>Sub Service Line</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor_Name</fullName>
        <active>true</active>
        <description>This record type records will be used to maintain Vendor Name picklist on campaign wizard screen.</description>
        <label>Vendor Name</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ReferenceData_PicklistController_Test.cls
@istest
 private class ReferenceData_PicklistController_Test{
     public static testmethod void CampaignCriteriaMethod(){
         test.startTest();
         List<RecordType> lstRecType = [select developerName,id from RecordType where sObjectType='CRM_CampaignLocationReferenceData__c' AND developerName = 'Region'];
         if(lstRecType.size()>0) {  
             CRM_CampaignLocationReferenceData__c clr = new CRM_CampaignLocationReferenceData__c ();
             clr.CRM_Region__c = 'Dallas';
             clr.CRM_Market__c= 'Dallas Market';
             insert clr;
             System.assertEquals(clr.CRM_Region__c, 'Dallas');            
             ReferenceData_PicklistController.recordTypeDeveloperName('CRM_CampaignLocationReferenceData__c',lstRecType[0].id);
             ReferenceData_PicklistController.refreshOwnershiptype(lstRecType[0].id);
         }
         List<RecordType> lstRecTypeCRD = [select developerName,id from RecordType where sObjectType='CRM_CampaignWizardReferenceData__c' AND developerName = 'Service_Line'];
         if(lstRecTypeCRD.size()>0) {
             CRM_CampaignWizardReferenceData__c crd = new CRM_CampaignWizardReferenceData__c();
             crd.CRM_IsActive__c = true;
             crd.Recordtypeid = lstRecTypeCRD[0].id;
             crd.CRM_ServiceLine__c= 'Branding';
             insert crd;
             System.assertEquals(crd.CRM_ServiceLine__c, 'Branding'); 
             ReferenceData_PicklistController.serviceLine(true);
              
         }
         List<RecordType> lstRecTypeCLR = [select developerName,id from RecordType where sObjectType='CRM_CampaignLocationReferenceData__c' AND developerName = 'Region'];
         if(lstRecTypeCLR.size()>0) 
             ReferenceData_PicklistController.ownershipOptions();
             
         List<RecordType> lstRecTypeCRDSSL = [select developerName,id from RecordType where sObjectType='CRM_CampaignWizardReferenceData__c' AND developerName = 'Sub_Service_Line'];
         if(lstRecTypeCRDSSL.size()>0) {
             CRM_CampaignWizardReferenceData__c crd = new CRM_CampaignWizardReferenceData__c();
             crd.CRM_IsActive__c = true;
             crd.Recordtypeid = lstRecTypeCRDSSL[0].id;
             crd.CRM_ServiceLine__c= 'Primary Care';
             insert crd;
             List<String> serviceLine = new List<String> ();
             serviceLine.add('Branding');
             System.assertEquals(serviceLine.size(), 1);
             ReferenceData_PicklistController.subServiceLine(true, serviceLine);
             ReferenceData_PicklistController.clinicalServiceLine(true);
         }
         List<RecordType> lstRecTypeCACR = [select developerName,id from RecordType where sObjectType='CRM_AudienceCriteriaRefData__c' AND developerName = 'ClinicalSubServiceLine'];
         if(lstRecTypeCACR.size()>0) {
             List<String> serviceLine = new List<String> ();
             serviceLine.add('Branding');
             CRM_AudienceCriteriaRefData__c cra = new CRM_AudienceCriteriaRefData__c();
             cra.CRM_IsActive__c = true;
             cra.Recordtypeid = lstRecTypeCACR[0].id;
             //cra.CRM_ClinicalServiceLineID__c = 'Branding';
             insert cra;
             System.assertEquals(cra.CRM_IsActive__c, true);
             ReferenceData_PicklistController.clinicalSubServiceLine(false,serviceLine);
             
             
         }
         Campaign c =  new Campaign ();
         c.Name = 'test';
         c.CRM_SelectedOwnershipCriteria__c = 'Hospital,Region';
         insert c;
         System.assertEquals(c.Name, 'test');        
         CRM_CampaignWizardReferenceData__c crd = new CRM_CampaignWizardReferenceData__c();
         List<RecordType> lstRecTypeCRDSSLN = [select developerName,id from RecordType where sObjectType='CRM_CampaignWizardReferenceData__c' AND developerName = 'Sub_Service_Line'];
         if(lstRecTypeCRDSSLN.size()>0) {             
             crd.CRM_IsActive__c = true;
             crd.Recordtypeid = lstRecTypeCRDSSLN[0].id;
             crd.CRM_ServiceLine__c= 'Hematology';
             insert crd;
         }
         System.assertEquals(crd.CRM_ServiceLine__c, 'Hematology');  
         CRM_CampaignRefJunction__c ccr = new CRM_CampaignRefJunction__c();
         ccr.CRM_CampaignMapping__c = c.id;
         ccr.CRM_CampaignWizardReferenceData__c = crd.id;
         insert ccr;
         System.assertEquals(ccr.CRM_CampaignMapping__c, c.id); 
          
         CampaignSequencer__c cs = new CampaignSequencer__c();
         cs.Name =  'test';
         cs.Counter_Value__c = 999;
         insert cs;
         System.assertEquals(cs.Name,  'test');  
         
         list<string> ValuesIds = new list<string> ();
         ValuesIds.add(crd.id);
         System.assertEquals(ValuesIds.size(),  1);  
         
         ReferenceData_PicklistController.updateJunctionObject(c.id, ValuesIds);
         ReferenceData_PicklistController.getCampaignName(c.id);
         ReferenceData_PicklistController.getPickListValues('ChannelValues');
         test.stopTest();
         
     }
     public static testmethod void CampaignCriteriaMethod2(){
         test.startTest();
         ReferenceData_PicklistController.getPickListValues('Call_To_Action');     
         test.stopTest();    
     
     }
     public static testmethod void CampaignCriteriaMethod3(){
         test.startTest();
         ReferenceData_PicklistController.getPickListValues('Vendor_Name');         
         test.stopTest();
     }
     public static testmethod void CampaignCriteriaMethod4(){
         test.startTest();
         ReferenceData_PicklistController.getPickListValues('Service_Line');         
         test.stopTest();
     
     }
     public static testmethod void CampaignCriteriaMetho5(){
         ReferenceData_PicklistController.getPickListValues('Sub_Service_Line'); 
         CRM_CampaignWizardReferenceData__c ccr = new CRM_CampaignWizardReferenceData__c();
         ccr.CRM_IsTargeted__c = false;
         insert ccr;
         System.assertEquals(ccr.CRM_IsTargeted__c, false);
         
         ReferenceData_PicklistController.getCampaignRecordTypeId(ccr.id); 
         Campaign c =  new Campaign ();
         c.Name = 'test';
         c.CRM_SelectedOwnershipCriteria__c = 'Hospital,Region';
         insert c;
         System.assertEquals(c.Name,'test');
         
         CampaignSequencer__c cs = new CampaignSequencer__c();
         cs.Name =  'test';
         cs.Counter_Value__c = 100;
         insert cs;
         System.assertEquals(cs.Name,  'test');
         test.startTest();
         ReferenceData_PicklistController.getCampaignName(c.id);
         test.stopTest();
     }       
     
     public static testmethod void CampaignCriteriaMethod6(){
         ReferenceData_PicklistController.getPickListValues('MemberType');
         CRM_CampaignWizardReferenceData__c ccr = new CRM_CampaignWizardReferenceData__c();
         ccr.CRM_IsTargeted__c = true;
         
         insert ccr;
         System.assertEquals(ccr.CRM_IsTargeted__c , true);
         
         test.startTest();
         ReferenceData_PicklistController.getCampaignRecordTypeId(ccr.id);
         test.stopTest();
         
         
         
     }
     public static testmethod void CampaignCriteriaMethod7(){
         ReferenceData_PicklistController.getPickListValues('Sub_Service_Line'); 
         CRM_CampaignWizardReferenceData__c ccr = new CRM_CampaignWizardReferenceData__c();
         ccr.CRM_IsTargeted__c = false;
         insert ccr;
         System.assertEquals(ccr.CRM_IsTargeted__c , false);
          
         ReferenceData_PicklistController.getCampaignRecordTypeId(ccr.id); 
         Campaign c =  new Campaign ();
         c.Name = 'test';
         c.CRM_SelectedOwnershipCriteria__c = 'Hospital,Region';
        
         insert c;
         System.assertEquals(c.Name ,  'test');
         
         CampaignSequencer__c cs = new CampaignSequencer__c();
         cs.Name =  'test';
         cs.Counter_Value__c = 100;
         insert cs;
         System.assertEquals( cs.Name,  'test');
         
         test.startTest();
         ReferenceData_PicklistController.getCampaignName(c.id);
         test.stopTest();
         
         
     }
          
     public static testmethod void CampaignCriteriaMethod8(){
         test.startTest();
         ReferenceData_PicklistController.getPickListValues('Sub_Service_Line'); 
         CRM_CampaignWizardReferenceData__c ccr = new CRM_CampaignWizardReferenceData__c();
         ccr.CRM_IsTargeted__c = false;
         insert ccr;
         System.assertEquals(ccr.CRM_IsTargeted__c,false);
         
         ReferenceData_PicklistController.getCampaignRecordTypeId(ccr.id); 
         Campaign c =  new Campaign ();
         c.Name = 'test';
         c.CRM_OwnershipType__c= 'Hospital';
         c.CRM_SelectedOwnershipCriteria__c = 'Hospital';
         
         insert c;
         System.assertEquals(c.Name,  'test');
         
         List<RecordType> lstRecType = [select developerName,id from RecordType where sObjectType='CRM_CampaignLocationReferenceData__c' AND developerName = 'Hospital'];
         if(lstRecType.size()>0) {  
         CRM_CampaignLocationReferenceData__c clr = new CRM_CampaignLocationReferenceData__c ();
         clr.CRM_Region__c = 'Dallas';
         clr.CRM_Market__c= 'Dallas Market';
         clr.CRM_HospitalCode__c = 'Hospital';
         clr.Recordtypeid = lstRecType[0].id;
         insert clr;
         System.assertEquals(clr.CRM_Region__c, 'Dallas');
         }
       
         CampaignSequencer__c cs = new CampaignSequencer__c();
         cs.Name =  'test';
         cs.Counter_Value__c = 100;
         insert cs;
         System.assertEquals(cs.Name,  'test');
         
        // ReferenceData_PicklistController.getCampaignName(c.id);
         ReferenceData_PicklistController.refreshOwnershiptype(lstRecType[0].id);
         test.stopTest();
         
         
     }
      public static testmethod void CampaignCriteriaMethod9(){
         test.startTest();
         CRM_CampaignWizardReferenceData__c ccr = new CRM_CampaignWizardReferenceData__c();
         ccr.CRM_IsTargeted__c = false;
         insert ccr;
         System.assertEquals(ccr.CRM_IsTargeted__c, false);
         
         ReferenceData_PicklistController.getCampaignRecordTypeId(ccr.id); 
         Campaign c =  new Campaign ();
         c.Name = 'test';
         c.CRM_OwnershipType__c= 'Region';
         c.CRM_SelectedOwnershipCriteria__c = 'Region';
         c.Audience_Region__c = 'Dallas Region';
         c.Audience_Hospital__c = 'ABC';
         
         insert c;
         System.assertEquals(c.Name,  'test');
         
         List<RecordType> lstRecType = [select developerName,id from RecordType where sObjectType='CRM_CampaignLocationReferenceData__c' AND developerName = 'Region'];
         if(lstRecType.size()>0) {  
         CRM_CampaignLocationReferenceData__c clr = new CRM_CampaignLocationReferenceData__c ();
         clr.CRM_Region__c = 'Region';
         clr.CRM_Market__c= 'Dallas Market';
         clr.CRM_HospitalCode__c = 'ABC';
         clr.CRM_RegionCode__c = 'Region';
         clr.Recordtypeid = lstRecType[0].id;
         insert clr;
         System.assertEquals(clr.CRM_Market__c, 'Dallas Market');
         }
       
         CampaignSequencer__c cs = new CampaignSequencer__c();
         cs.Name =  'test';
         cs.Counter_Value__c = 102;
         insert cs;
         System.assertEquals(cs.Name,  'test');
         
         //ReferenceData_PicklistController.getCampaignName(c.id);
         test.stopTest();
         
         
     }
     public static testmethod void CampaignCriteriaMethod10(){
         Campaign c =  new Campaign ();
         c.Name = 'test';
         c.CRM_OwnershipType__c= 'Market';
         c.CRM_SelectedOwnershipCriteria__c = 'Market';
         c.Audience_Region__c = 'Dallas Market';
         
         insert c;
         System.assertEquals(c.Name,  'test');
         
         Test.setCreatedDate(c.Id, DateTime.newInstance(2017,01,01));
         List<RecordType> lstRecType = [select developerName,id from RecordType where sObjectType='CRM_CampaignLocationReferenceData__c' AND developerName = 'Market'];
         if(lstRecType.size()>0) {  
         CRM_CampaignLocationReferenceData__c clr = new CRM_CampaignLocationReferenceData__c ();
         clr.CRM_Region__c = 'Dallas Region';
         clr.CRM_Market__c= 'Market';
         clr.CRM_HospitalCode__c = 'Market';
         clr.Recordtypeid = lstRecType[0].id;
         insert clr;
         System.assertEquals(clr.CRM_Market__c, 'Market');
         }
       
         CampaignSequencer__c cs = new CampaignSequencer__c();
         cs.Name =  'test';
         cs.Counter_Value__c = 100;
         insert cs;
         System.assertEquals(cs.Name,  'test');
         
         test.startTest();
         //ReferenceData_PicklistController.getCampaignName(c.id);
         ReferenceData_PicklistController.refreshOwnershiptype(lstRecType[0].id);
         test.stopTest();
         
         
     }
                  
     public static testmethod void CampaignCriteriaMethod11(){
         
         Campaign c =  new Campaign ();
         c.Name = 'test';
         c.CRM_OwnershipType__c= 'Market';
         c.CRM_SelectedOwnershipCriteria__c = 'Market';
         c.Audience_Region__c = 'Dallas Market';
         
         insert c;
         System.assertEquals(c.Name,  'test');
         Campaign c2 =  new Campaign ();
         c2.Name = 'test';
         c2.CRM_OwnershipType__c= 'Market';
         c2.CRM_SelectedOwnershipCriteria__c = 'Market';
         c2.Audience_Region__c = 'Dallas Market';
         
         insert c2;
         System.assertEquals(c2.Name,  'test');
        
         List<RecordType> lstRecType = [select developerName,id from RecordType where sObjectType='CRM_CampaignLocationReferenceData__c' AND developerName = 'Market'];
         if(lstRecType.size()>0) {  
         CRM_CampaignLocationReferenceData__c clr = new CRM_CampaignLocationReferenceData__c ();
         clr.CRM_Region__c = 'Dallas Region';
         clr.CRM_Market__c= 'Market';
         clr.CRM_HospitalCode__c = 'Market';
         clr.Recordtypeid = lstRecType[0].id;
         insert clr;
         System.assertEquals(clr.CRM_Market__c, 'Market');
         }
       
         CampaignSequencer__c cs = new CampaignSequencer__c();
         cs.Name =  'test';
         cs.Counter_Value__c = 100;
         insert cs;
         System.assertEquals(cs.Name,  'test');
         test.startTest();
         //ReferenceData_PicklistController.getCampaignName(c.id);
         ReferenceData_PicklistController.refreshOwnershiptype(lstRecType[0].id);
         test.stopTest();
     
     }
     public static testmethod void CampaignCriteriaMethod12(){
        
         Campaign c =  new Campaign ();
         c.Name = 'test';
         c.CRM_OwnershipType__c= 'Region';
         c.CRM_SelectedOwnershipCriteria__c = 'Region';
         c.Audience_Region__c = 'Dallas Region';
         c.Audience_Hospital__c = 'ABC';
         
         insert c;
         System.assertEquals(c.Name,  'test');
         List<RecordType> lstRecType = [select developerName,id from RecordType where sObjectType='CRM_CampaignLocationReferenceData__c' AND developerName = 'Region'];
         if(lstRecType.size()>0) {  
         CRM_CampaignLocationReferenceData__c clr = new CRM_CampaignLocationReferenceData__c ();
         clr.CRM_Region__c = 'Dallas-Region';
         clr.CRM_Market__c= 'Dallas Market';
         clr.CRM_HospitalCode__c = 'ABC';
         clr.CRM_RegionCode__c = 'Region';
         clr.Recordtypeid = lstRecType[0].id;
         insert clr;
         System.assertEquals(clr.CRM_Region__c, 'Dallas-Region');
         }
       
         CampaignSequencer__c cs = new CampaignSequencer__c();
         cs.Name =  'test';
         cs.Counter_Value__c = 102;
         insert cs;
         System.assertEquals(cs.Name,  'test');
         test.startTest();
         //ReferenceData_PicklistController.getCampaignName(c.id);
         test.stopTest();
         
         
     }
     public static testmethod void CampaignCriteriaMethod13(){
         
         Campaign c =  new Campaign ();
         c.Name = 'test';
         c.CRM_OwnershipType__c= 'Region';
         c.CRM_SelectedOwnershipCriteria__c = 'Region';
         c.Audience_Region__c = 'Dallas Region';
         c.Audience_Hospital__c = 'ABC';
         
         insert c;
         System.assertEquals(c.Name,  'test');
         List<RecordType> lstRecType = [select developerName,id from RecordType where sObjectType='CRM_CampaignLocationReferenceData__c' AND developerName = 'Region'];
         if(lstRecType.size()>0) {  
         CRM_CampaignLocationReferenceData__c clr = new CRM_CampaignLocationReferenceData__c ();
         clr.CRM_Region__c = 'region';
         clr.CRM_Market__c= 'Dallas Market';
         clr.CRM_HospitalCode__c = 'ABC';
         clr.CRM_RegionCode__c = 'Region';
         clr.Recordtypeid = lstRecType[0].id;
         insert clr;
         System.assertEquals(clr.CRM_Market__c, 'Dallas Market');
         }
       
         CampaignSequencer__c cs = new CampaignSequencer__c();
         cs.Name =  'test';
         cs.Counter_Value__c = 102;
         insert cs;
         System.assertEquals(cs.Name,  'test');
         
         test.startTest();
        // ReferenceData_PicklistController.getCampaignName(c.id);
         test.stopTest();
         
         
     }
     
     public static testmethod void CampaignCriteriaMethod130()
     {
         
         Campaign c =  new Campaign ();
         c.Name = 'test';
         c.CRM_OwnershipType__c= 'Market';
         c.CRM_SelectedOwnershipCriteria__c = 'DT1';
         c.Service_Line__c = 'enc';
         c.Channel__c = 'Email';
        
         insert c;
         System.assertEquals(c.Name,  'test');
         List<RecordType> lstRecType = [select developerName,id from RecordType where sObjectType='CRM_CampaignLocationReferenceData__c' AND developerName = 'Market'];
         if(lstRecType.size()>0) {  
         CRM_CampaignLocationReferenceData__c clr = new CRM_CampaignLocationReferenceData__c ();
         clr.CRM_Market__c= 'Detroit Market';
         clr.CRM_MarketCode__c = 'DT1';
         clr.Recordtypeid = lstRecType[0].id;
         insert clr;
         System.assertEquals(clr.CRM_Market__c, 'Detroit Market');
         }
       
         CampaignSequencer__c cs = new CampaignSequencer__c();
         cs.Name =  'test';
         cs.Counter_Value__c = 102;
         insert cs;
         System.assertEquals(cs.Name,  'test');
         
         test.startTest();
         ReferenceData_PicklistController.getCampaignName(c.id);
         test.stopTest();
         
         
     }
     
     public static testmethod void CampaignCriteriaMethod131()
     {
         
         Campaign c =  new Campaign ();
         c.Name = 'test';
         c.CRM_OwnershipType__c= 'Region';
         c.CRM_SelectedOwnershipCriteria__c = 'TX1';
         c.Service_Line__c = 'enc';
         c.Channel__c = 'Email';
        
         insert c;
         System.assertEquals(c.Name,  'test');
         List<RecordType> lstRecType = [select developerName,id from RecordType where sObjectType='CRM_CampaignLocationReferenceData__c' AND developerName = 'Region'];
         if(lstRecType.size()>0) {  
         CRM_CampaignLocationReferenceData__c clr = new CRM_CampaignLocationReferenceData__c ();
         clr.CRM_Region__c= 'Texas Region';
         clr.CRM_RegionCode__c = 'TX1';
         clr.Recordtypeid = lstRecType[0].id;
         insert clr;
         System.assertEquals(clr.CRM_Region__c, 'Texas Region');
         }
       
         CampaignSequencer__c cs = new CampaignSequencer__c();
         cs.Name =  'test';
         cs.Counter_Value__c = 102;
         insert cs;
         System.assertEquals(cs.Name,  'test');
         
         test.startTest();
         ReferenceData_PicklistController.getCampaignName(c.id);
         test.stopTest();
         
         
     }
     
}