objects/CRM_AudienceUpload__c.object
<CustomObject>
    <label>Audience Upload</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Audience Upload Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audience Uploads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_UserCampaign__c.object
<CustomObject>
    <fields>
        <fullName>CRM_CampaignId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Campaign Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_UserId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>User Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>User Campaign</label>
    <nameField>
        <displayFormat>UC-{0000000}</displayFormat>
        <label>User Campaign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AudienceUploadHelper_PP1.cls
public with sharing class AudienceUploadHelper_PP1
{

    public static void createJunctionRecords(List<CRM_AudienceUpload__c> uploads)
    {
        Id campaignId = fetchCampaignId();
    }

    private static Id fetchCampaignId()
    {
        List<CRM_UserCampaign__c> userCampaigns = 
        [
            SELECT CRM_CampaignId__c
            FROM CRM_UserCampaign__c
            WHERE CRM_UserId__c =: UserInfo.getUserId()
        ];

        if (userCampaigns.size() != 1)
        {
            //TODO: throw exception
        }

        return userCampaigns[0].CRM_CampaignId__c;
    }  
    
}