objects/CRM_AudienceReport__c.object
<CustomObject>
    <fields>
        <fullName>CRM_AudienceUploadJunction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Audience Upload Junction</label>
        <referenceTo>CRM_AudienceUploadJunction__c</referenceTo>
        <relationshipLabel>Audience Reports</relationshipLabel>
        <relationshipName>Audience_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRM_Campaign__c</fullName>
        <externalId>true</externalId>
        <label>Campaign</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Audience Report</label>
    <nameField>
        <displayFormat>AU-RN-{0000000}</displayFormat>
        <label>Audience Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audience Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_AudienceUpload__c.object
<CustomObject>
    <fields>
        <fullName>CRM_AudienceUploadJunction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Audience Upload Junction</label>
        <referenceTo>CRM_AudienceUploadJunction__c</referenceTo>
        <relationshipLabel>Audience Uploads</relationshipLabel>
        <relationshipName>Audience_Uploads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Audience Upload</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Audience Upload Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audience Uploads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_AudienceUploadJunction__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Audience Upload Junctions</relationshipLabel>
        <relationshipName>CRM_AudienceUploadJunctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Audience Upload Junction</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Audience Upload Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audience Upload Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Tenet_AudienceReportScheduler_Test.cls
@istest
public class Tenet_AudienceReportScheduler_Test{
public static testmethod void executemethod() {
    
 Test.startTest();
     list<CRM_AudienceReport__c> audReport = new list<CRM_AudienceReport__c>();
        list<CRM_AudienceUpload__c>  audienclist = new list<CRM_AudienceUpload__c>();
        Campaign camp = marketingDataUtils.campforhomeaddress();
        CRM_AudienceUploadJunction__c  audiencejunction = marketingDataUtils.createAudienceJunctin(camp.id);
        CRM_AudienceReport__c audiencereport = new CRM_AudienceReport__c();
         audiencereport.CRM_Campaign__c=camp.id;
         audiencereport.CRM_AudienceUploadJunction__c=audiencejunction.id;
       insert audiencereport;
       audReport.add(audiencereport);
    Tenet_AudienceReportScheduler campmembersc = new Tenet_AudienceReportScheduler();
    String CRON_EXP = '0 10 12 21 4 ?';
    String jobId = System.schedule('Sample_name', CRON_EXP, new Tenet_AudienceReportScheduler() ); 
    Campaign_AudienceReportDeleteBatch ds = new Campaign_AudienceReportDeleteBatch ();
    
    ds.createLogs(new MyException('This is bad'),'Test');
 Test.stopTest();
 }
 public class MyException extends Exception {} 
}