objects/CRM_AudienceUploadJunction__c.object
<CustomObject>
    <fields>
        <fullName>CRM_ToDelete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>To Delete</label>
        <type>Checkbox</type>
    </fields>
    <label>Audience Upload Junction</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Audience Upload Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audience Upload Junctions</pluralLabel>
    <recordTypes>
        <fullName>Audience_Report</fullName>
        <active>true</active>
        <description>Will be used to link audience report to campaign</description>
        <label>Audience Report</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AudienceUploadHelper_Test.cls
@istest
public class AudienceUploadHelper_Test 
    {
        public static testmethod void helper1()
        {
        Database.QueryLocator QL;
        Database.BatchableContext BC;
        campaign newCampaigns =marketingDataUtils.createcampforPP();
        Id uploadRecordTYpeId = ReferenceData_PicklistController.recordTypeId('CRM_AudienceUploadJunction__c','Audience_Report');
        CRM_AudienceUploadJunction__c  audiencejunction = marketingDataUtils.createAudienceJunction(newCampaigns.id);
          audiencejunction.CRM_ToDelete__c=false;
          audiencejunction.RecordTypeId=uploadRecordTYpeId;
      update audiencejunction;
            Boolean isAudienceUpload = False;
            AudienceUploadHelper uploadaud = new AudienceUploadHelper();
              AudienceUploadHelper.setUploadJunctionForDelete(newCampaigns.id);
        }

    }