objects/CRM_CampaignWizardReferenceData__c.object
<CustomObject>
    <fields>
        <fullName>CRM_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Reference data field to activate and deactivate picklistvalue .</description>
        <inlineHelpText>Activate value for piclkist .</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_ServiceLine__c</fullName>
        <description>Reference data field to store Service line picklist values for campaign wizard screen.</description>
        <externalId>true</externalId>
        <inlineHelpText>Stores service line picklist values for campaign wizard screen.</inlineHelpText>
        <label>Service Line</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_SubServiceLine__c</fullName>
        <description>Reference data field to store Sub Service line picklist values.</description>
        <inlineHelpText>Stores Sub Service line picklist values .</inlineHelpText>
        <label>Sub Service Line</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>Ref Data - Campaign Wizard</label>
    <nameField>
        <displayFormat>CWRD-{0000000}</displayFormat>
        <label>Campaign Reference Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ref Data - Campaign Wizard</pluralLabel>
    <recordTypes>
        <fullName>Service_Line</fullName>
        <active>true</active>
        <description>This record type records will be used to maintain Service Line picklist on campaign wizard screen.</description>
        <label>Service Line</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sub_Service_Line</fullName>
        <active>true</active>
        <description>This record type records will be used to maintain Sub Service Line picklist on campaign wizard screen which is dependent on service line values.</description>
        <label>Sub Service Line</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DRG_Code__c.object
<CustomObject>
    <fields>
        <fullName>Service_Line__c</fullName>
        <label>Service Line</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Other</fullName>
                </value>
                <value>
                    <fullName>Behavioral</fullName>
                </value>
                <value>
                    <fullName>Burn</fullName>
                </value>
                <value>
                    <fullName>Cardiovascular</fullName>
                </value>
                <value>
                    <fullName>Digestive Disease</fullName>
                </value>
                <value>
                    <fullName>Endocrine</fullName>
                </value>
                <value>
                    <fullName>ENT</fullName>
                </value>
                <value>
                    <fullName>Hematology</fullName>
                </value>
                <value>
                    <fullName>Infectious Disease</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Musculoskeletal</fullName>
                </value>
                <value>
                    <fullName>Nephrology/Urology</fullName>
                </value>
                <value>
                    <fullName>Neuroscience</fullName>
                </value>
                <value>
                    <fullName>Newborn</fullName>
                </value>
                <value>
                    <fullName>OB/GYN</fullName>
                </value>
                <value>
                    <fullName>Oncology</fullName>
                </value>
                <value>
                    <fullName>Ophthalmology</fullName>
                </value>
                <value>
                    <fullName>Poisoning/Drug Tox</fullName>
                </value>
                <value>
                    <fullName>Rehabilation</fullName>
                </value>
                <value>
                    <fullName>Respiratory</fullName>
                </value>
                <value>
                    <fullName>Skin and Breast</fullName>
                </value>
                <value>
                    <fullName>Spine</fullName>
                </value>
                <value>
                    <fullName>Transplant</fullName>
                </value>
                <value>
                    <fullName>Trauma</fullName>
                </value>
                <value>
                    <fullName>Cardiac Services</fullName>
                    <isActive>false</isActive>
                    <label>Cardiac Services</label>
                </value>
                <value>
                    <fullName>General Medicines</fullName>
                    <isActive>false</isActive>
                    <label>General Medicines</label>
                </value>
                <value>
                    <fullName>General Surgery</fullName>
                    <isActive>false</isActive>
                    <label>General Surgery</label>
                </value>
                <value>
                    <fullName>Gynecology</fullName>
                    <isActive>false</isActive>
                    <label>Gynecology</label>
                </value>
                <value>
                    <fullName>Neonatology</fullName>
                    <isActive>false</isActive>
                    <label>Neonatology</label>
                </value>
                <value>
                    <fullName>Neurology</fullName>
                    <isActive>false</isActive>
                    <label>Neurology</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRG Code</label>
    <nameField>
        <displayFormat>DRG-{0000}</displayFormat>
        <label>DRG Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRG Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DRG_Code_Information__c.object
<CustomObject>
    <fields>
        <fullName>DRG_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRG Code</label>
        <referenceTo>DRG_Code__c</referenceTo>
        <relationshipLabel>DRG Code Informations</relationshipLabel>
        <relationshipName>DRG_Code_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <formula>TEXT( DRG_Code__r.Service_Line__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Line</label>
        <type>Text</type>
    </fields>
    <label>DRG Code Information</label>
    <nameField>
        <displayFormat>DRG INFO-{000000}</displayFormat>
        <label>DRG Code Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRG Code Informations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>CRM_ServiceLine__c</fullName>
        <label>Service Line</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRM_SubServiceLine__c</fullName>
        <label>Sub Service Line</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Encounter</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PagingDRGController_Test.cls
@istest
public class PagingDRGController_Test 
{
    public static testMethod void DrgMethod() 
    {
        boolean flag = True;
        boolean exclude = true;
        set < Integer > visitedPage = Null;
        campaign cmp = marketingDataUtils.CreateCampaign();
        DRG_Code__c codes = marketingDataUtils.createDRGcode();
        DRG_Code_Information__c DRGCode = marketingDataUtils.createDRGCodeDetails(cmp.id, codes.id);

        PagingDRGController.WrapSearchResult wrap = new PagingDRGController.WrapSearchResult(codes, flag);
        pagereference testpage = new pagereference('/apex/CampaignCriteria_DRGs');
        Test.setcurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('id', cmp.id);
        //ApexPages.currentPage().getParameters().put('exclude',True);
        ApexPages.StandardController sc = new ApexPages.standardController(cmp);
        PagingDRGController Drg = new PagingDRGController(sc);
        Drg.geo = codes;
        Drg.selectAll = True;
        Drg.selectedDrgNumbere = 'Test';
        Drg.masterSelectAll = False;
        Drg.selectedDescription = 'This is location';
        Drg.searchLocation();
        Drg.selectAll = True;
        Drg.exclude = True;
        Drg.getsearchResult();
        Drg.first();
        Drg.next();
        Drg.previous();
        Drg.last();
        Drg.cancel();
        Drg.saveDemographicServiceArea();
        Drg.clearSearch();
        Drg.quickSave();
    }

    public static testMethod void DrgMethod2() 
    {
        boolean flag = True;
        boolean exclude = True;
        set < Integer > visitedPage = Null;
        campaign cmp = marketingDataUtils.CreateCampaign();
        DRG_Code__c codes = marketingDataUtils.createDRGcode();
        DRG_Code_Information__c DRGCode = marketingDataUtils.createDRGCodeInformation(cmp.id);
        Encounter__c encount = marketingDataUtils.createEncounter(cmp.id);
        PagingDRGController.WrapSearchResult wrap = new PagingDRGController.WrapSearchResult(codes, flag);
        pagereference testpage = new pagereference('/apex/CampaignCriteria_DRGs');
        Test.setcurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('id', cmp.id);

        ApexPages.StandardController sc = new ApexPages.standardController(cmp);
        PagingDRGController Drg = new PagingDRGController(sc);
        Drg.geo = codes;
        Drg.selectAll = True;
        Drg.selectedDrgNumbere = 'Test';
        Drg.masterSelectAll = False;
        Drg.searchLocation();
        Drg.selectAll = True;
        Drg.getsearchResult();
        Drg.first();
        Drg.next();
        Drg.previous();
        Drg.last();
        Drg.cancel();
        Drg.selectAll = False;
        Drg.masterSelectAll = True;
        Drg.saveDemographicServiceArea();
        Drg.clearSearch();
    }
    
    public static testMethod void DrgMethod3() 
    {
        boolean flag = True;
        boolean exclude = True;
        set < Integer > visitedPage = Null;
        string encounterid;
        map < id, DRG_Code__c > masterSearchResult;

        campaign cmp = marketingDataUtils.CreateCampaign();
        DRG_Code__c codes = marketingDataUtils.createDRGcode();
        DRG_Code_Information__c DRGCode = marketingDataUtils.createDRGCodeInformation(cmp.id);
        Encounter__c encount = marketingDataUtils.createEncounter(cmp.id);

        PagingDRGController.WrapSearchResult wrap = new PagingDRGController.WrapSearchResult(codes, flag);
        pagereference testpage = new pagereference('/apex/CampaignCriteria_DRGs');
        Test.setcurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('id', cmp.id);
        //ApexPages.currentPage().getParameters().put('encounterid',encount.id);    
        ApexPages.StandardController sc = new ApexPages.standardController(cmp);
        PagingDRGController Drg = new PagingDRGController(sc);
        Drg.geo = codes;
        Drg.selectAll = True;
        Drg.selectedDrgNumbere = 'Test';
        Drg.masterSelectAll = False;
        Drg.searchLocation();
        Drg.selectAll = True;
        Drg.getsearchResult();
        Drg.first();
        Drg.next();
        Drg.previous();
        Drg.last();
        Drg.encounterid = 'enc123';

        Drg.cancel();
        Drg.saveDemographicServiceArea();
        Drg.clearSearch();
    }
    
    public static testMethod void DrgMethod4() 
    {
        campaign cmp = marketingDataUtils.createcampainDetails();
        DRG_Code__c codes = marketingDataUtils.createDRGcode();
        DRG_Code_Information__c DRGCode = marketingDataUtils.createDRGCodeInformation(cmp.id);
        Encounter__c encount = marketingDataUtils.createEncounter(cmp.id);
        boolean flag = true;
        PagingDRGController.WrapSearchResult wrap = new PagingDRGController.WrapSearchResult(codes, flag);
        pagereference testpage = new pagereference('/apex/CampaignCriteria_DRGs');
        Test.setcurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('id', cmp.id);
        ApexPages.StandardController sc = new ApexPages.standardController(cmp);
        PagingDRGController Drg = new PagingDRGController(sc);
        Drg.geo = codes;
        Drg.cmp.Service_Line__c = 'All Other';
        Drg.cmp.CRM_SubServiceLineText__c = 'Dental';
        Drg.selectedDescription = 'ok this true';
        Drg.searchLocation();
    }
    
    public static testMethod void DrgMethod5() 
    {
        boolean flag = False;
        boolean exclude = true;
        set < Integer > visitedPage = Null;
        campaign cmp = marketingDataUtils.CreateCampaign();
        DRG_Code__c codes = marketingDataUtils.createDRGcode();
        DRG_Code_Information__c DRGCode = marketingDataUtils.createDRGCodeDetails(cmp.id, codes.id);

        PagingDRGController.WrapSearchResult wrap = new PagingDRGController.WrapSearchResult(codes, flag);
        pagereference testpage = new pagereference('/apex/CampaignCriteria_DRGs');
        Test.setcurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('id', cmp.id);
        //ApexPages.currentPage().getParameters().put('exclude',True);
        ApexPages.StandardController sc = new ApexPages.standardController(cmp);
        PagingDRGController Drg = new PagingDRGController(sc);
        Drg.geo = codes;
        Drg.selectAll = True;
        Drg.selectedDrgNumbere = 'Test';
        Drg.masterSelectAll = True;
        Drg.selectedDescription = 'This is location';
        Drg.searchLocation();
        Drg.selectAll = False;
        Drg.exclude = True;
        Drg.getsearchResult();
        Drg.first();
        Drg.next();
        Drg.previous();
        Drg.last();
        Drg.cancel();
        Drg.saveDemographicServiceArea();
        Drg.clearSearch();
        Drg.quickSave();
    }
    
    @isTest
    private static void testLstServiceLineValues()
    {
        boolean flag = True;
        boolean exclude = true;
        set<Integer> visitedPage = null;
        
        Test.startTest();
        campaign cmp = marketingDataUtils.CreateCampaign();
        DRG_Code__c codes = marketingDataUtils.createDRGcode();
        DRG_Code_Information__c DRGCode = marketingDataUtils.createDRGCodeDetails(cmp.id, codes.id);
        
        CRM_CampaignWizardReferenceData__c referenceData1 = new CRM_CampaignWizardReferenceData__c();
        referenceData1.CRM_IsActive__c = true;
        referenceData1.RecordTypeId = [SELECT id FROM RecordType WHERE SobjectType='CRM_CampaignWizardReferenceData__c' AND DeveloperName='Service_Line'][0].Id;
        referenceData1.CRM_ServiceLine__c = 'TestServiceLine';
        insert referenceData1;
        
        CRM_CampaignWizardReferenceData__c referenceData2 = new CRM_CampaignWizardReferenceData__c();
        referenceData2.CRM_IsActive__c = true;
        referenceData2.RecordTypeId = [SELECT id FROM RecordType WHERE SobjectType='CRM_CampaignWizardReferenceData__c' AND DeveloperName='Sub_Service_Line'][0].Id;
        referenceData2.CRM_SubServiceLine__c = 'TestSubServiceLine';
        insert referenceData2;
        

        PagingDRGController.WrapSearchResult wrap = new PagingDRGController.WrapSearchResult(codes, flag);
        pagereference testpage = new pagereference('/apex/CampaignCriteria_DRGs');
        Test.setcurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('id', cmp.id);
        ApexPages.StandardController sc = new ApexPages.standardController(cmp);
        PagingDRGController Drg = new PagingDRGController(sc);
        
        List<SelectOption> serviceLineValues = Drg.lstServiceLineValues;
        List<SelectOption> subServiceLineValues = Drg.getsubserviceLine();
        Drg.callactionmethod();
        
        
        System.assertEquals(serviceLineValues.size(), 2);
        System.assertEquals(subServiceLineValues.size(), 1);
        Test.stopTest();
    }
    
    @isTest
    private static void haldleExistingRecordsTest()
    {
        Test.startTest();
        boolean flag = true;
        campaign cmp = marketingDataUtils.CreateCampaign();
        DRG_Code__c codes = marketingDataUtils.createDRGcode();
        DRG_Code_Information__c DRGCode = marketingDataUtils.createDRGCodeDetails(cmp.id, codes.id);
        
        PagingDRGController.WrapSearchResult wrap = new PagingDRGController.WrapSearchResult(codes, flag);
        pagereference testpage = new pagereference('/apex/CampaignCriteria_DRGs');
        Test.setcurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('id', cmp.id);
        ApexPages.StandardController sc = new ApexPages.standardController(cmp);
        PagingDRGController Drg = new PagingDRGController(sc);
        Drg.geo = codes;
        Drg.selectAll = true;
        Drg.selectedDrgNumbere = 'Test';
        Drg.masterSelectAll = false;
        Drg.selectedDescription = 'This is location';
        Drg.searchLocation();
        Drg.selectAll = true;
        Drg.exclude = true;
        
        Drg.searchLocation();
        
        String[] valSsls = new String[]{'ssl1', 'ssl2'};
        Drg.selectedvalSSL = valSsls;
        Drg.searchLocation();
        Test.StopTest();
    }
    
    @isTest
    private static void haldleExistingRecordsTest1()
    {
        Test.startTest();
        boolean flag = true;
        campaign cmp = marketingDataUtils.CreateCampaign();
        DRG_Code__c codes = marketingDataUtils.createDRGcode();
        DRG_Code_Information__c DRGCode = marketingDataUtils.createDRGCodeDetails(cmp.id, codes.id);
        
        PagingDRGController.WrapSearchResult wrap = new PagingDRGController.WrapSearchResult(codes, flag);
        pagereference testpage = new pagereference('/apex/CampaignCriteria_DRGs');
        Test.setcurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('id', cmp.id);
        ApexPages.StandardController sc = new ApexPages.standardController(cmp);
        PagingDRGController Drg = new PagingDRGController(sc);
        
        Drg.searchLocation();
        Test.StopTest();
    }
}