objects/CRM_CampaignGeographyReferenceData__c.object
<CustomObject>
    <description>Stores Reference data for State, county, CBSA and City</description>
    <fields>
        <fullName>CRM_County__c</fullName>
        <description>Stores County Name of the County Record</description>
        <inlineHelpText>Enter the County Name of the County Record</inlineHelpText>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_CountysStateID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>state record ID for the respective County record</description>
        <inlineHelpText>State Name of the respective County record</inlineHelpText>
        <label>County&apos;s State ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CRM_CampaignGeographyReferenceData__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>State</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CRM_CampaignGeographyReferenceData__c</referenceTo>
        <relationshipName>CRM_CountyStateMapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRM_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Reference data field to activate and deactivate picklistvalue</description>
        <inlineHelpText>Activate value for picklist</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_StateCode__c</fullName>
        <description>State Record: Stores Value of the State Code</description>
        <externalId>true</externalId>
        <inlineHelpText>State Record: Stores Value of the State Code</inlineHelpText>
        <label>State Code</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_State__c</fullName>
        <description>Stores State Name of the State Record</description>
        <externalId>true</externalId>
        <inlineHelpText>Enter the State Name of the State Record</inlineHelpText>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Ref Data - Geography</label>
    <nameField>
        <displayFormat>CGRD-{0000000}</displayFormat>
        <label>Campaign Geography Reference Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ref Data - Geography</pluralLabel>
    <recordTypes>
        <fullName>CBSA</fullName>
        <active>true</active>
        <description>Record Type for CBSA</description>
        <label>CBSA</label>
    </recordTypes>
    <recordTypes>
        <fullName>County</fullName>
        <active>true</active>
        <description>Record Type for County</description>
        <label>County</label>
    </recordTypes>
    <recordTypes>
        <fullName>State</fullName>
        <active>true</active>
        <description>Record Type for State</description>
        <label>State</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_CampaignLocationReferenceData__c.object
<CustomObject>
    <description>Stores Reference Data for Region, Market, Hospital and Service Area</description>
    <fields>
        <fullName>CRM_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Reference data field to activate and deactivate picklistvalue</description>
        <inlineHelpText>Activate value for piclkist.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Ref Data - Location</label>
    <nameField>
        <displayFormat>CLRD-{0000000}</displayFormat>
        <label>Locations Reference Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ref Data - Locations</pluralLabel>
    <recordTypes>
        <fullName>Market</fullName>
        <active>true</active>
        <description>Record Type for Market</description>
        <label>Market</label>
    </recordTypes>
    <recordTypes>
        <fullName>Region</fullName>
        <active>true</active>
        <description>Record Type for Region</description>
        <label>Region</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_Search_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>CRM_AdditionalZipCodes__c</fullName>
        <label>Additional ZIP codes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRM_Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Search Criterias</relationshipLabel>
        <relationshipName>Search_Criterias_del</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CRM_ExcludedZipCodes__c</fullName>
        <label>Excluded ZIP Codes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRM_Search_Criteria_Level_1__c</fullName>
        <label>Search Criteria Level 1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>By Region</fullName>
                </value>
                <value>
                    <fullName>By Market</fullName>
                </value>
                <value>
                    <fullName>By Hospital</fullName>
                </value>
                <value>
                    <fullName>By State</fullName>
                </value>
                <value>
                    <fullName>By County</fullName>
                </value>
                <value>
                    <fullName>By CBSA</fullName>
                </value>
                <value>
                    <fullName>By Distance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CRM_Search_Criteria_Level_2__c</fullName>
        <label>Search Criteria Level 2</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRM_Search_Criteria_Level_3__c</fullName>
        <label>Search Criteria Level 3</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Search Criteria</label>
    <nameField>
        <displayFormat>SC-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Search Criterias</pluralLabel>
    <recordTypes>
        <fullName>Region</fullName>
        <active>true</active>
        <label>Region</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Homeaddress_Controller_Test.cls
@istest
public class Homeaddress_Controller_Test{
public static testmethod void method1(){
Campaign newCampaign = marketingDataUtils.campforhomeaddress(); 
CRM_CampaignLocationReferenceData__c refSA = marketingDataUtils.createServiceArea();
CRM_CampaignLocationReferenceData__c refMarket = marketingDataUtils.createRegionMarket();

CRM_Search_Criteria__c searchcriteria = new CRM_Search_Criteria__c();
     searchcriteria.CRM_Campaign__c=newCampaign.id;
     searchcriteria.CRM_Search_Criteria_Level_1__c ='By Market';
     searchcriteria.CRM_Search_Criteria_Level_2__c ='PSA';
     searchcriteria.CRM_Search_Criteria_Level_3__c ='DT1;EF3;PH2';
     searchcriteria.CRM_AdditionalZipCodes__c ='';
     searchcriteria.CRM_ExcludedZipCodes__c ='1GAP123';
   insert searchcriteria;
   
   pagereference testpage = new pagereference ('/apex/HomeAddress');
   Test.setcurrentPage(testPage); 
       ApexPages.currentPage().getParameters().put('id',newCampaign.id);
       ApexPages.StandardController sc = new ApexPages.standardController(newCampaign);
   Homeaddress_Controller homeadress = new Homeaddress_Controller(sc);
        homeadress.refreshSearchLevel2();
        homeadress.refreshSearchLevel3();
        homeadress.selectedServiceArea.add(refSA.id);
        homeadress.selectedSearchCriteriaLevel2.add(refMarket.id);
        homeadress.saveHomeAddressSearch();
        homeadress.Cancel();
        homeadress.deleteCriteria();
  }
  public static testmethod void method2(){
string sl='By Region';
list<string> sl2=new list<string>{'Primary Service Area'};
list<string> sl3= new list<string>{'Baylor/Tenet JV Region'};   
Campaign newCampaign = marketingDataUtils.campforhomeaddress(); 
CRM_CampaignLocationReferenceData__c refSA = marketingDataUtils.createServiceArea();
CRM_CampaignLocationReferenceData__c  refregion =marketingDataUtils.createRegion();


CRM_Search_Criteria__c searchcriteria = new CRM_Search_Criteria__c();
     searchcriteria.CRM_Campaign__c=newCampaign.id;
     searchcriteria.CRM_Search_Criteria_Level_1__c ='By Region';
     searchcriteria.CRM_Search_Criteria_Level_2__c ='PSA';
     searchcriteria.CRM_Search_Criteria_Level_3__c ='CR3';
     searchcriteria.CRM_AdditionalZipCodes__c ='';
     searchcriteria.CRM_ExcludedZipCodes__c ='';
   insert searchcriteria;

   pagereference testpage = new pagereference ('/apex/HomeAddress');
   Test.setcurrentPage(testPage); 
       ApexPages.currentPage().getParameters().put('id',newCampaign.id);
       ApexPages.StandardController sc = new ApexPages.standardController(newCampaign);
   Homeaddress_Controller homeadress = new Homeaddress_Controller(sc);
        Homeaddress_Controller.searchResult(sl, sl2, sl3);
        homeadress.refreshSearchLevel2();
        homeadress.refreshSearchLevel3();
        homeadress.serviceAreaList = new  List<SelectOption>{};
        homeadress.selectedServiceArea.add(refSA .id);
        homeadress.selectedSearchCriteriaLevel2.add(refregion.id);
        homeadress.saveHomeAddressSearch();

  }
    public static testmethod void method3(){
string sl='By Distance';
list<string> sl2=new list<string>{''};
list<string> sl3= new list<string>{''};    
Campaign newCampaign = marketingDataUtils.campforhomeaddress(); 
CRM_CampaignLocationReferenceData__c refSA = marketingDataUtils.createServiceArea();
CRM_CampaignLocationReferenceData__c refhos = marketingDataUtils.createrefHospital();
CRM_CampaignGeographyReferenceData__c state = marketingDataUtils.createstate();

CRM_Search_Criteria__c searchcriteria = new CRM_Search_Criteria__c();
     searchcriteria.CRM_Campaign__c=newCampaign.id;
     searchcriteria.CRM_Search_Criteria_Level_1__c ='By Distance';
     searchcriteria.CRM_Search_Criteria_Level_2__c ='21';
     searchcriteria.CRM_Search_Criteria_Level_3__c ='DHF';
     searchcriteria.CRM_AdditionalZipCodes__c ='26536;76733';
     searchcriteria.CRM_ExcludedZipCodes__c ='88693;87833';
   insert searchcriteria;
   pagereference testpage = new pagereference ('/apex/HomeAddress');
   Test.setcurrentPage(testPage); 
       ApexPages.currentPage().getParameters().put('id',newCampaign.id);
       ApexPages.StandardController sc = new ApexPages.standardController(newCampaign);
   Homeaddress_Controller homeadress = new Homeaddress_Controller(sc);
        homeadress.refreshSearchLevel2();
        homeadress.refreshSearchLevel3();
        homeadress.selectedSearchCriteriaLevel2.add(refhos.id);
        homeadress.saveHomeAddressSearch();
        
  }
  public static testmethod void method4(){
Campaign newCampaign = marketingDataUtils.campforhomeaddress(); 
CRM_CampaignGeographyReferenceData__c  cbsa =  marketingDataUtils.createrefCBSA();

   pagereference testpage = new pagereference ('/apex/HomeAddress');
   Test.setcurrentPage(testPage); 
       ApexPages.currentPage().getParameters().put('id',newCampaign.id);
       ApexPages.StandardController sc = new ApexPages.standardController(newCampaign);
   Homeaddress_Controller homeadress = new Homeaddress_Controller(sc);
        homeadress.refreshSearchLevel2();
        homeadress.selectedSearchCriteriaLevel2.add(cbsa.id);
        homeadress.saveHomeAddressSearch();
  }
  public static testmethod void method5(){
string sl='By county';
list<string> sl2=new list<string>{'Missouri'};
list<string> sl3= new list<string>{'DALLAS'};
Campaign newCampaign = marketingDataUtils.campforhomeaddress(); 
CRM_CampaignLocationReferenceData__c refSA = marketingDataUtils.createServiceArea();
Id Recordtypesstate = Schema.SObjectType.CRM_CampaignGeographyReferenceData__c.getRecordTypeInfosByName().get('State').getRecordTypeId(); 
      CRM_CampaignGeographyReferenceData__c geostaterefData = new CRM_CampaignGeographyReferenceData__c();
                 geostaterefData.CRM_State__c='Missouri';
                 geostaterefData.CRM_StateCode__c='MO';
                 geostaterefData.CRM_IsActive__c=True;
                 geostaterefData.RecordTypeId=Recordtypesstate;
               insert geostaterefData;
           Id RecordtypeCounty = Schema.SObjectType.CRM_CampaignGeographyReferenceData__c.getRecordTypeInfosByName().get('County').getRecordTypeId(); 
           CRM_CampaignGeographyReferenceData__c countyrefData = new CRM_CampaignGeographyReferenceData__c();
                 countyrefData.CRM_County__c='DALLAS';
                 countyrefData.CRM_CountysStateID__c=geostaterefData.id;
                 countyrefData.CRM_IsActive__c=True;
                 countyrefData.RecordTypeId=RecordtypeCounty;
               insert countyrefData;

CRM_Search_Criteria__c searchcriteria = new CRM_Search_Criteria__c();
     searchcriteria.CRM_Campaign__c=newCampaign.id;
     searchcriteria.CRM_Search_Criteria_Level_1__c ='By County';
     searchcriteria.CRM_Search_Criteria_Level_2__c ='MO';
     searchcriteria.CRM_Search_Criteria_Level_3__c ='DALLAS';
     searchcriteria.CRM_AdditionalZipCodes__c ='';
     searchcriteria.CRM_ExcludedZipCodes__c ='';
   insert searchcriteria;
   pagereference testpage = new pagereference ('/apex/HomeAddress');
   Test.setcurrentPage(testPage); 
        ApexPages.currentPage().getParameters().put('id',newCampaign.id);
        ApexPages.StandardController sc = new ApexPages.standardController(newCampaign);
        Homeaddress_Controller homeadress = new Homeaddress_Controller(sc);
        Homeaddress_Controller.searchResult(sl, sl2, sl3);
        homeadress.refreshSearchLevel2();
        homeadress.selectedSearchCriteriaLevel2.add(geostaterefData.id);
        homeadress.refreshSearchLevel3();
        homeadress.selectedVal.add(countyrefData.id);
        homeadress.saveHomeAddressSearch();
  }
  public static testmethod void method6(){
string sl='By State';
list<string> sl2=new list<string>{'Missouri'};
list<string> sl3= new list<string>{''};   
Campaign newCampaign = marketingDataUtils.campforhomeaddress(); 
CRM_CampaignLocationReferenceData__c refSA = marketingDataUtils.createServiceArea();
CRM_CampaignLocationReferenceData__c refhosket = marketingDataUtils.createrefHospital();
CRM_CampaignGeographyReferenceData__c state =  marketingDataUtils.createstate();

CRM_Search_Criteria__c searchcriteria = new CRM_Search_Criteria__c();
     searchcriteria.CRM_Campaign__c=newCampaign.id;
     searchcriteria.CRM_Search_Criteria_Level_1__c ='By State';
     searchcriteria.CRM_Search_Criteria_Level_2__c ='MO';
     searchcriteria.CRM_Search_Criteria_Level_3__c ='';
     searchcriteria.CRM_AdditionalZipCodes__c ='';
     searchcriteria.CRM_ExcludedZipCodes__c ='';
   insert searchcriteria;

   pagereference testpage = new pagereference ('/apex/HomeAddress');
   Test.setcurrentPage(testPage); 
       ApexPages.currentPage().getParameters().put('id',newCampaign.id);
       ApexPages.StandardController sc = new ApexPages.standardController(newCampaign);
   Homeaddress_Controller homeadress = new Homeaddress_Controller(sc);
        Homeaddress_Controller.searchResult(sl, sl2, sl3);
        homeadress.refreshSearchLevel2();
        homeadress.refreshSearchLevel3();
        homeadress.selectedSearchCriteriaLevel2.add(state.id);
        homeadress.saveHomeAddressSearch();

  }
  public static testmethod void method7(){
Campaign newCampaign = marketingDataUtils.campforhomeaddress(); 
CRM_CampaignLocationReferenceData__c refSA = marketingDataUtils.createServiceArea();
CRM_CampaignGeographyReferenceData__c state =  marketingDataUtils.createstate();
CRM_CampaignGeographyReferenceData__c Cbsa =  marketingDataUtils.createrefCBSA();

CRM_Search_Criteria__c searchcriteria = new CRM_Search_Criteria__c();
     searchcriteria.CRM_Campaign__c=newCampaign.id;
     searchcriteria.CRM_Search_Criteria_Level_1__c ='By CBSA';
     searchcriteria.CRM_Search_Criteria_Level_2__c ='Aberdeen, SD';
     searchcriteria.CRM_Search_Criteria_Level_3__c ='';
     searchcriteria.CRM_AdditionalZipCodes__c ='638863';
     searchcriteria.CRM_ExcludedZipCodes__c ='1GAP123';
   insert searchcriteria;
   pagereference testpage = new pagereference ('/apex/HomeAddress');
   Test.setcurrentPage(testPage); 
       ApexPages.currentPage().getParameters().put('id',newCampaign.id);
       ApexPages.StandardController sc = new ApexPages.standardController(newCampaign);
   Homeaddress_Controller homeadress = new Homeaddress_Controller(sc);
        homeadress.refreshSearchLevel2();
        homeadress.saveHomeAddressSearch();
  }
}