objects/CRM_AudienceReport__c.object
<CustomObject>
    <fields>
        <fullName>CRM_AudienceUploadJunction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Audience Upload Junction</label>
        <referenceTo>CRM_AudienceUploadJunction__c</referenceTo>
        <relationshipLabel>Audience Reports</relationshipLabel>
        <relationshipName>Audience_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Audience Report</label>
    <nameField>
        <displayFormat>AU-RN-{0000000}</displayFormat>
        <label>Audience Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audience Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_AudienceUploadJunction__c.object
<CustomObject>
    <fields>
        <fullName>CRM_ToDelete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>To Delete</label>
        <type>Checkbox</type>
    </fields>
    <label>Audience Upload Junction</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Audience Upload Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audience Upload Junctions</pluralLabel>
    <recordTypes>
        <fullName>Audience_Report</fullName>
        <active>true</active>
        <description>Will be used to link audience report to campaign</description>
        <label>Audience Report</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Campaign_AudienceReportDeleteBatch.cls
/*
    This class will delte Audience Upload Junction records which are marked for deletion and child Audience Upload records
*/
public class Campaign_AudienceReportDeleteBatch implements Database.Batchable<sObject>,Database.Stateful{
    public final String query;
    
    public Campaign_AudienceReportDeleteBatch (){
        query = 'select id from CRM_AudienceReport__c where CRM_AudienceUploadJunction__r.CRM_ToDelete__c=true OR CRM_AudienceUploadJunction__c=null';
    }
    public Database.QueryLocator start(Database.BatchableContext BC){
        
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC,List<sObject> audienceReport){
        try{
            delete audienceReport;
            
            Database.emptyRecycleBin(audienceReport);
        }catch(Exception ex){
            createLogs(ex, 'Campaign_AudienceReportDeleteBatch:Execute');
        }   
    }
        
    public void finish(Database.BatchableContext BC){
        try{
            Id uploadRecordTYpeId = ReferenceData_PicklistController.recordTypeId('CRM_AudienceUploadJunction__c','Audience_Report');
            list<CRM_AudienceUploadJunction__c> deleteAudienceJunctionList = new list<CRM_AudienceUploadJunction__c>();
            deleteAudienceJunctionList = [select id from CRM_AudienceUploadJunction__c where recordTypeId=:uploadRecordTYpeId AND CRM_ToDelete__c=true limit 5000];
            delete deleteAudienceJunctionList;
        }catch(Exception ex){
             createLogs(ex, 'Campaign_AudienceReportDeleteBatch:Finish');
        }   
    }
    
    public void createLogs(Exception ex, string sr){
        Tenet_Exception_Handler logError = new Tenet_Exception_Handler();
        logError.creatExceptionLog(ex,null,sr);
    }

}