objects/CRM_AudienceUpload__c.object
<CustomObject>
    <fields>
        <fullName>CRM_AudienceUploadJunction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Audience Upload Junction</label>
        <referenceTo>CRM_AudienceUploadJunction__c</referenceTo>
        <relationshipLabel>Audience Uploads</relationshipLabel>
        <relationshipName>Audience_Uploads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Audience Upload</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Audience Upload Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audience Uploads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_AudienceUploadJunction__c.object
<CustomObject>
    <fields>
        <fullName>CRM_ToDelete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>To Delete</label>
        <type>Checkbox</type>
    </fields>
    <label>Audience Upload Junction</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Audience Upload Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audience Upload Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Campaign_AudienceUploadDeleteBatch.cls
/*
	This class will delte Audience Upload Junction records which are marked for deletion and child Audience Upload records
*/
public class Campaign_AudienceUploadDeleteBatch implements Database.Batchable<sObject>,Database.Stateful{
	public final String query;
	
	public Campaign_AudienceUploadDeleteBatch(){
		query = 'select id from CRM_AudienceUpload__c where CRM_AudienceUploadJunction__r.CRM_ToDelete__c=true OR CRM_AudienceUploadJunction__c=null';
	}
	public Database.QueryLocator start(Database.BatchableContext BC){
	    
	    return Database.getQueryLocator(query);
	}
	
	public void execute(Database.BatchableContext BC,List<sObject> audienceUpload){
	
		delete audienceUpload;
		
		Database.emptyRecycleBin(audienceUpload);
	
	}
	    
	public void finish(Database.BatchableContext BC){
		
		delete [select id from CRM_AudienceUploadJunction__c where CRM_ToDelete__c=true limit 10000];
	
	}

}