objects/Error_Log__c.object
<CustomObject>
    <description>Error_Log Custom object stores the Integration transaction error records between Tenet Marketing Org and Wunderman system.</description>
    <fields>
        <fullName>Error_Description__c</fullName>
        <label>Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Line_Number__c</fullName>
        <label>Error Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Source__c</fullName>
        <description>Store information about the Source, where error originated.</description>
        <label>Error Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Name Match</fullName>
                </value>
                <value>
                    <fullName>Query API Builder</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Error_Type__c</fullName>
        <label>Error Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opened_Date_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Opened Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Err{00000000}</displayFormat>
        <label>Error Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Tenet_Exception_Handler.cls
/*
    Created By : Amit Dahiya
    Created Date : September 2, 2016
    Objective : This class will be used to log exception in system which will occur during Name Match sync process
*/
public class Tenet_Exception_Handler{

    public void creatExceptionLog(Exception ex, Lead respondentDetails,String source){
        //log issue in system
        Error_Log__c errorLog = new Error_Log__c();
        if(respondentDetails!=null){
            errorLog.Lead__c=respondentDetails.Id;
        }
        errorLog.Error_Line_Number__c=ex.getLineNumber();
        errorLog.Error_Description__c=ex.getMessage();
        errorLog.Error_Source__c=source;
        errorLog.Error_Type__c=ex.getTypeName();
        errorLog.Stack_Trace__c=ex.getStackTraceString();
        errorLog.Opened_Date_Time__c=DateTime.Now();
        
        insert errorLog;
        
    }
	public void creatExceptionLog(HttpResponse ex, Lead respondentDetails,String source){
        //log issue in system
        Error_Log__c errorLog = new Error_Log__c();
        if(respondentDetails!=null){
            errorLog.Lead__c=respondentDetails.Id;
        }
        //errorLog.Error_Line_Number__c=ex.getLineNumber();
        if(ex.getBody().length()>32768)
            errorLog.Error_Description__c=ex.getBody().substring(0, 32767);
        else
            errorLog.Error_Description__c=ex.getBody();
        errorLog.Error_Source__c=source;
        errorLog.Error_Type__c='Issue In Response';
        errorLog.Stack_Trace__c='Response Status Code: '+ex.getStatusCode();
        errorLog.Opened_Date_Time__c=DateTime.Now();
        
        insert errorLog;
        
    }
}